### ISSUE TITLE
shaders.xr isn't present.

### ISSUE THREAD

**Issue by MonoLityczny** [OGSR/OGSR-Engine#109]
Hello. I wanted to ask about adding 3D Scopes to model.
I did a one sample model, and added models_lense shader to model with notepad++ but where's shaders.xr? I want to do it with SDK. Thanks.

**Comment by joye-ramone** [comment]
Hi @MonoLityczny 
I am not exact sure about SDK, but you can use ogf data changer tool to assign any shander to any mesh on model.
Also, **models_lense_scope** is not a part of shaders.xr. It is lua based shander.
You can grab it from OGSE Resources repo:
https://github.com/OGSR/OGSR-Resources/blob/ogsr_engine/gamedata/shaders/r2/models_lense_scope.ps
https://github.com/OGSR/OGSR-Resources/blob/ogsr_engine/gamedata/shaders/r2/models_lense_scope.s

**Comment by joye-ramone** [comment]
Use this https://drive.google.com/open?id=1LSmq0LBzqWkPsrKznFzxFCnF-N7kgwoU

**Comment by romanpopulik** [comment]
Hi. It still doesnt work. I was able to change shader name even with notapad++ (glass_stalker_refl has the same number of characters) but on loading screen the game crashes with log:

> [error]Expression    : FATAL ERROR
> [error]Function      : CResourceManager::_GetBlender
> [error]File          : c:\projects\ogsr-engine\ogsr_engine\xr_3da\resourcemanager.cpp
> [error]Line          : 46
> [error]Description   : Shader 'models\models_lense_scope' not found in library.

**Comment by joye-ramone** [comment]
Did you clean shader cache after you add models_lense_scope  ?

**Comment by romanpopulik** [comment]
I've just tried. I deleted all files in Documents\Stalker-SHOC\logs\shader_cache folder, but it doesnt help, still the same error. Also, models_lense_scope didnt appear in shader_cache folder.

**Comment by joye-ramone** [comment]
Then you add it in a wrong way.
I use all shaders from ogse-resources and all works good - I see compiled models_lense_scope.ps and models can use it

**Comment by romanpopulik** [comment]
Where do you see compiled models_lense_scope.ps ? In shaders chache ?

**Comment by romanpopulik** [comment]
[gamedata.zip](https://github.com/OGSR/OGSR-Engine/files/2826099/gamedata.zip)

**Comment by romanpopulik** [comment]
Another issue - looks like horizontal rotation is mirrored in scope view:
https://youtu.be/g9n-E7t3eJ0

**Comment by joye-ramone** [comment]
You need to rotate lense on scope to fix this.

**Comment by romanpopulik** [comment]
It helped, thanks :-)

**Comment by joye-ramone** [comment]
@romanpopulik  So all good now? 
Can I close this issue?

**Comment by romanpopulik** [comment]
Just last thing. What is the relation between scope_zoom_factor and scope_lense_fov_factor ? I mean, in example, when I set scope_zoom_factor to value with no zoom at all (it's 90 with hud_fov 50) which value should I use for scope_lense_fov_factor to get 4x zoom ?

**Comment by romanpopulik** [comment]
Btw - great job with this feature. I finished SVD and it works like a charm.

**Comment by joye-ramone** [comment]
There is not correlation between scope_lense_fov_factor and scope_zoom_factor
But, scope_lense_fov_factor depend on actual user fov and sometimes it requer some testing to find correct value.
Also, it is good idea to use scope_inertion_factor with scope_lense_fov_factor  to limit mouse speed when use lense.

**Comment by romanpopulik** [comment]
Ah, I see. Thanks for the info. If you I could help with anything, I'll gladly do this.
