### ISSUE TITLE
Different reload sounds for pistols

### ISSUE THREAD

**Issue by romanpopulik** [OGSR/OGSR-Engine#112]
As pistols have different reload animations by default, is an additional reload sound added to new engine ?

**Comment by romanpopulik** [comment]
However, I know how to change the code to add this sound, but I cant compile engine. I use Visual Studio 2017 and gets a lot of errors. Do you have somewhere instructions how to setup VS ?

**Comment by joye-ramone** [comment]
What sounds you need? For what anims?
To build project you need to install correct versions of Windows SDK.
I install these versions: https://i.imgur.com/k909gti.png

**Comment by romanpopulik** [comment]
For pistols **anim_reload** and **anim_reload_empty** use the same sound **snd_reload**
All I need is to define different sounds for these two anims.

**Comment by romanpopulik** [comment]
But I'm installing Windows SDK and maybe I'll be able to do that myself. I edited VC++ directories paths in VS and now I have only 19 errors "Failed to locate: CL.exe"

**Comment by romanpopulik** [comment]
`1>------ Odbudowanie wszystkiego rozpoczęte: Projektlzo, Konfiguracja: Release x64 ------
2>------ Odbudowanie wszystkiego rozpoczęte: Projektcommon, Konfiguracja: Release x64 ------
3>------ Odbudowanie wszystkiego rozpoczęte: Projektbsincgen, Konfiguracja: Release Win32 ------
4>------ Odbudowanie wszystkiego rozpoczęte: Projektbin2h, Konfiguracja: Release Win32 ------
1>TRACKER : error TRK0005: Failed to locate: "CL.exe". Nie można odnaleźć określonego pliku.
1>
1>
1>Kompilowanie projektu „lzo.vcxproj” wykonane — NIEPOWODZENIE.
2>TRACKER : error TRK0005: Failed to locate: "CL.exe". Nie można odnaleźć określonego pliku.
2>
2>
5>------ Odbudowanie wszystkiego rozpoczęte: ProjektxrCore, Konfiguracja: Release x64 ------
2>Kompilowanie projektu „common.vcxproj” wykonane — NIEPOWODZENIE.
6>------ Odbudowanie wszystkiego rozpoczęte: Projektlibvorbis_static, Konfiguracja: Release x64 ------
3>TRACKER : error TRK0005: Failed to locate: "CL.exe". Nie można odnaleźć określonego pliku.
3>
3>
3>Kompilowanie projektu „bsincgen.vcxproj” wykonane — NIEPOWODZENIE.
4>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VC\VCTargets\Microsoft.CppBuild.targets(391,5): warning MSB8028: Katalog pośredni (native-tools\Release\) zawiera pliki udostępnione z innego projektu (bsincgen.vcxproj). Może to spowodować niepoprawne zachowanie podczas oczyszczania i ponownej kompilacji.
7>------ Odbudowanie wszystkiego rozpoczęte: Projektlibvorbisfile_static, Konfiguracja: Release x64 ------
4>TRACKER : error TRK0005: Failed to locate: "CL.exe". Nie można odnaleźć określonego pliku.
4>
4>
4>Kompilowanie projektu „bin2h.vcxproj” wykonane — NIEPOWODZENIE.
8>------ Odbudowanie wszystkiego rozpoczęte: Projektlibogg_static, Konfiguracja: Release x64 ------
5>TRACKER : error TRK0005: Failed to locate: "CL.exe". Nie można odnaleźć określonego pliku.
5>
5>
5>Kompilowanie projektu „xrCore.vcxproj” wykonane — NIEPOWODZENIE.
9>------ Odbudowanie wszystkiego rozpoczęte: ProjektxrCDB, Konfiguracja: Release x64 ------
6>TRACKER : error TRK0005: Failed to locate: "CL.exe". Nie można odnaleźć określonego pliku.
6>
6>
6>Kompilowanie projektu „libvorbis_static.vcxproj” wykonane — NIEPOWODZENIE.
10>------ Odbudowanie wszystkiego rozpoczęte: ProjektLuaJIT, Konfiguracja: Release x64 ------
7>TRACKER : error TRK0005: Failed to locate: "CL.exe". Nie można odnaleźć określonego pliku.
7>
7>
7>Kompilowanie projektu „libvorbisfile_static.vcxproj” wykonane — NIEPOWODZENIE.
11>------ Odbudowanie wszystkiego rozpoczęte: ProjektOpenAL32, Konfiguracja: Release x64 ------
8>TRACKER : error TRK0005: Failed to locate: "CL.exe". Nie można odnaleźć określonego pliku.
8>
8>
8>Kompilowanie projektu „libogg_static.vcxproj” wykonane — NIEPOWODZENIE.
9>TRACKER : error TRK0005: Failed to locate: "CL.exe". Nie można odnaleźć określonego pliku.
9>
9>
9>Kompilowanie projektu „xrCDB.vcxproj” wykonane — NIEPOWODZENIE.
12>------ Odbudowanie wszystkiego rozpoczęte: Projektode, Konfiguracja: Release x64 ------
13>------ Odbudowanie wszystkiego rozpoczęte: ProjektxrParticles, Konfiguracja: Release x64 ------
10>'cl' is not recognized as an internal or external command,
10>operable program or batch file.
10>
10>*******************************************************
10>*** Build FAILED -- Please check the error messages ***
10>*******************************************************
10>Nie można odnaleźć określonego pliku.
10>Nie można odnaleźć określonego pliku.
10>Nie można odnaleźć określonego pliku.
10>Nie można odnaleźć określonego pliku.
10>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VC\VCTargets\Microsoft.MakeFile.Targets(49,5): error MSB3073: Polecenie „
10>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VC\VCTargets\Microsoft.MakeFile.Targets(49,5): error MSB3073: 		RD /S/Q ..\bin
10>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VC\VCTargets\Microsoft.MakeFile.Targets(49,5): error MSB3073: 		call msvcbuild.bat x64
10>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VC\VCTargets\Microsoft.MakeFile.Targets(49,5): error MSB3073: 
10>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VC\VCTargets\Microsoft.MakeFile.Targets(49,5): error MSB3073: 		if not exist "C:\Users\Administrator\Desktop\OGSR-Engine-1.0.542\\bin_x64\*.*" (
10>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VC\VCTargets\Microsoft.MakeFile.Targets(49,5): error MSB3073: 			md "C:\Users\Administrator\Desktop\OGSR-Engine-1.0.542\\bin_x64\"
10>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VC\VCTargets\Microsoft.MakeFile.Targets(49,5): error MSB3073: 		)
10>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VC\VCTargets\Microsoft.MakeFile.Targets(49,5): error MSB3073: 		copy /Y "..\bin\x64\LuaJIT.dll" "C:\Users\Administrator\Desktop\OGSR-Engine-1.0.542\\bin_x64\LuaJIT.dll"
10>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VC\VCTargets\Microsoft.MakeFile.Targets(49,5): error MSB3073: 		copy /Y "..\bin\x64\LuaJIT.pdb" "C:\Users\Administrator\Desktop\OGSR-Engine-1.0.542\\bin_x64\LuaJIT.pdb"
10>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VC\VCTargets\Microsoft.MakeFile.Targets(49,5): error MSB3073: 		if not exist "C:\Users\Administrator\Desktop\OGSR-Engine-1.0.542\\bin_x64\..\ogsr_engine\_LIB\Engine\Release\x64\*.*" (
10>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VC\VCTargets\Microsoft.MakeFile.Targets(49,5): error MSB3073: 			md "C:\Users\Administrator\Desktop\OGSR-Engine-1.0.542\\bin_x64\..\ogsr_engine\_LIB\Engine\Release\x64\"
10>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VC\VCTargets\Microsoft.MakeFile.Targets(49,5): error MSB3073: 		)
10>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VC\VCTargets\Microsoft.MakeFile.Targets(49,5): error MSB3073: 		copy /Y "..\bin\x64\LuaJIT.lib" "C:\Users\Administrator\Desktop\OGSR-Engine-1.0.542\\bin_x64\..\ogsr_engine\_LIB\Engine\Release\x64\LuaJIT.lib"
10>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VC\VCTargets\Microsoft.MakeFile.Targets(49,5): error MSB3073: 		if not exist "C:\Users\Administrator\Desktop\OGSR-Engine-1.0.542\\bin_x64\..\ogsr_engine\_LIB\Engine\Release\x64\*.*" (
10>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VC\VCTargets\Microsoft.MakeFile.Targets(49,5): error MSB3073: 			md "C:\Users\Administrator\Desktop\OGSR-Engine-1.0.542\\bin_x64\..\ogsr_engine\_LIB\Engine\Release\x64\"
10>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VC\VCTargets\Microsoft.MakeFile.Targets(49,5): error MSB3073: 		)
10>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VC\VCTargets\Microsoft.MakeFile.Targets(49,5): error MSB3073: 		copy /Y "..\bin\x64\LuaJIT.exp" "C:\Users\Administrator\Desktop\OGSR-Engine-1.0.542\\bin_x64\..\ogsr_engine\_LIB\Engine\Release\x64\LuaJIT.exp"
10>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VC\VCTargets\Microsoft.MakeFile.Targets(49,5): error MSB3073: 	” zostało zakończone przez kod 1.
10>Kompilowanie projektu „luajit.vcxproj” wykonane — NIEPOWODZENIE.
14>------ Odbudowanie wszystkiego rozpoczęte: ProjektLuabind, Konfiguracja: Release x64 ------
13>TRACKER : error TRK0005: Failed to locate: "CL.exe". Nie można odnaleźć określonego pliku.
13>
13>
13>Kompilowanie projektu „xrParticles.vcxproj” wykonane — NIEPOWODZENIE.
12>TRACKER : error TRK0005: Failed to locate: "CL.exe". Nie można odnaleźć określonego pliku.
12>
12>
12>Kompilowanie projektu „default.vcxproj” wykonane — NIEPOWODZENIE.
15>------ Odbudowanie wszystkiego rozpoczęte: Projektlibtheora_static, Konfiguracja: Release x64 ------
16>------ Odbudowanie wszystkiego rozpoczęte: ProjektxrRender, Konfiguracja: Release x64 ------
11>Generating bsinc_inc.h
11>'native-tools\bsincgen' is not recognized as an internal or external command,
11>operable program or batch file.
11>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(209,5): error MSB6006: Polecenie „cmd.exe” zakończone przez kod 9009.
11>Kompilowanie projektu „OpenAL32.vcxproj” wykonane — NIEPOWODZENIE.
17>------ Odbudowanie wszystkiego rozpoczęte: ProjektxrSound, Konfiguracja: Release x64 ------
14>TRACKER : error TRK0005: Failed to locate: "CL.exe". Nie można odnaleźć określonego pliku.
14>
14>
14>Kompilowanie projektu „luabind.vcxproj” wykonane — NIEPOWODZENIE.
18>------ Pominięte odbudowanie wszystkiego: ProjektxrCompress, Konfiguracja: Release x64 ------
18>Projekt nie został wybrany do kompilowania dla tej konfiguracji rozwiązania 
15>TRACKER : error TRK0005: Failed to locate: "CL.exe". Nie można odnaleźć określonego pliku.
15>
15>
15>Kompilowanie projektu „libtheora_static.vcxproj” wykonane — NIEPOWODZENIE.
17>TRACKER : error TRK0005: Failed to locate: "CL.exe". Nie można odnaleźć określonego pliku.
17>
17>
17>Kompilowanie projektu „xrSound.vcxproj” wykonane — NIEPOWODZENIE.
19>------ Odbudowanie wszystkiego rozpoczęte: ProjektxrGame, Konfiguracja: Release x64 ------
16>TRACKER : error TRK0005: Failed to locate: "CL.exe". Nie można odnaleźć określonego pliku.
16>
16>
16>Kompilowanie projektu „xrRender_R2.vcxproj” wykonane — NIEPOWODZENIE.
19>TRACKER : error TRK0005: Failed to locate: "CL.exe". Nie można odnaleźć określonego pliku.
19>
19>
19>Kompilowanie projektu „xrGame.vcxproj” wykonane — NIEPOWODZENIE.
20>------ Odbudowanie wszystkiego rozpoczęte: ProjektXR_3DA, Konfiguracja: Release x64 ------
20>TRACKER : error TRK0005: Failed to locate: "CL.exe". Nie można odnaleźć określonego pliku.
20>
20>
20>Kompilowanie projektu „XR_3DA.vcxproj” wykonane — NIEPOWODZENIE.
========== Ponowna kompilacja: 0 zakończono powodzeniem, 19 zakończono niepowodzeniem, 1 pominięto ==========
`

**Comment by romanpopulik** [comment]
I think I installed everything. Also I tried to find solution on this CL.exe, no success.

**Comment by joye-ramone** [comment]
@romanpopulik not need to edit anything in project files to compile it.
Looks that you installation of VS 2017 is broken or something like this.

**Comment by romanpopulik** [comment]
Almost made it:
`1>------ Kompilacja rozpoczęta: Projekt: LuaJIT, Konfiguracja: Release x64 ------
2>------ Kompilacja rozpoczęta: Projekt: OpenAL32, Konfiguracja: Release x64 ------
3>------ Pominięta kompilacja: ProjektxrCompress, Konfiguracja: Release x64 ------
3>Projekt nie został wybrany do kompilowania dla tej konfiguracji rozwiązania 
1>'cl' is not recognized as an internal or external command,
1>operable program or batch file.
1>
1>*******************************************************
1>*** Build FAILED -- Please check the error messages ***
1>*******************************************************
1>Nie można odnaleźć określonego pliku.
1>Nie można odnaleźć określonego pliku.
1>Nie można odnaleźć określonego pliku.
1>Nie można odnaleźć określonego pliku.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.MakeFile.Targets(44,5): error MSB3073: Polecenie „
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.MakeFile.Targets(44,5): error MSB3073: 		if not exist "..\bin\x64\LuaJIT.dll" (
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.MakeFile.Targets(44,5): error MSB3073: 			call msvcbuild.bat x64
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.MakeFile.Targets(44,5): error MSB3073: 		)
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.MakeFile.Targets(44,5): error MSB3073: 
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.MakeFile.Targets(44,5): error MSB3073: 		if not exist "C:\Users\Administrator\Desktop\OGSR-Engine-1.0.542\\bin_x64\LuaJIT.dll" (
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.MakeFile.Targets(44,5): error MSB3073: 			if not exist "C:\Users\Administrator\Desktop\OGSR-Engine-1.0.542\\bin_x64\*.*" (
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.MakeFile.Targets(44,5): error MSB3073: 				md "C:\Users\Administrator\Desktop\OGSR-Engine-1.0.542\\bin_x64\"
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.MakeFile.Targets(44,5): error MSB3073: 			)
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.MakeFile.Targets(44,5): error MSB3073: 			copy /Y "..\bin\x64\LuaJIT.dll" "C:\Users\Administrator\Desktop\OGSR-Engine-1.0.542\\bin_x64\LuaJIT.dll"
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.MakeFile.Targets(44,5): error MSB3073: 			copy /Y "..\bin\x64\LuaJIT.pdb" "C:\Users\Administrator\Desktop\OGSR-Engine-1.0.542\\bin_x64\LuaJIT.pdb"
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.MakeFile.Targets(44,5): error MSB3073: 		)
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.MakeFile.Targets(44,5): error MSB3073: 		if not exist "C:\Users\Administrator\Desktop\OGSR-Engine-1.0.542\\bin_x64\..\ogsr_engine\_LIB\Engine\Release\x64\LuaJIT.lib" (
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.MakeFile.Targets(44,5): error MSB3073: 			if not exist "C:\Users\Administrator\Desktop\OGSR-Engine-1.0.542\\bin_x64\..\ogsr_engine\_LIB\Engine\Release\x64\*.*" (
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.MakeFile.Targets(44,5): error MSB3073: 				md "C:\Users\Administrator\Desktop\OGSR-Engine-1.0.542\\bin_x64\..\ogsr_engine\_LIB\Engine\Release\x64\"
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.MakeFile.Targets(44,5): error MSB3073: 			)
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.MakeFile.Targets(44,5): error MSB3073: 			copy /Y "..\bin\x64\LuaJIT.lib" "C:\Users\Administrator\Desktop\OGSR-Engine-1.0.542\\bin_x64\..\ogsr_engine\_LIB\Engine\Release\x64\LuaJIT.lib"
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.MakeFile.Targets(44,5): error MSB3073: 		)
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.MakeFile.Targets(44,5): error MSB3073: 		if not exist "C:\Users\Administrator\Desktop\OGSR-Engine-1.0.542\\bin_x64\..\ogsr_engine\_LIB\Engine\Release\x64\LuaJIT.exp" (
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.MakeFile.Targets(44,5): error MSB3073: 			if not exist "C:\Users\Administrator\Desktop\OGSR-Engine-1.0.542\\bin_x64\..\ogsr_engine\_LIB\Engine\Release\x64\*.*" (
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.MakeFile.Targets(44,5): error MSB3073: 				md "C:\Users\Administrator\Desktop\OGSR-Engine-1.0.542\\bin_x64\..\ogsr_engine\_LIB\Engine\Release\x64\"
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.MakeFile.Targets(44,5): error MSB3073: 			)
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.MakeFile.Targets(44,5): error MSB3073: 			copy /Y "..\bin\x64\LuaJIT.exp" "C:\Users\Administrator\Desktop\OGSR-Engine-1.0.542\\bin_x64\..\ogsr_engine\_LIB\Engine\Release\x64\LuaJIT.exp"
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.MakeFile.Targets(44,5): error MSB3073: 		)
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.MakeFile.Targets(44,5): error MSB3073: 	” zostało zakończone przez kod 1.
1>Kompilowanie projektu „luajit.vcxproj” wykonane — NIEPOWODZENIE.
2>   Trwa tworzenie biblioteki C:\Users\Administrator\Desktop\OGSR-Engine-1.0.542\\3rd_party\_LIB\Release\x64\OpenAL32.lib i obiektu C:\Users\Administrator\Desktop\OGSR-Engine-1.0.542\\3rd_party\_LIB\Release\x64\OpenAL32.exp
2>OpenAL32.vcxproj -> C:\Users\Administrator\Desktop\OGSR-Engine-1.0.542\\bin_x64\OpenAL32.dll
2>        1 file(s) copied.
4>------ Kompilacja rozpoczęta: Projekt: XR_3DA, Konfiguracja: Release x64 ------
4>LINK : fatal error LNK1104: nie można otworzyć pliku „LuaJIT.lib”
4>Kompilowanie projektu „XR_3DA.vcxproj” wykonane — NIEPOWODZENIE.
========== Kompilacja: 1 zakończono powodzeniem, 2 zakończono niepowodzeniem, 16 zaktualizowano, 1 pominięto ==========
`

**Comment by romanpopulik** [comment]
Nevermind, I made it.

**Comment by joye-ramone** [comment]
So all good now? 
Can I close this issues?

**Comment by romanpopulik** [comment]
Yes. Thanks.
