### ISSUE TITLE
Turning off scope_texture mode

### ISSUE THREAD

**Issue by romanpopulik** [OGSR/OGSR-Engine#114]
Is there any way to use 3d scopes in weapons with attachable scopes ? I already tested 3d scopes in SVD, but I had to set its scope_status value to 0, otherwise scope_texture mode runs when aiming.

**Comment by joye-ramone** [comment]
Set scope_texture to empty string
scope_texture =

**Comment by romanpopulik** [comment]
Works like a charm, thanks

**Comment by romanpopulik** [comment]
Another question - what about zoom_offset, zoom_rotate_x and zoom_rotate_y settings for attachable scopes ? I tried to add values to scope section in weapons.ltx but it doesn't work.

**Comment by joye-ramone** [comment]
It will not work. Add this to weapon hud section
One weapon section can use only one scope so it is enough

**Comment by romanpopulik** [comment]
Ok. So I set up these values for the scope. But when I detach the scope, ironsights are not aligned. Otherwise, if I align the ironsights, the scope is misaligned.

**Comment by joye-ramone** [comment]
Correct. There is not separate zoom params for scopr and ironsights in engine.
So you can do it via scripts to modify this params when scope attached\detached

**Comment by ferr-um** [comment]
Приветствую. Я так понимаю что больше одной линзы движок не может корректно обрабатывать в прицеле? Так как при использовании больше двух линз в одном прицеле движок начинает путать расстановку и выдавать поочередно их исключая то одну, то другую из перехвата.

**Comment by joye-ramone** [comment]
Да, так и есть. А зачем 2 линзы может быть нужно ?

**Comment by ferr-um** [comment]
чтобы придать более объемный вид прицелу и закрыть дыры с обоих сторон самого прицела, а то визуально это выглядит очень не презентабельно на мой взгляд, то есть линза в середине самого прицела, а по краям так называемые затычки, это работает когда прицел жестко привязан к оружию, но как только в конфиге делается возможность установки и снятия прицела начинается трабла и движок начинает юзать то одну линзу игноря вторую, то наоборот. Поэтому хотелось бы у вас спросить, есть ли возможность при создании конфига оружия со съемным прицелом указать движку параметры как при использовании не съемного прицела, чтобы он не сбивался при выборе.

**Comment by joye-ramone** [comment]
Я ничего не понял из описания. Сорри. 
У меня с линзами проблем нету. Никто не мешает их поставить несколько но выбрать другой шейдер.

**Comment by ferr-um** [comment]
пробовали, все работает на оружии с прицелом который не снимается с оружия, как только изменяется параметр в конфиге оружия на съемный, начинаются проблемы, сначала при прицеливании идет первая линза, отсоединяем прицел и снова ставим, уже показывается вторая линза и так поочередно.

**Comment by ferr-um** [comment]
думаю что с одной линзой проблемы точно не будет, все будет работать идеально, но хотелось бы реализовать задумку с несколькими линзами.

**Comment by joye-ramone** [comment]
И съемные прицелы тоже у меня работаю. 
Что значит "идет" первая лизна ?
Есть видео или скрин ?

**Comment by ferr-um** [comment]
Вот на скриншоте показана линза с другим шейдером она первая и служит как затычка чтоб прицел не просматривался - http://images.vfl.ru/ii/1552562146/cd68555f/25761396.jpg присоединяю прицел и в режиме прицеливания она показывается почему-то, но шейдер models_lense_scope назначен не на нее, далее снимаю прицел и снова устанавливаю, в режиме прицеливания показывается уже вторая линза с назначенным models_lense_scope - http://images.vfl.ru/ii/1552562280/5bb29697/25761424.jpg .. снова снимаю прицел и снова устанавливаю, снова показывается первая линза на которую не назначен models_lense_scope и так все повторяется по кругу.

**Comment by joye-ramone** [comment]
хм. такого никогда не видел.
scope_lense_fov_factor в секции прицела же ?

**Comment by ferr-um** [comment]
да, в секции прицела (секция прицела для удобности сделана в конфиге самого оружия, для тестирования)

**Comment by joye-ramone** [comment]
тогда заведи плз отдельный баг с описанием и моделькой + конфигами оружия.
у меня такой проблемы нету и быстро по совету поправить ее будет сложно.
так же, возможно все таки что то не так с моделькой, а это нужно что бы кто то ее глянул

**Comment by ferr-um** [comment]
Хорошо спасибо. А вы сами пробовали использовать несколько линз или только одну тестировали? Я понимаю что проблемы на одной линзе возможно и не будет (просто не пробовал еще), пересмотрю данные, по возможным ошибкам и если ничего не найду, то вероятно придется создавать по вашему совету баг-репост.

**Comment by joye-ramone** [comment]
На всех прицелах несколько линз.
Баг завести стоит, но это не значит что его поправят быстро, потому что проблемы пока только у тебя.

**Comment by ferr-um** [comment]
Ясно, спасибо.

**Comment by ferr-um** [comment]
В параметрах wpn_addon_scope достаточно ли только указать значение scope_lense_fov_factor или еще какие то параметры дополнительно нужны? Пробовал на другой модели оружия где указана всего лишь одна линза с шейдером models_lense_scope эффект при снятии и установки прицела примерно такой же ... один раз показывается линза но без самого прицела, второй раз показывается корпус прицела без линзы. Где-то подробнее есть информация по добавлению параметров в конфиг оружия, все что я изучил, сводится к прописыванию параметра scope_lense_fov_factor и если прицел съемный, то эта секция прописывается в конфиг прицела .... но так корректной работоспособности пока что на моделях оружия со съемным прицелом так и не добился. На моделях оружия с параметрами scope_status = 1, все работает как положено, на моделях оружия с параметром scope_status = 2 происходят чудеса, при установке прицела получается либо так - http://images.vfl.ru/ii/1552571589/88fb5688/25763216.jpg либо вот так - http://images.vfl.ru/ii/1552571646/3f137e58/25763224.jpg .....

**Comment by joye-ramone** [comment]
А. это у тебя наверно другой баг. Который кстити поправили совсем недавно.
у тебя на прицеле не все кости отображаются. Это известный баг ТЧ для сложный моделей прицелов. вот фикс https://github.com/OGSR/OGSR-Engine/commit/ef07585bba6fd859387826da5a8874e34a177cd2
Жди релиз следующий

**Comment by ferr-um** [comment]
спасибо, а то я весь мозг уже сломал себе выискивая проблему по костям.

**Comment by KRodinn** [comment]
@ferr-um скачай движок отсюда и проверь, есть ли на нем эта проблема: https://ci.appveyor.com/project/OGSR/ogsr-engine/builds/23047089/job/7v60qdwroc97eqtj/artifacts

**Comment by ferr-um** [comment]
Спасибо за поддержку, проверю напишу.

**Comment by ferr-um** [comment]
Еще раз спасибо за быстрое реагирование, все заработало корректно, прицел ставится и снимается, текстуры все на месте. Линза как одна, так и несколько отображаются правильно. При снятии и повторной установке прицела, все так-же корректно работает.

Скриншот в режиме прицеливания - http://images.vfl.ru/ii/1552574075/96cf3c13/25763566.jpg
Скриншот показа линзы прикрытия на прицеле, чтоб насквозь не просматривалось - http://images.vfl.ru/ii/1552574141/bc5431fe/25763582.jpg

Еще возник такой вопрос со слов пользователей, нет ли возможности указания параметра scope_lense_fov_factor для самой линзы, чтобы в режиме прокручивания колесом мыши было увеличение или уменьшение параметра scope_lense_fov_factor. Если же используется scope_lense_fov_factor, то увеличение или уменьшение происходит как в самой линзе, так и с худ рук с оружием приближается или отдаляется. Для меня лично это вполне удобно при игре, но вот всякие реалисты говорят что это не правдоподобно и было бы логичнее использовать что-то в параметрах scope_lense_fov_factor, чтобы он имел такую возможность уменьшать или увеличивать размер увеличения линзы посредством прокрутки колеса мыши и не использовался параметр scope_dynamic_zoom.

**Comment by joye-ramone** [comment]
Динамический зум чисто для линз пока не реализован. в планах

**Comment by ferr-um** [comment]
Спасибо за ответ. Будем ждать новостей по разработке.

**Comment by ferr-um** [comment]
Возник еще вопрос, секция zoom_offset в режиме прицеливания для оружия без прицелом и без прицела как-то разграничивается в худовой секции? Так как в оригинале игры режим прицеливания с оптикой перекрывался текстурой, здесь есть возможность указать координаты для оружия без прицела и с прицелом? Или это уже только скриптами можно реализовать?

**Comment by joye-ramone** [comment]
Только скриптами. Перечитай этот issue. я уже писал про это

**Comment by ferr-um** [comment]
Да я читал, с помощью переводчика переписку и он меня подвел, так как я сначала обрадовался что хотя бы одну секцию прицела можно указать в настройках - http://images.vfl.ru/ii/1552638605/edf3f184/25772142.jpg а оказалось что это одна позиция для прицеливания независимо от установленных аддонов на оружие. Не подскажите наиболее правильный вариант скриптования, в каком направлении вернее идти, насколько мне попадались варианты, все сводится к подмене модели оружия с установленным аддоном и настроенной позицией zoom_offset. Возможно уже есть что-то более практичное и удобное решение, и планируется ли в дальнейших версиях движка как-то эту проблему поправить? Если планируется, тогда лучше подождать вариант решения проблемы от разработчиков и не заниматься кустарным способом, который в дальнейшем только усугубит адаптацию модификации к новой версии движка.

**Comment by joye-ramone** [comment]
Подменять модель не нужно. Есть скриптовый доступ к параметрам через set_hud_offset и set_hud_rotate. Пример https://github.com/OGSR/OGSR-Resources/blob/15f27129338ca38d3c5beb5cbbd786e7c7837f03/gamedata/scripts/ogse_bind_weapon.script#L49

А когда будет в движке - сложно сказать, когда то будет точно.

**Comment by ferr-um** [comment]
спасибо за информацию.

**Comment by KRodinn** [comment]
@ferr-um динамический зум и новые параметры `zoom_offset`, `zoom_rotate` сделали [**вот в этой сборке движка**](https://ci.appveyor.com/project/OGSR/ogsr-engine/builds/23265610/job/29qhm1oihbqh50f9/artifacts).
Описание здесь: #121

**Comment by ferr-um** [comment]
> @ferr-um динамический зум и новые параметры `zoom_offset`, `zoom_rotate` сделали [**вот в этой сборке движка**](https://ci.appveyor.com/project/OGSR/ogsr-engine/builds/23265610/job/29qhm1oihbqh50f9/artifacts).
> Описание здесь: #121

Вот душевное спасибо, несколько дней бились всем скопом, но на этом движке ни в какую не хотели наши костыли работать. Спасибо ушел вникать и тестировать!!!

**Comment by ferr-um** [comment]
К сожалению  новые параметры в конфиге оружия не подхватывает новая версия движка, все прописал, вбил различные значения, почистил кеш, начинал новую игру, прицеливание идет либо по мушке с целиком, либо в режиме установленного ПГ, или в режиме включенной планки прицеливания ПГ ...  вот третий параметр scope_grenade_zoom_offset я так и не понял для каких целей ибо даже с установленным прицелом в режиме прицеливания из ПГ оптика не задействована вроде бы (на автомате АК точно), там прицеливание на боковой планке, возможно это на других видах оружия или в модификациях актуально. Тем не менее не понимаю в чем проблема ибо увеличение линзы (логика работы scope_dynamic_zoom для прицелов с scope_lense_fov_factor - теперь динамический зум будет именно в линзе) работает, правда интересно, при прокрутке либо макс увеличение, либо мин и так по кругу не зависимо в какую сторону крутишь, никакого шага в 0.3 не ощущаю (но это мелочи), самое важное это разграничение настраивания прицеливания, которое не хочет работать, возможно я что-то упустил? Возможно снова требуется какой-то скриптовый костыль? Или данные надо прописывать выше основных параметров прицеливания? Или эти параметры нужно в конфиг съемного прицела нужно прописывать?

**Comment by joye-ramone** [comment]
добавил
 use_scope_zoom=true
 use_scope_grenade_zoom=true
?

**Comment by ferr-um** [comment]
> добавил
> use_scope_zoom=true
> use_scope_grenade_zoom=true
> ?

Конечно, несколько раз прочитал, что к чему и для чего - http://images.vfl.ru/ii/1553263085/9ba53a41/25875843.png

**Comment by joye-ramone** [comment]
параметры
use_scope_zoom=true
use_scope_grenade_zoom=true
должны быть в секции оружия, не худа
scope_grenade_zoom_offset  - нужно в режиме ПГ и когда установлен прицел, потому как в некоторых модели прицел закрывает точку прицеливания через ПГ

**Comment by ferr-um** [comment]
спасибо, я так и понял что где-то накосячил .. и еще вопрос в режиме включения прицеливания через ПГ линза отключается, это так задумано или она все же должна работать или должна переключаться на текстуру обычную в окне линзы? В некоторых случаях возможно это будет видно, так как оптика видна, или я снова что-то упустил?

**Comment by joye-ramone** [comment]
Да линза отключаеться. Под ней должна быть обычная линза с текстурой.

**Comment by ferr-um** [comment]
Отлично, ну главное знать что должно быть, и не пытаться найти чего там нет) Спасибо за поддержку, очень много возможностей, физически просто пока не переварю, все хочется потестировать, настроить, оценить потенциал. А тут еще и обновы шикарные подъезжают, по настройке прицеливания просто класс. Проверил все отлично работает, и последнее, параметр если scope_dynamic_zoom = true, steps, min_zoom_k, то то значения ниже указываются steps = 4 например и min_zoom_k = 0,3?

**Comment by joye-ramone** [comment]
Не совсем, пример параметра такой scope_dynamic_zoom = true, 4, 0.3
Тогда 4 - кол-во шагов зума
0.3 - коф-н для зума. То есть минимальный зум будет = scope_lense_fov_factor  * 0.3
можно указать только
scope_dynamic_zoom = true, 4
или вообще
scope_dynamic_zoom = true

тогда будут браться параметры по умолчанию из движка

**Comment by ferr-um** [comment]
все ясно, дописать через запятую, где движок по порядку  считает данные для scope_dynamic_zoom = true. Еще раз спасибо, быстро, оперативно, доступно и понятно.

**Comment by joye-ramone** [comment]
Да, только не забывай, числа ж конфиге должны быть написаны с точкой 0.3 - правильно, 0,3 - не правильно. Ну это все как обычно и в других местах в конфигах

**Comment by ferr-um** [comment]
да, это понятно, деление целого точкой только.

**Comment by ferr-um** [comment]
Прописал параметры в конфиг прицела так: scope_dynamic_zoom  = true,  5, 0.1 это должно означать что шагов при прокручивании колесиком должно быть 5 и минимальный зум 0.1, но эффекта никакого, два варианта работы максимальный и минимальный по кругу идут. Параметры же оптики в конфиге прицела верно? Там и линза и динамический зум и эти параметры, новая игра результатов не принесла, возможно я снова где-то допустил ошибку. На любом зуме делится количество шагов столько указано или есть минимальные какие-то параметры при которых зум будет работать в двух режимах?

**Comment by joye-ramone** [comment]
Вот прописал себе в прицел теже параметры
scope_lense_fov_factor	= 18
scope_dynamic_zoom 	= true, 5, 0.1

получил 5 шагов. Минимальный зум 0,1 * 18 - почти без приближения

**Comment by ferr-um** [comment]
будем искать.

**Comment by joye-ramone** [comment]
А у тебя что получается зум вообще по кругу крутиться больше-меньше даже если колесо мышки крутить в одну сторону?

**Comment by ferr-um** [comment]
> А у тебя что получается зум вообще по кругу крутиться больше-меньше даже если колесо мышки крутить в одну сторону?

точно так, независимо в какую сторону крутишь два варианта шага, максимальный и минимальный, все перепробовал .. может параметры use_scope_zoom и use_scope_grenade_zoom в конфиге прицела должны быть, а не в конфиге самого оружия? Прицел-то съемный вроде как, хотя на других моделях ничего не прописано кроме линзы, так-же работает в двух режимах максимальный и минимальный и прицелы не съемные.

**Comment by joye-ramone** [comment]
use_scope_zoom и use_scope_grenade_zoom - всегда в конфиге оружия. и они тут не причем скорее всего
а точно у вас в скриптах ничего нету по этому поводу?

**Comment by ferr-um** [comment]
если остатки старого движка, вроде бы на два файла больше в старом было, накатом делал, могли эти файлы повлиять как-то?

**Comment by joye-ramone** [comment]
в [features] 
ogse_wpn_zoom_system = true ?

**Comment by ferr-um** [comment]
> в [features]
> ogse_wpn_zoom_system = true ?

Нет конечно, так как в описании по правкам оружия об этом ни слова не упомянуто, а я после обновления движка и не залез глянуть что там нового появилось:) Все заработало спасибо, допишите в описание правок об этой необходимой активации в external.ltx .. иначе многие на эти грабли еще встанут и будут искать причину:).

**Comment by joye-ramone** [comment]
Допишем. 
Но ты там настройки просмотри - там есть много чего с описанием.

**Comment by ferr-um** [comment]
> Допишем.
> Но ты там настройки просмотри - там есть много чего с описанием.

да, уже залез в этот файл, стараюсь его не трогать особо ибо движок обновляете и штатно все оставляю, чтоб не накрутить лишнего и не искать потом концы. Еще раз спасибо за оперативную поддержку и подсказки по навигации движка и опций. Мне теперь не на одну неделю разбора интересностей и новых фич с их внедрением хватит.

**Comment by ferr-um** [comment]
Здравствуйте. Снова с вопросом. В информации сказано:

Для активации №1 и №2 в секцию оружия нужно добавить параметр use_scope_zoom=true
Для активации №3 в секцию оружия нужно добавить параметр use_scope_grenade_zoom=true

эти функции я так понял по отдельности работать не будут? Например пункт первый и второй не нужен и нужен только вариант настройки худовых секций с оптикой и пг, так как новая логика хоть и позволяет приблизить худ и дарует новые возможности, но эффект отдачи сводит все на нет и прицел влетает как бы в экран. А если отодвинуть прицел чтобы он корректно выглядел при стрельбе и отдаче, слишком миниатюрное окно с линзой получается и нужного эффекта от прицела не достигается. Старый вариант работал как приближение (отдаление) худа рук с оружием (оптикой на ней и работой зума линзы при этом) на настроенные параметры и не создавал таких проблем, сейчас же встает вопрос о том, что некоторые модели прицелов (в частности ПСО, проблематично пристроить в игру из-за выступающего наглазника и утопленной линзы, а этот прицел как никак "канонский" в игре). Поэтому попробовал отключить параметр use_scope_zoom=true что сразу привело к отключению настроек прицеливания, хотя думал что они независимы друг от друга и должны работать по отдельности, как сказано в описании.

**Comment by joye-ramone** [comment]
Ты так сложно пишеш тексты, что мне нужно минут 10 читать что бы понять в чем проблема.
По порядку, use_scope_zoom включает использование параметров scope_grenade_normal_* и scope_* если на оружии надет прицел.
use_scope_grenade_zoom - включать использование параметра scope_grenade_ если есть прицел и оружие в режиме ПГ. можно использовать хоть оба хоть по отдельности.

Дальше, да, из за слишком длинных анимацию выстрела с отдачей, в режиме прицеливания оружие может влезать в экран. Так было и раньше, не зависимо от use_scope_zoom или use_scope_grenade_zoom

Тут 2 варианта:
1. Делать анимации другие, я еще добавлю возможность указывать отдельно анимации выстрела во время прицеливания. Но все равно нужно будет править модель
2. Играть с новыми параметрами scope_lense_hud_fov. Тогда можно лучше настроить приближение линзы к экрану без провяливания модели. Но это все равно требует настройки и подбора параметров. Движок тут особо не поможет больше.

В след раз заводи отделенные issue под каждую проблему (если это проблема движка)
А то тут уже такой чат получился. Не хорошо.

**Comment by ferr-um** [comment]
Я имел в виду раньше логика scope_lense_hud_fov работала по другому и проблем с проваливаем прицела при должной настройке не было, так как работа зума линзы и зума худа рук с оружием действовали параллельно, при увеличении зума увеличивался и зум линзы и зум худа рук, так-же параллельно и уменьшался при прокручивании колесиком и этот вариант меня устраивал, не хватало только опции настройки прицеливания, сейчас же остался зум линзы со всеми вытекающими, вот как пример старой работы логики scope_lense_hud_fov где даже при максимальном увеличении (диаметр прицела, то, что надо) при стрельбе и отдаче не возникает проблем с заскоком прицела в монитор - https://youtu.be/Ne8lEI7dBnY .. да может быть это не совсем реалистично, но главное это функционально и удобно в игре, так как я не претендую на создание снайперского симулятора:). Попробую еще покрутить настройки, возможно удастся что-то выжать в плане динамического зума худа рук с оружием как было раньше, но не факт ...

**Comment by joye-ramone** [comment]
Ты что то путаешь. Раньше параметра scope_lense_hud_fov не было вообще.
А при динамическом зуме увеличивался не худ рук, а мировой фов. Как при обычный текстурных прицелах .
А уже зум линзы увеличивался тоже потому что считался от мирового фов.
Теперь мировой фов не меняется, а меняется зум в самой линзе.
+ появился параметр scope_lense_hud_fov .

Я делал как, параметрами scope_zoom_* ставил оружие довольно далеко от экрана и делал scope_lense_hud_fov  = 0.30 - тогда во время прицеливания оружие будет казать большим в руках ГГ

**Comment by ferr-um** [comment]
Ок спасибо, покрутим, посмотрим, думаю параметров слишком много становится для настройки и просто надо разобраться как наилучше выстроить параметры прицеливая и найти оптимальный вариант, так как я худовой секцией прицеливания с оптикой выставлял максимальное приближение и параметры scope_lense_hud_fov как таковые не затрагивал, так что думаю вы правы, стоит попробовать различные варианты.

**Comment by joye-ramone** [comment]
Да должно получиться. с scope_lense_hud_fov  будет тоже самое что было раньше, только будет приближаться сам худ, а мир будет за пределами прицела такой же.

**Comment by ferr-um** [comment]
я подобрал себе логичный и понятный вариант настройки (тем более сравнив худы оптики в других играх, в частности прицел ПСО, получается что мы еще в выигрыше ибо в Таркове например и того меньше диаметр прицела). Единственное это выставить параметры, когда идет отдача максимальная чтобы прицел не влетал в монитор. Смотрится конечно хардкорно при стрельбе, но очень эффектно). Пример работы - https://vk.com/video-48325165_456240022

**Comment by joye-ramone** [comment]
Так как делал? с scope_lense_hud_fov

**Comment by ferr-um** [comment]
Как вы и написали сначала выставил (настроил) худовые секции оружия чтобы прицел не влетал в экран при стрельбе, указал scope_lense_fov_factor и этого уже достаточно, более тонкие настройки scope_lense_hud_fov, scope_zoom_hud_fov, scope_zoom_factor даже еще не делал. Основные параметры это худовые секции настройки самого оружия без прицела - zoom_offset и с прицелом - scope_zoom_offset и параметр увеличения линзы scope_lense_fov_factor, все остальное думаю это уже на вкус и на цвет, при этом даже третий настраиваемый параметр отдаления и приближения худа рук с оружием в zoom_offset и scope_zoom_offset так-же по нулям взят.

**Comment by ferr-um** [comment]
В общем с этой новой линзой без аномалий не обошлось .. непонятное просвечивание или раздвоение и причину так не смогли установить .. на всех коллиматорах куда пытались внедрить линзу траблы идут, на прежней версии линзы таких проблем не замечали, может есть какие-то предположения на эту тему что в скринах и видео. Пробовали и одну линзу и дополнительно прикрывали, результат неутешительный и не могли разгадать пока что ...

Скрины
http://images.vfl.ru/ii/1553530542/97afdb61/25915527.jpg
http://images.vfl.ru/ii/1553530542/dc799418/25915528.jpg
http://images.vfl.ru/ii/1553530543/b4ed94a2/25915529.jpg
http://images.vfl.ru/ii/1553530543/3cd07809/25915530.jpg
http://images.vfl.ru/ii/1553530543/78775b7b/25915531.jpg

Видео
https://youtu.be/Vm_LlIiD5A0
https://youtu.be/L5t5TAlobgQ

**Comment by joye-ramone** [comment]
Что значит новой линзы? Линза та же. И работает на всех моделях что у меня есть точно так же.

**Comment by ferr-um** [comment]
а у меня к сожалению перестали работать как раньше, вот как было раньше - https://youtu.be/scHf_fhyhfs причем ничего не меняя в моделях, пытались новые правки добавить в конфиг и результат в скринах выше ...

**Comment by joye-ramone** [comment]
Сорри, но в рендере ничего не менялось
Модели должны быть непрозрачные изначально. В этом и есть ошибка.

**Comment by ferr-um** [comment]
ок, пробуем уже по другому, будет результат напишу подробности.

**Comment by ferr-um** [comment]
А вы какую версию используете? Я так и крутил на 1.0.615, вчера попробовал на 1.0.625 но там уже пропал динамический зум линзы и вижу что изменения совсем другие и многое работает в плане прицелов по другому ... думаю пока что отложить сию затею, так как слишком частые обновления движка ни к чему стабильному не приводят, все меняется настолько быстро, что работать с моделями не представляется возможным, а переделывать после каждой новой версии движка модели в плане прицелов, линз и конфигов, удовольствие то еще ... почему раньше вариант линз в коллиматорных прицелах работал стабильно без визуальных косяков и почему перестал на той же линзе, которая не изменилась для меня осталось загадкой, подразумеваю изменение шейдера которое привело к таким последствиям.

**Comment by KRodinn** [comment]
@ferr-um 
>  Я так и крутил на 1.0.615, вчера попробовал на 1.0.625 но там уже пропал динамический зум линзы и вижу что изменения совсем другие и многое работает в плане прицелов по другому ... 

Используй ту, что я тебе скинул. Я ж скинул не просто так. 1.0.625 - это движок из стабильной ветки, там еще нет дин. зума в 3д и тп.
Я тебе скинул движок из тестовой ветки, вот его и используй. Изменения из тестовой ветки попадут в стабильную примерно через месяц. Я скинул тебе раньще, чтобы ты не ждал. И ещё, когда будет следующий стабильный релиз, там в чейнжлоге обязательно будет написано про 3д зум и тп. Если сейчас не написано - логично что его там нет.

> почему раньше вариант линз в коллиматорных прицелах работал стабильно без визуальных косяков

Не знаю, в этом плане в движке ничего не менялось. Попробуй шейдерный кэш почистить что - ли... Даже не знаю, что сказать.

**Comment by KRodinn** [comment]
@ferr-um и ещё, как уже правильно сказал @joye-ramone - поверхность, на которую идет рендер изображения в 3д прицеле - **должна быть полностью не прозрачной** Об этом к стати и в Wiki написано. Мы в свое время знатно поплясали на этих граблях, когда везде сделали прохрачные прицелы и вдруг оказалось что они глючат при грозе и ещё многих ситуациях, изображение как бы просвечивается сквозь прицел. Вот в этом и ваша ошибка скорее всего. 3д прицел должен быть полностью непрозрачным, иначе будут графические баги при некоторых погодных условиях и не только.

**Comment by ferr-um** [comment]
Спасибо за информацию:) вот мы тоже знатно уже поплясали... надеемся найти какие-то интересные варианты работы линз с моделями оружия ...
