### ISSUE TITLE
hud_adjust_mode

### ISSUE THREAD

**Issue by romanpopulik** [OGSR/OGSR-Engine#116]
Looks like hud_adjust_mode doesn't work for fire_point and shell_point. Is this feature uncomplete or am I missing something ?

**Comment by joye-ramone** [comment]
It should work for all modes. I will check soon.
Also, we should probably add a few more modes to simplify weapon hud configuration

**Comment by seaz5150** [comment]
Any update on this?

**Comment by joye-ramone** [comment]
No

**Comment by seaz5150** [comment]
Would it be difficult to fix the fire point mode? I need to do alot of those and it would be a godsent.

**Comment by KRodinn** [comment]
it's not difficult, it's lazy
I haven't made major edits in the engine for a long time, I have not been in the mood for this for a long time.

**Comment by seaz5150** [comment]
Well I understand, you did alot of great work on this, you deserve a rest! Hope you will check the sound layering at some point, would be cool to have. Tried to add it myself but there is no way :D

**Comment by KRodinn** [comment]
This is not rest, this is depression...

**Comment by seaz5150** [comment]
Hey, hang in there man! For me personally modding helps me with this. Takes your mind off of other stuff.

**Comment by joye-ramone** [comment]
@seaz5150 As I can see there 5 modes in engine for this parameter:
1. zoom_offset + zoom_rotate_x + zoom_rotate_y
2. fire_point
3. missile_throw_offset
4. shell_point
5. fire_point2 ???

mode 1 definitly working, I was using it a lot.
So you need fire_point (mode 2) and shell_point (mode 3).
I see that code and logic in place, can you please describe what is wrong?
I will take a look.

**Comment by seaz5150** [comment]
As far as I know fire_point2 is for the grenade launcher muzzle flashes. For me personally I just need to edit alot of normal muzzle flashes, so it would be enough if you fixed just the second (fire_point) mode. Yes, the first one works fine, the rest of them do not move the position of the particles at all.

**Comment by joye-ramone** [comment]
@seaz5150 please check this build https://github.com/OGSR/OGSR-Engine/actions/runs/278652640

**Comment by seaz5150** [comment]
It works! Thanks alot, now I don't have to experiment with the position and keep restarting the game)

**Comment by joye-ramone** [comment]
https://github.com/OGSR/OGSR-Engine/commit/4733b2637e54b75fca09525dd7740a5aac9898e9
