### ISSUE TITLE
Compilation problem.

### ISSUE THREAD

**Issue by MonoLityczny** [OGSR/OGSR-Engine#118]
Hi. 

I've reinstaled VS2017, and SDK 8.1 because before i cannot compile even a single file.

Now i get that errors. I don't know what im doing wrong.

Release x64.

![compilation blyaaaaaa](https://user-images.githubusercontent.com/22204253/53077425-4708cd80-34f2-11e9-8d67-0b6ba2279cc1.PNG)

**Comment by joye-ramone** [comment]
Try to install following SDK versions: https://vgy.me/oDeXZa.png
I can compile project without any issues on both my working PCs

**Comment by MonoLityczny** [comment]
I've fixed it with changing Windows SDK version in all libraries to 10.
