### ISSUE TITLE
Меню

### ISSUE THREAD

**Issue by bigmack2304** [OGSR/OGSR-Engine#124]
Есть небольшой вопрос по поводу меню. Как известно, в оригинале в меню играет музыка но когда она заканчивается дальше ничего не происходит, просто тишина. Планируется ли в дальнейшем это как-то поправить? К примеру, если в конфигах прописана одна мелодия то сделать так чтобы в меню она играла по кругу. Либо если в конфигах прописано более одной мелодии, то чтобы после окончания мелодии рандомно либо в порядке очереди воспроизводилась следующая мелодия.

**Comment by joye-ramone** [comment]
Насколько это важно? Могу поправить

**Comment by bigmack2304** [comment]
Было-бы не плохо, хоть и мелочь а приятно. Не помню чтобы такая фишка была в других модах, по крайней мере на тч.

**Comment by joye-ramone** [comment]
Ок будет

**Comment by joye-ramone** [comment]
Добавил в dev ветку https://github.com/OGSR/OGSR-Engine/commit/d01c2e1b05f6f876f7d6fb46f3df94dc08735963
