### ISSUE TITLE
[Feature] Add .anm play for weapons animation

### ISSUE THREAD

**Issue by LVutner** [OGSR/OGSR-Engine#126]

**Comment by NikitaNikson** [comment]
есть уже код для .anm эффектов по время перезарядки
https://bitbucket.org/sv3nk/la-code/commits/567c41d9a221cc36f8b317c9ff1ab06831a57462

Демонстрация: https://youtu.be/tzVQJ2gKWak

**Comment by KRodinn** [comment]
Подобное изначально и в ЗП есть, мы как бы в курсе.

**Comment by KRodinn** [comment]
Я вот сегодня перенес ЗП-систему, она работает не так как в ЛА.
В ЗП имя эффектора это походу `anims\camera_effects\weapon\имя играемой анимации, которое в модели прописано. Именно то что в модели, а не просто какой-нибудь anim_reload`
А в ЛА `anims\camera_effects\weapon\секция ствола+_префикс_анимации, жестко прописанный в движке ( к стати, не понятно зачем, ведь проще брать имя анимации в качестве префикса, типа anim_reload, в этом случае гораздо меньше правок кода надо. )`
Фигня получается. Для первого варианта надо переделать тонны моделей, переписать там имена анимаций. Для второго копипастить тонны эффекторов для каждой секции. А в случае если секций тысячи, как в огср моде, из-за многоприцельностей и тп, это тонна лишних файлов будет.
Наверное придётся делать третий вариант, по-своему, читать из конфига типа `anim_reload_effector = что-то`.
И уже вот это `что-то` искать в папке `anims\camera_effects\weapon\`.
