### ISSUE TITLE
Вылетает

### ISSUE THREAD

**Issue by prived1960** [OGSR/OGSR-Engine#145]
Играл с 2.10R с год назад. Решил попробовать накатить Х64.
Проверил старую 32 бит установку- работает (сбекапил). Качал исходную игрушку по ссылкам с АМК.
https://www.amk-team.ru/forum/topic/13108-ogse-0693-opisanie-i-ssylki/
Скачал OGSR-Resources-ogsr_engine.zip, распаковал поверх.
Потом распаковал поверх OGSR_Engine_SHOC_EDITION_x64_1.0.688.7z.
Конфигуратор запускается, но при попытке запустить Х64 движок- вылет с ошибкой (на скриншоте). ЧЯДНТ?
![OGSR](https://user-images.githubusercontent.com/27216724/59143254-99062e00-89d1-11e9-9463-cb2dc677c195.png)

**Comment by prived1960** [comment]
Попробовал запустить 32-бит движок. Имею вылет с той же ошибкой.
Expression    : fatal error
Function      : CInifile::r_section
File          : E:\stalker\sources\trunk\xrCore\Xr_ini.cpp
Line          : 342
Description   : <no expression>
Arguments     : Can't open section 'bio'

**Comment by KRodinn** [comment]
> Потом распаковал поверх OGSR_Engine_SHOC_EDITION_x64_1.0.688.7z.

Скорее всего в этом и проблема. В релизах лежат файлы именно для запуска на оригинальном ТЧ. При установке на огсе, надо брать из этого архива только сам движок, т.е. папку bin_*

> Попробовал запустить 32-бит движок.

В последнем релизе 32-битного движка нет вообще. Мы отказались от его поддержки, потому что его некому тестировать, и вообще он никому не нужен.

**Comment by prived1960** [comment]
Движок 32 от 2.10, который не был апдейтом оригинала а ставился из своего дистриба. Я его дважды прошел до конца.
Можете тогда указать правильную последовательность установки (или ссылку, если я туплю)

**Comment by KRodinn** [comment]
Ну, собственно, как стоит у меня:
1. ОГСЕ 2.10R
2. https://github.com/OGSR/OGSR-Resources/archive/ogsr_engine.zip
3. Папка bin_* из https://github.com/OGSR/OGSR-Engine/releases/download/1.0.688/OGSR_Engine_SHOC_EDITION_x64_1.0.688.7z

**Comment by KRodinn** [comment]
Вообще, наверное когда-то в будущем надо нормальный альфа-бета релиз под огсе сделать, да и всё. Но у меня на это не хватает ни времени, ни желания в последнее время...

**Comment by prived1960** [comment]
Все заработало. Я еще копировал поверх файлы геймдаты из архива п.3. Тогда непонятно, зачем они нужны...

**Comment by KRodinn** [comment]
> Тогда непонятно, зачем они нужны...

Для запуска движка на оригинальном ТЧ. У нас же в первую очередь движок для ТЧ, а не для огсе.
