### ISSUE TITLE
"Улучшенная многоядерность" имеется ввиду TBB?

### ISSUE THREAD

**Issue by aka-sektor** [OGSR/OGSR-Engine#146]
Такие проекты как **OpenXRay** и **X-Ray Oxygen**, достигли улучшения многоядерности через **TBB** (_Intel Threading Building Blocks_) для динамического распределения нагрузки на процессор (задач) между ядрами, вне зависимости от платформы (архитектуры).

**OGSR** также?

**Comment by KRodinn** [comment]
ИМХО, для X-Ray TBB избыточен.

**Comment by aka-sektor** [comment]
Странно, уже написано "Улучшена многопоточность" https://github.com/OGSR/OGSR-Engine/wiki/Список-изменений

**Comment by ForserX** [comment]
@KRodinn, почему же? Там ещё аллокаторы шустрые есть. (alloc/malloc/free). Таск система, параллелинг циклов. 
(Говорю о том, что юзаем)

**Comment by ForserX** [comment]
> Странно, уже написано "Улучшена многопоточность"
TBB - просто API. Это можно сделать миллионом способов

**Comment by aka-sektor** [comment]
Так понимаю, TBB нету в OGSR. Многоядерность на уровне оригинала

**Comment by Xottab-DUTY** [comment]
Никакого улучшения многоядерности через тбб мы не достигали. Прежде чем использовать понятия, надо сначала с ними ознакомиться.
Улучшение многопоточности – да. Многоядерности – нет.

**Comment by KRodinn** [comment]
@ForserX 
>@KRodinn, почему же?

Просто помню, как в OXR намучались с этим TBB, прежде чем оно стало норм работать. Да ну, нафиг он нужен.

**Comment by KRodinn** [comment]
> Многоядерность на уровне оригинала

Нет

**Comment by aka-sektor** [comment]
> Никакого улучшения многоядерности через тбб мы не достигали. Прежде чем использовать понятия, надо сначала с ними ознакомиться.
«задачи», которые динамически распределяются между ядрами процессора

**Comment by aka-sektor** [comment]
> Нет

И за счёт чего тогда улучшена многоядерность?

**Comment by Xottab-DUTY** [comment]
Многоядерность зависит только от системы и от железа, но не от программистов движка. Кроме, разве что, одной вещи. Оригинальный движок был жёстко привязан к первому ядру и это было сделано из-за того, что в Windows XP плохой планировщик, который плохо распределял нагрузку по ядрам. OGSR, OpenXRay, Oxygen, все мы отвязали движки от первого ядра, чтобы система сама решала, на каком ядре движок будет работать.

Я точно помню, что я это уже объяснял кому-то... Возможно, даже где-то в этом репозитории...

**Comment by Xottab-DUTY** [comment]
Ещё раз: многоядерность и многопоточность – это разные понятия.

**Comment by dsh2dsh** [comment]
> (Говорю о том, что юзаем)

О, насколько FPS увеличился после всего этого?

**Comment by aka-sektor** [comment]
> OGSR, OpenXRay, Oxygen, все мы отвязали движки от первого ядра

Т.е. TBB помогает улучшить многопоточность?

**Comment by KRodinn** [comment]
ПРИЧЁМ ТУТ TBB???

**Comment by KRodinn** [comment]
Здесь его нет и не будет.

**Comment by ForserX** [comment]
> Просто помню, как в OXR намучались с этим TBB

Они xalloc заменили на TBB. В этом и был косяк. 

> о, насколько FPS увеличился после всего этого?

Ты же сам видел наш TBB

**Comment by Xottab-DUTY** [comment]
> Т.е. TBB помогает улучшить многопоточность?

Да. TBB это просто готовый инструмент, помогающий программисту. (помощь заключается в том, что это готовый инструмент и не нужно делать свои велосипеды)
Но само распоточивание движка, это уже полностью лежит на программисте.

> Они xalloc заменили на TBB. В этом и был косяк.

То аллокатор тббшный, мы потом вернули оригинальный. Но работа с потоками через TBB ведётся. Удобно.

**Comment by aka-sektor** [comment]
> чтобы система сама решала, на каком ядре движок будет работать

TBB для этого?

**Comment by KRodinn** [comment]
В гугл с такими вопросами, плз, а не сюда. Тут не справочное бюро по TBB.

**Comment by aka-sektor** [comment]
За счет чего "Улучшенная многопоточность" в OGSR?

**Comment by aka-sektor** [comment]
> TBB это просто готовый инструмент

Выходит эту хрень вообще записывать в особенности не было смысла

**Comment by KRodinn** [comment]
> За счет чего "Улучшенная многопоточность" в OGSR?

В списке изменений там всё написано, если его изучить внимательно.
И вообще, с какой целью интересуешься?

**Comment by aka-sektor** [comment]
Интересуюсь для себя

**Comment by aka-sektor** [comment]
> В списке изменений там всё написано

"rs_mt_texload -- Включить многопоточную загрузку текстур. Может немного ускорить загрузку текстур при наличии SSD, в некоторых случаях."
Только это?

**Comment by KRodinn** [comment]
не только

**Comment by aka-sektor** [comment]
"C++11 based thread pool" всё ещё на месте?

**Comment by KRodinn** [comment]
ага

**Comment by aka-sektor** [comment]
А то дискорд OpenXRay внезапно удивился, нафиг это юзать

**Comment by Xottab-DUTY** [comment]
C++11 based thread pool нам не нужен, ибо это велосипед, а его задачи выполняет TBB.

> TBB для этого?

Ты меня поражаешь. Я ясно сказал: "чтобы система **САМА** решала..". А TBB не является системной библиотекой..

**Comment by aka-sektor** [comment]
Просто пропустил, про то что это инструмент

**Comment by KRodinn** [comment]
> А то дискорд OpenXRay внезапно удивился, нафиг это юзать

Им это и не надо юзать, у них TBB

**Comment by aka-sektor** [comment]
> у них TBB

Вроде ты говорил "в некоторых местах даёт более чем двухкратный прирост FPS". За счет чего? C++11 based thread pool это тоже инструмент?

**Comment by KRodinn** [comment]
> Вроде ты говорил

В актуальном Wiki этого нет.

> За счет чего?

Улучшения в системе многопоточной обработке партиклов.

**Comment by Xottab-DUTY** [comment]
Самое лучшее объяснение каким образом многопоточность увеличивает FPS:
Это происходит за счёт того, что делать двумя руками намного быстрее, чем одной рукой. Тоже самое и с потоками. Только руки обычно две, а потоков может быть больше и, соответственно, скорость работы больше.

**Comment by aka-sektor** [comment]
Говорили бы чётко и ясно, было бы меньше вопросов. А то:

> TBB - просто API



> TBB это просто готовый инструмент

**Comment by KRodinn** [comment]
ммм, а тебе-то какая разница?
И вообще, все ответы можно тут получить: https://lmgtfy.com/?q=Intel+TBB

**Comment by aka-sektor** [comment]
Просто путаницы много. Понятно что там программисткие будни они такие. Но неужели понятно для игрока описать особенности движка нельзя.

**Comment by KRodinn** [comment]
А игроку об этом знать не надо

**Comment by aka-sektor** [comment]
Так и программистом быть не надо, чтобы моды делать. Стало быть и модмейкеру знать не надо. А кому тогда движки эти модифицируете?

**Comment by KRodinn** [comment]
Себе, и разработчикам, которые хотят использовать движок.
Ты путаешь понятия "игрок" и "разработчик".

**Comment by aka-sektor** [comment]
Мне кажется, есть непонимание что могут модифицированные движки, и как их изменили, и из-за этого они не востребованы так, как могли бы.

**Comment by aka-sektor** [comment]
Все проекты, выкладывают же готовые бинарники, бери только, и используй. Но перед этим, нужно разобраться во всей этой структуре гитхаба, и что откуда качать. Недружелюбно все очень.

**Comment by joye-ramone** [comment]
гитхаб хостит сейчас почти 25 миллионов проектов. Это им то все неудобно?
А разобраться можно за пару дней. Было бы желание.

**Comment by KRodinn** [comment]
> Мне кажется, есть непонимание что могут модифицированные движки, и как их изменили, и из-за этого они не востребованы так, как могли бы.

Я что могу сделать? Я и так гигантский Wiki написал по движку, в отличие от многих. И тем не менее вот так приходят люди и начинают тут предъявлять, что им мало информации видите ли.
Может быть дело в людях, а не в недостатке информации?

**Comment by KRodinn** [comment]
> Все проекты, выкладывают же готовые бинарники, бери только, и используй. Но перед этим, нужно разобраться во всей этой структуре гитхаба, и что откуда качать. Недружелюбно все очень.

Все проекты так делают, потому что ничего лучше на данный момент никто не придумал.

**Comment by aka-sektor** [comment]
> неудобно?

На самом деле, игроки ни слухом не духом, о ваших гибхабах. Начинающие моддеры, или опытные, которые до того в двиг и не лезли никогда, могут тоже не знать.

> Я и так гигантский Wiki

К вики OGSR вопросов почти нет. Согласен, описано отлично. Возможно даже фиксируется все, не уверен. Жаль, про другие проекты такого не скажешь.

**Comment by joye-ramone** [comment]
> На самом деле, игроки ни слухом не духом, о ваших гибхабах.
файлы по почте пересылают и хранят? а потом читаем одну из 100500 история как полетел hdd и все файлы проекта потеряны. Ну ну. "ваши" гитхабы конечно сложные.
Этот спор не имеет смысла. Делать проще чем сейчас некуда. Будет желание - можно разобрать за считанные дни. А так это все ради флейма.

**Comment by aka-sektor** [comment]
> в недостатке информации?

Скорее не в не отсортированности информации. Нужно разделять, игроков/моддеров от программистов.

**Comment by KRodinn** [comment]
> На самом деле, игроки ни слухом не духом, о ваших гибхабах. Начинающие моддеры, или опытные, которые до того в двиг и не лезли никогда, могут тоже не знать.

Ты не поверишь, но я не родился программистом. Я сам когда-то с блокнота начинал. Было бы желание, можно всему научиться, если захотеть.

> Там чтобы что-то узнать, приходится пробираться через поток неуместного сарказма и смехуёвочек.

Ты слишком серьезно ко всему относишься, дядь.

> Не для людей сделано.

Ну да, тут одни роботы сидят.

**Comment by joye-ramone** [comment]
> Есть что-то вроде степеней желания. 

Еще раз напишу - разобраться можно за 3 дня. Если лень потратить это время - ну так не нужно оно значит. Если не вышло - тож самое.

**Comment by aka-sektor** [comment]
> я не родился программистом

Понятно что ими становятся, но не каждый.

> слишком серьезно

Может и да. Просто нахрена создавать о себе впечатление человека, который не разбирается в том что делает. То лень... да нет. Шутить не лень.

> такой фильтр

Галимый фильтр. Зачем отсекать потенциальных юзеров движка, раз все доступно? Вот разрабы LA, уже который год, не отдают ничего.

**Comment by joye-ramone** [comment]
> Зачем отсекать потенциальных юзеров движка

Так тут все от юзера зависит. Захочет - и свой движок напишет же.

**Comment by KRodinn** [comment]
> ими становятся, но не каждый.

Вот поэтому нужно стимулировать людей становиться программистами. Чем больше будет программистов - тем быстрее будет развиваться Цивилизация, тем скорее придёт новая эра Искуственного Интеллекта, цифровой экономики, виртуальной реальности и тд.
Именнно поэтому мы, OGSR, стимулируем обычных людей, становиться программистами.
А что сделал ты для приближения новой эпохи?

**Comment by KRodinn** [comment]
> Вот разрабы LA, уже который год, не отдают ничего.

Вот пойди и предъяви им за это. Пускай отдают. Тебе-то точно отдадут, я уверен.

**Comment by aka-sektor** [comment]
Этот тред войдет в 10ку вышедших из под контроля xD

Собсна ладно на этом, я выяснил что нужно. Пусть и на второй день.



> стимулировать

Говорят нужен математический склад ума. Иначе это просто мука будет.



> тем быстрее будет развиваться Цивилизация

Да-да... и быстрее наступят события вселенной Терминатора xD



> А что сделал ты

Ничего. Быть посредственностью нормально.

> предъяви

При каждом удобном случае, крайний раз здесь: https://www.youtube.com/watch?v=-uA-HMx3GAQ
Но чувствую... пока полностью X-Ray не выдоят... не видать нам сырцов LA, как своих ушей.

**Comment by joye-ramone** [comment]
> пока полностью X-Ray не выдоят.

Было бы там что доить. Можно подумать они на этом заработали или выиграли что то.
Это так из личных побуждений не выкладывают.

**Comment by aka-sektor** [comment]
> из личных побуждений не выкладывают

Ой... ну это очевидно. Иначе зачем исходники уровней даже держать.
Компиляторы поменяли, декомпили не берут. Уровни LA не вытащить... или вытащить? Вроде нет...
Знали что ломать...

**Comment by ferr-um** [comment]
Уровни LA не вытащить... или вытащить? 

 Вопрос насколько тебе нужны эти уровни и сколько ты готов времени на это потратить - https://youtu.be/ZzEu6Qbl52s

**Comment by AllCore** [comment]
Ну исходники кордона и ещё нескольких локаций из ЛА есть в их СДК. Локи из DC разбираются без level.spawn, а 1.3003 разбираются и со спавном. Вот только это мало поможет - конвертер разбирает Топи, к примеру, на 16к частей и SDK 0.4 пасует с их открытием. На не совсем слабом компе открываются за час. Да и если сильно нужны локи ЛА то можно подключить без убогого СДК и редактировать через алл.спавн и граф. И вообще это тред OGSR, а не LA.
