### ISSUE TITLE
Lua lfs

### ISSUE THREAD

**Issue by naxac** [OGSR/OGSR-Engine#148]
Не загружается библиотека lfs в Луа. Загружаю через require, как в _G_add. lfs.dll лежит в папке движка (bin_x64). В логе:
%1 не является приложением Win32. 
На компе - Windows х64. Может, необходимо что-то ещё установить, кроме Visual C++ Redistributable, DirectX и OpenAl?

**Comment by joye-ramone** [comment]
а lfs.dll 64 сборки?

**Comment by dsh2dsh** [comment]
C lfs.dll, помню, какая-то проблема была. Но это не важно. @naxac используй движковый stdfs. Пример можно посмотреть тут
https://github.com/dsh2dsh/op2ogse/blob/551a49564a04e825ef4fb182554f07a15e163fe6/gamedata/scripts/dsh/dsh.script#L2545

Подробности тут
https://github.com/OGSR/OGSR-Engine/blob/a2412f0f8cee573ec4250a9f17d0df5d482d226c/ogsr_engine/xrGame/fs_registrator_script.cpp#L253

**Comment by naxac** [comment]
@joye-ramone, да, библиотека из архива. Понятно тогда, спасибо.

@dsh2dsh, спасибо.

**Comment by joye-ramone** [comment]
@naxac а что обычно из той либы используют? если чего то не хватает - его проще в движке добавить

**Comment by naxac** [comment]
@joye-ramone, мне нужно было время последнего изменения файла - для вывода версии мода. В stdfs есть необходимый функционал.
