### ISSUE TITLE
Компили есть? А если найду...

### ISSUE THREAD

**Issue by aka-sektor** [OGSR/OGSR-Engine#149]
Скромный вопрос. Двиг 64 бит.

А компиляторы что?

**Comment by KRodinn** [comment]
А зачем они нам? Уже и так в проектах кучу компилей наплодили, на любой вкус и цвет.
Тем более у нас их тестить некому, да и они будут банально никому не нужны.

**Comment by aka-sektor** [comment]
Проблема в том, что K.D. сделал багованные x64 компили для SDK 0.4 в своё время. А более никто их толком не фиксил.

**Comment by KRodinn** [comment]
Ну, у КД компиляторы вообще кривота неимоверная. Мне говорили, что они кривые лайтмапы создают. А зачем их фиксить? Не юзать их да и всё.
Насколько я знаю, рекомендуют компилить ЗП-шными, и как-то там лайтмапы переносить под ТЧ.

**Comment by aka-sektor** [comment]
Стесняюсь спросить, а AI тоже компилить ЗПшным? Так не получится.

По моей информации, x64 компили K.D. "не совсем кривота". Недавно компилили ими, результат был почти без глюков. Говорят, возможно от мощности ПК зависит.

Ну а ЗПшные компили для ТЧ юзать - категорически отказываются.

**Comment by KRodinn** [comment]
Я вообще не шарю в компиляторах. Что мне говорили о них, то и написал.

**Comment by D1m0n93** [comment]
Женя, зачем тебе х64 компилятор под аи-сетку, да еще и под ТЧ? Хватит там и стандартного, это только если для гигантских локаций нужно, которых под ТЧ нет и вряд-ли будет. В основном такие глобальные проекты делаются уже под ЗП, а движок OGSR лично я больше рассматриваю как возможность дать новую жизнь старым проектам на ТЧ, таким как ОГСЕ, НС...

**Comment by D1m0n93** [comment]
> 
> 
> Стесняюсь спросить, а AI тоже компилить ЗПшным? Так не получится.
> 
> По моей информации, x64 компили K.D. "не совсем кривота". Недавно компилили ими, результат был почти без глюков. Говорят, возможно от мощности ПК зависит.
> 
> Ну а ЗПшные компили для ТЧ юзать - категорически отказываются.

Что значит зависит от мощности ПК? У меня 12 потоков, а тени всё равно глючные даже на маленькой подземке агропрома, которая скомпилилась за 10 минут. И кстати неправильные лайтмапы как раз больше всего видны на улучшенных рендерах, а на обычном ТЧ можно и не заметить. К тому же, после переноса на рендеры ЗП лучшего результата в графике можно добиться, как раз-таки пересобрав все карты компиляторами ЗП.

**Comment by aka-sektor** [comment]
> 64 компилятор под аи-сетку, да еще и под ТЧ? Хватит там и стандартного

Уточнил тут, проблема наверное не в размере локи, а в том, что оригинальные xrAI и xrDO - несовместимы с уровнем скомпиленным в xrLC x64.

> глобальные проекты делаются уже под ЗП

Ну... для любителям того самого, это не аргумент.

**Comment by KRodinn** [comment]
>>не шарю в компиляторах

>А что они сложнее движка?

Не сложнее, мне они банально не нужны.
Нужны бы были - разбирался бы.
Я из утилит правил только xrCompress, вот за него могу пояснить, если что.
