### ISSUE TITLE
Плавное скрытие оружия через функцию hide_weapon

### ISSUE THREAD

**Issue by RayTwitty** [OGSR/OGSR-Engine#150]
Косяк оригинала ТЧ. Если скрыть оружие при помощи скриптовой функции `actor:hide_weapon()`, то оружие исчезнет без отыгрывания анимации _holster (hide)_.
Более подробно разбор проблемы здесь: https://www.gameru.net/forum/index.php?s=&showtopic=23443&view=findpost&p=1660348
Я там предложил промежуточное решение, но хотелось бы докопаться до истины.

**Comment by SurDno** [comment]
Забавная тема. В ЧН скрывается плавно, и из-за этого есть эксплоит, позволяющий пронести пушку на базу группировки. 

Нужно во время анимации успеть сменить оружие на другое того же типа (через инвентарь). ГГ его достанет и сразу начнёт убирать. Если всё время менять оружие между двумя типами и пройти так зону его убора, можно будет хоть Лебедева застрелить к чертям.

В ЗП это вроде поправили, хотя анимация осталась. Глянуть бы.

**Comment by KRodinn** [comment]
Нетпакеты и вообще вся клиент-серверная система - это наверное самое ужасное, что есть в движке. Это один сплошной баг. Неудивительно что там всё глючит. Все эти очереди клиент-серверных сообщений, их пересылки, синхронизации - это ж пздц, всё настолько запутано, что даже по началу тяжело разобраться, как эта хрень вся работает. Эталон быдлокода.

> Я там предложил промежуточное решение, но хотелось бы докопаться до истины.

Да нормально, и так сойдёт. Мне вот например лень докапываться. Потом сюда твой фикс закину тоже.

**Comment by RayTwitty** [comment]
Вроде получилось решить проблему более "элегантно", если можно так выразиться применительно к X-Ray: https://www.gameru.net/forum/index.php?s=&showtopic=23443&view=findpost&p=1660458
Но конечно, лучше чтобы еще кто-нибудь потестил.

P.S. Заодно проверил косяк на предмет смены оружия во время скрытия - вроде не выявил (или нужно совсем как-то извратиться, чтобы его воспроизвести).
