### ISSUE TITLE
OGSE rev. 2.0 проблема с тенями

### ISSUE THREAD

**Issue by Priler** [OGSR/OGSR-Engine#152]
В текущем бранче такой проблемы нет, в старом rev 2.0 есть.
Может подскажете как поправить?

До прицеливания: https://i.imgur.com/0CJDMYQ.jpg
После: https://i.imgur.com/LyBcmS5.jpg

Проблема конкретна из-за параметра "Тень от солнца".
Может есть вариант перенести его рендер из новой версии?
Обновиться не могу так как движок конкретно rev 2.0 завязан на моде.

**Comment by KRodinn** [comment]
Версия движка какая? Что такое `rev 2.0` - я понятия не имею. У нас таких версий нет.

**Comment by Priler** [comment]
> Версия движка какая? Что такое `rev 2.0` - я понятия не имею. У нас таких версий нет.

Мод отсюда https://www.amk-team.ru/forum/topic/13490-adaptaciya-graficheskoy-chasti-ogse/page/24/?tab=comments
Как узнать версию текущего движка? В каком файле.

**Comment by KRodinn** [comment]
Так ты про старый OGSE - движок что ли?
Он устарел во всех смыслах, и в нём уже невозможно что-либо поправить, да и некому.
На OGSR переходить надо, за нами будущее.

_И вообще, мы к OGSE никакого отношения не имеем. У нас совершенно другая команда, движок, стратегия развития и тд. Просто некоторые почему-то думают, что мы к старой команде OGSE какое-то отношение имеем. Это не так, та команда распалась давным давно, её по сути больше нет._
