### ISSUE TITLE
Несколько проблем с анимациями мутантов

### ISSUE THREAD

**Issue by JIuBeP** [OGSR/OGSR-Engine#154]
Здравствуйте, есть несколько странных моментов в анимациях или их состояниях у мутантов, словно порой они зависают в одном состоянии и остаются на месте.
https://radikal.ru/video/EGXo0G5rXw8
https://radikal.ru/video/2zFONzOvzUc

и по мелочи в контейнерах(трупах) по пкм st_move и st_move_all (переместить) не переведено.
теперь вроде есть иконка болта, но что то с ней не так
интерфейс в меню сохранений на соотношении 5:4 немного съезжает за рамки

Будет ли поддержка инверсной кинематики (ЧН\ЗП) с любыми моделями (в том числе старыми из ТЧ)? То есть все НПС (кроме ГГ) на кривых поверхностях ставят ноги правильно

**Comment by joye-ramone** [comment]
Настройки интерфейса (иконок, размеров) это не движок как бы.
Пример ресурсов - это просто наработки для адаптации.

**Comment by JIuBeP** [comment]
Понятно, просто подумал вдруг уже заранее включены готовые, на всякий случай написал.

**Comment by KRodinn** [comment]
> Будет ли поддержка инверсной кинематики (ЧН\ЗП) с любыми моделями (в том числе старыми из ТЧ)?

Будет, когда мне будет не лень ею заняться.

**Comment by exostalker2** [comment]
I also encountered the mutants (dogs) walking in place, quite distracting...

**Comment by KRodinn** [comment]
Fixed in https://github.com/OGSR/OGSR-Engine/commit/9a3335456120f5a858a348dc272d98ae09799849

**Comment by KRodinn** [comment]
> Будет ли поддержка инверсной кинематики (ЧН\ЗП) с любыми моделями (в том числе старыми из ТЧ)? То есть все НПС (кроме ГГ) на кривых поверхностях ставят ноги правильно

Теперь есть ( https://github.com/OGSR/OGSR-Engine/commit/3b4df654696ef3082be454dc648e8753e62dfb8c )

**Comment by Dushess** [comment]
добавлю момент, который потребует переделку именно самих анимок. Если кто займется, когда-нибудь...
псевдопсины в режиме хотьбы используют ту же анимацию бега = довольно уродливо смотрится.
