### ISSUE TITLE
Про 3д прицелы, ppe и жажду

### ISSUE THREAD

**Issue by bigmack2304** [OGSR/OGSR-Engine#155]
Обратил внимание на одну особенность с 3Д прицелами, если включить какой либо ppe эффект и в этоже время прицелится в прицел то изображение в прицеле становится гораздо светлее чем за его пределами (такое ощущение что ppe в прицеле рендерится второй раз). 
Есть фотки -  https://yadi.sk/i/duVdiTXJ9l07Qg , https://yadi.sk/i/ioVH4xf_hD_nGw , https://yadi.sk/i/urYQzrSQJKKZBA
Еще хотел спросить про жажду, ее ввели еще в 1.0.688 но со следующего обновления она куда-то пропала и настройка actor_thirst в конфиге external пропала. При попытке самостоятельно вписать этот параметр (actor_thirst = true) в конфиг получал вылет. Вернется ли эта вишка в следующих обновлениях ?

**Comment by joye-ramone** [comment]
Для включения жажды нужно адаптировать конфиги.
Пример https://gist.github.com/joye-ramone/4d187529577085010eb2f4c63b4cb8ff

**Comment by bigmack2304** [comment]
Да, теперь жажда заработала. Оказалось что я немножко тупанул и забыл добавить функцию в _g.script
