### ISSUE TITLE
Discord RPC Support

### ISSUE THREAD

**Issue by Naratzull** [OGSR/OGSR-Engine#156]
Планируете ли поддержку Дискорда как в X-Ray Oxygen или Anomaly?
![DiscordRPCExample](https://user-images.githubusercontent.com/44362807/63689122-8fe36b00-c822-11e9-99eb-1b504f4a79d4.png)

**Comment by KRodinn** [comment]
Может быть, в будущем. Если мне будет не лень)

**Comment by Naratzull** [comment]
> Может быть, в будущем. Если мне будет не лень)

Эх, хотел бы вам помочь, но движок лень собирать. Мне этот проект нравится очень.

**Comment by joye-ramone** [comment]
Что же там собирать. Открыть sln файл и выбрать Build &)

**Comment by Naratzull** [comment]
> Что же там собирать. Открыть sln файл и выбрать Build &)
С моим процессором 2-3 часа ждать)

**Comment by joye-ramone** [comment]
Хм. Даже сейчас после всех правок по сборке ?
У меня собирается за 30 мин на основном компе и за 45 на ноуте.

**Comment by KRodinn** [comment]
Чёт много. У меня полный ребилд - меньше 10 минут.

**Comment by Naratzull** [comment]
> Чёт много. У меня полный ребилд - меньше 10 минут.



> Хм. Даже сейчас после всех правок по сборке ?
> У меня собирается за 30 мин на основном компе и за 45 на ноуте.

Предположительно, но час точно уйдет.
