### ISSUE TITLE
Партикл трассера плоский относительно камеры и он еле заметен

### ISSUE THREAD

**Issue by tiger-vlad** [OGSR/OGSR-Engine#158]
Трассер еле заметно. Теперь игроку сложно определить куда полетела пуля, особенно если стрелять по дальним целям ( кстати рикошет отображается нормально). Баг хорошо заметен в 3д прицелах.
Сломалось на версии 2.0.777.
Предполагаю, что проблема в Tracer.cpp, а именно в методе FillSprite_Circle().

Вот [**видео на версии 1.0.527**](https://www.youtube.com/watch?v=ew756hQh1j8). Видно, что  трассер имеет форму круга.

А вот [**видео на версии 2.0.830**](https://www.youtube.com/watch?v=ZnUeZFs34w4):  здесь или вообще не видно трассер или видно, что партикл трассера плоский относительно камеры. Вот, что я имею в виду - **[Скрин](http://www.picshare.ru/uploads/190911/jLGtV85EYg.jpg)**.

**Comment by tiger-vlad** [comment]
В исключение могу добавить трассеры из "Винтореза" или "Грозы", там трассеры  заметны, но все равно видно, что рисуются они как-то иначе и круг не такой явный и четкий. 
[Видео ТЧ 1.0006](https://www.youtube.com/watch?v=TPIsWOEL5ho) 
[Видео OGSR 2.0.830](https://www.youtube.com/watch?v=zoWuiQsSJ0U)
Скрины:
[ТЧ vs OGSR](http://www.picshare.ru/uploads/190918/7ieYm0Qu52.jpg) - трассер на ТЧ четкий
[ТЧ vs OGSR](http://www.picshare.ru/uploads/190918/i3XaRNHicb.png) - также тут видно, что на ОГСР трассер вылетает не из центра.

**Comment by bigmack2304** [comment]
Кстати по поводу трассера, вроде как достаточно обновить текстуру fx_tracer.dds, тогда трассера снова будут видны, по крайней мере у меня это сработало. В архиве новая и старая текстуры - https://yadi.sk/d/DJvAykMZ4ACVOg

**Comment by KRodinn** [comment]
А новая текстура откуда?
Залил сюда, чтоб файл не потерялся, посмотрю на него когда-нибудь потом. 
[tracers.zip](https://github.com/OGSR/OGSR-Engine/files/4722950/tracers.zip)

**Comment by bigmack2304** [comment]
Вообще эту правку я нашел тут https://www.amk-team.ru/forum/topic/14065-ogsr-mod-pravki-i-modifikacii/?do=findComment&comment=1326084
Так что откуда ее выдернули неизвестно, но могу предположить что из зова припяти либо из чистого неба.

**Comment by KRodinn** [comment]
Интересно :thinking:

**Comment by joye-ramone** [comment]
в ЗП текстура такая же как в ТЧ почти. 32*32
А откуда взялась эта большая текстура - непонятно

**Comment by bigmack2304** [comment]
Сейчас распаковал чистый ЗП и там есть такая текстурка fx_tracer_weapons.dds она в точности такая-же какую я скинул ранее.

**Comment by joye-ramone** [comment]
Точно. Там же имя трейсера в конфиге указывается
[bullet_manager]
tracer_shader					= effects\bullet_tracer ;hud\default
tracer_texture					= fx\fx_tracer_weapons
А в ogsr hardcoded
`
CTracer::CTracer()
{
	sh_Tracer.create("effects\\bullet_tracer","fx\\fx_tracer");
`

**Comment by KRodinn** [comment]
ага, надо прописать `fx\fx_tracer_weapons` и, собственно, доложить его в геймдату.

**Comment by joye-ramone** [comment]
может стоит перенести часть Tracer.cpp из ЗП?

**Comment by KRodinn** [comment]
Надо ещё посмотреть на него сначала, что там с совместимостью и прочими нюансами.

**Comment by joye-ramone** [comment]
Можно хотя бы часть
`
	LPCSTR sh_name		= pSettings->r_string("bullet_manager", "tracer_shader");
	LPCSTR tx_name		= pSettings->r_string("bullet_manager", "tracer_texture");
`
