### ISSUE TITLE
Одиночки стреляют в баре - невозможно играть

### ISSUE THREAD

**Issue by hay20161** [OGSR/OGSR-Engine#159]
Здравствуйте, помогите пожалуйста решить проблему.

После некоторых квестов единичные одиночки рандомно начинают стрелять по ГГ в Баре. Иногда спускаются прямо к Бармену. Иногда один у костра. При виде ГГ начинает палить, два других продолжают сидеть (желтые).

Пытался распаковать gamedata.db_base_configs, ничего не выходит. Найти настройки не могу. Играть невыносимо. Как мне исправить ситуацию? Подойдет любой вариант кроме переигрывания

**Comment by KRodinn** [comment]
Ну во-первых, это не проблема движка. Ты же огср мод имеешь ввиду?
Во-вторых, скинь сейв рядом со стреляющим и полный лог игры.

**Comment by hay20161** [comment]
Приложил. Заранее спасибо.
[debug.zip](https://github.com/OGSR/OGSR-Engine/files/3679585/debug.zip)

По ходу дальнейщего прохождения столкнулся с такой же проблемой на янтаре. Идут 3 одиночки, как меня завидят **только один из них** начинает в меня палить. Остальные нейтралы. Если ввязаться в драку, то по возвращению в бар все одиночки становятся врагами.

Повторюсь, для меня и правка конфигов будет решением.

**Comment by KRodinn** [comment]
Хм, а чего ты ожидал? Чтобы после этого все друзьями были?
![](https://cdn.discordapp.com/attachments/507590575520743438/629564156517023754/ss_admin_10-04-19_09-18-04_l05_bar.png)

**Comment by KRodinn** [comment]
Я сегодня добрый.
[admin_quicksave.zip](https://github.com/OGSR/OGSR-Engine/files/3689263/admin_quicksave.zip)
Но в следующий раз с такими просьбами можешь даже не обращаться.
