### ISSUE TITLE
Автоопределение RU и WW

### ISSUE THREAD

**Issue by Xottab-DUTY** [OGSR/OGSR-Engine#160]
Как будет время, посмотрите эти коммиты, строго по порядку:
1. https://github.com/OpenXRay/xray-16/commit/09a15ae933088dd0e5bb6531b6ffed1dc271d65d
2. https://github.com/OpenXRay/xray-16/commit/efdd64650ee4472a6cfa73cecbc363b9a069bf5b
3. https://github.com/OpenXRay/xray-16/commit/1d92cff8a8ca4c44efed1744b94fda1fa092f7a8

©️ OpenXRay

Возьмите себе, отпадёт необходимость указывать ключ `-steam` для запуска стимовской версии. 😉

**Comment by KRodinn** [comment]
Спасибо, посмотрим :+1:
