### ISSUE TITLE
Не получается собрать движок

### ISSUE THREAD

**Issue by NikitaNikson** [OGSR/OGSR-Engine#170]
Добрый день! Заранее прошу прощение, если не туда пишу. Дело в том, что при сборке движка у меня выдаётся куча ошибок, в духе: "Не удается открыть файл включение: stdlib.h: No such file or directory"
В чём проблема и как эти файлы найти? (собираю через Microsoft Visual Studio Professional 2017 
Версия 15.9.17)
Спасибо :)

**Comment by KRodinn** [comment]
Каких-то компонентов не хватает значит. Вот так должно быть: 
![image](https://user-images.githubusercontent.com/16670637/70504569-089ed680-1b37-11ea-96f5-df1d99d60284.png)

**Comment by NikitaNikson** [comment]
Спасибо за пояснение :)
