### ISSUE TITLE
Смена имени ГГ

### ISSUE THREAD

**Issue by Graff46** [OGSR/OGSR-Engine#175]
У CActor есть метод SetName меняет имя ГГ на некоторых местах отображения (далее полях) в игре, другие поля изменяются через редактирование нет-пакета актора, имя ГГ при наведении на метку ГГ на карте в ПДА не меняется. Не плохо было-бы сделать единый метод смени имени ГГ и ссылаться на 1 переменную всем полям игры где выводится имя ГГ.

**Comment by joye-ramone** [comment]
Можно без пакетов обойтись
Пример https://github.com/dsh2dsh/op2ogse/blob/aeab3ba5c1316d4f7cacd4fdf68b1da7a14b3881/gamedata/scripts/dsh/dsh.script#L2996

**Comment by KRodinn** [comment]
Wiki походу никто не читает? Там описано, как сделать полное переименование главного героя, без всяких нетпакетов.

**Comment by Graff46** [comment]
Решено
