### ISSUE TITLE
Не меняется имя ГГ на метке карты КПК

### ISSUE THREAD

**Issue by Graff46** [OGSR/OGSR-Engine#178]
При смене имени ГГ как написано в вики:
```lua
function change_actor_name(newName)
	db.actor:get_inventory_owner():SetName( newName )
	local sobj   = db.actor:get_alife_object()
	local trader = sobj:get_trader()
	trader.character_name = newName
end
```
Не меняется подпись метки ГГ на карте в ПДА
 <a href="https://ibb.co/CvTdmdL"><img src="https://i.ibb.co/CvTdmdL/ss-01-15-20-23-58-34-l05-bar.jpg" alt="ss-01-15-20-23-58-34-l05-bar" border="0"></a>
<a href="https://ibb.co/MpqpDYJ"><img src="https://i.ibb.co/MpqpDYJ/ss-01-16-20-00-12-30-l05-bar.jpg" alt="ss-01-16-20-00-12-30-l05-bar" border="0"></a>

**Comment by KRodinn** [comment]
На метке в ПДА же просто текст из локализации, а не настоящее имя.
