### ISSUE TITLE
Не сохраняется заклинивший патрон в стволе.

### ISSUE THREAD

**Issue by bigmack2304** [OGSR/OGSR-Engine#179]
Надкнулся на такой баг. Если стрелять из оружия до тех пор пока оно не заклинит и после этого сохранится (не перезаряжая его перед сохранением), то после последующей перезагрузке этого сохранения, из этого оружия снова можно будет стрелять. Т.е факт того что ствол заклинил не сохраняется и сбрасывается после перезагрузки.

**Comment by Olil-byte** [comment]
Решение:
https://github.com/Olil-byte/OGSR-Engine/commit/a0ddd9925718e2217acefed66a885b5b734d3bb4
