### ISSUE TITLE
Солнце просвечивает сквозь землю

### ISSUE THREAD

**Issue by Mcbek-st** [OGSR/OGSR-Engine#182]
В начале игры солнечные лучи просвечивают сквозь бункер сидора.

**Comment by KRodinn** [comment]
Это проблема самого бункера. [**Вот тут**](https://www.amk-team.ru/forum/topic/13490-adaptaciya-graficheskoy-chasti-ogse/?do=findComment&comment=1100697) например описано, почему так.
