### ISSUE TITLE
Вылет demo_play

### ISSUE THREAD

**Issue by Graff46** [OGSR/OGSR-Engine#183]
Если записать демку с помощью demo_record, а потом её воспроизвести через  demo_play, то игра вылетит.
*На ванили работает.

**Comment by KRodinn** [comment]
demo_play вообще планировалось вырезать, насколько помню. Недорезали, вот и не работает.

**Comment by Graff46** [comment]
Я через него кат-сцены делал

**Comment by KRodinn** [comment]
Ну сочувствую, что сказать. Ты первый человек, юзающий демо_плей, которого я встречал.

**Comment by Graff46** [comment]
Какой последний коммит где demo_play рабочий?

**Comment by KRodinn** [comment]
Откуда ж я знаю когда он сломался? Я им никогда не пользовался. Предполагаю что очень давно.
