### ISSUE TITLE
Зависания при множественных коллизиях

### ISSUE THREAD

**Issue by Graff46** [OGSR/OGSR-Engine#184]
В моем моде есть заскриптованная сцена где от взрыва разбивается стеклянная колба с "мозгом" в  Х-16. При воспроизведении  вышеуказанной сцены с движком OGSR - происходят очень сильные зависания, в итоге игра повисает, приходится завершать через диспетчер процессов.
Я не уверен, но мне показалось, что при разбивании колбы на  OGSR  генерируется слишком много осколков, смотрится это как порошок, возможно из-за слишком большого числа осколков игра и повисает.
[Видео](https://youtu.be/dtblszcScpY?t=9600) сценки на ванильном движке

**Comment by KRodinn** [comment]
Запусти под отладчиком да глянь, где там виснет в момент взрыва.

**Comment by KRodinn** [comment]
Вспомнил, попробуй уменьшить `snd_targets` - до `32` или `16`. Не помню, сколько там было в ТЧ.

**Comment by Graff46** [comment]
Не помогло. А средства профилирования не хотят работать на 7ке(

**Comment by Xottab-DUTY** [comment]
Средства профилирования это не отладчик

**Comment by Graff46** [comment]
А как мне узнать какая ф-ция забирает ресурсы? Точками останова?

**Comment by KRodinn** [comment]
>в итоге игра повисает, приходится завершать через диспетчер процессов

Вот когда она повисла, в отладчике присоединяешься к процессу игры, паузишь его и смотришь, какой код выполняется в этот момент.

**Comment by Graff46** [comment]
Я сделал ряд тестов, оказалось, что всё дело в партиклах. В вики указано, что система проигрывания партиклов была переписана, возможно что-то пошло не так при множественных проигрывании партиклов.

**Comment by Graff46** [comment]
Решение: https://github.com/Graff46/OGSR-Engine/commit/e520822662f6cbe5d965e113a81e49b613980f6b
