### ISSUE TITLE
Возможность включать ПНВ в транспорте

### ISSUE THREAD

**Issue by Graff46** [OGSR/OGSR-Engine#190]
По умолчанию включить/выключить ПНВ находясь в транспорте нельзя, что не является логичным.

**Comment by joye-ramone** [comment]
Это решается скриптом в 10 строк.

**Comment by Graff46** [comment]
> 
> 
> Это решается скриптом в 10 строк.

Перехватом нажатия клавиш? А по нормальному, если назначения клавиш поменено будет.

**Comment by joye-ramone** [comment]
А в чем проблема с переназначением? Есть dik_to_bind и key_bindings.kNIGHT_VISION

**Comment by Graff46** [comment]
Все равно, это костыль получается, я вижу решение этой проблемы в движке.

**Comment by joye-ramone** [comment]
Оно там точно есть) 
Ждем PR

**Comment by Graff46** [comment]
Я не знаю как это сделать

**Comment by joye-ramone** [comment]
CarInput.cpp
Там обработка нажатий кнопок когда актор в машине. Нужно добавить еще обработку kNIGHT_VISION по аналогии с ActorInput.cpp
