### ISSUE TITLE
Работа эффекта ПНВ при камерах не только от первого лица

### ISSUE THREAD

**Issue by Graff46** [OGSR/OGSR-Engine#191]
Эффект от ПНВ работает на камере от 1-го лица, если переключиться на камеры 2-го и 3-го лица эффекты ПНВ не наблюдаются.
Также нет эффекта ПНВ при demo_play, но это спорный момент.

**Comment by KRodinn** [comment]
Ну как бы логично, разве от 2-3 лица может быть пнв? ПНВ на голове актора находится же, то бишь от 1-го лица.
