### ISSUE TITLE
Дрожание актора

### ISSUE THREAD

**Issue by marlock9** [OGSR/OGSR-Engine#193]
Между релизами 2.0.852 и 2.0.905 внесена регрессия, в результате которой на версиях движка >=2.0.905 камера при ходьбе "дрожит". Если переключиться в demo_record, то всё плавно. Мне это особенно заметно по причине использования 144 гц монитора и Freesync. 60 гц частота в меню -> откл., ограничение кадров -> откл.
Вижу в списке изменений 2.0.905: Исправлено дрожание оружия (на самом деле это дрожал актор), заметное при большом hud_fov.
Судя по всему, именно от этого коммита стало хуже. Коммит, видимо, вот этот: https://github.com/OGSR/OGSR-Engine/commit/3d1ce040f60948be1c9883274f3c3c10494c675f
Проверить у себя, к сожалению, не могу.

**Comment by KRodinn** [comment]
А есть какое-нибудь видео, чтоб посмотреть, как он дрожит?
Я вот не замечаю в игре.

**Comment by marlock9** [comment]
https://www.youtube.com/watch?v=FDHmm_DJaG8
По-моему очень хорошо видно.
На 852 всё очень плавно, как и во всех других модах.

**Comment by KRodinn** [comment]
Ну, если б ты не показал, я бы и не заметил никогда)
Ну а фикс Шокера нужный, он точно работает, но его видимо надо применять только в режиме прицеливания, чтобы этого побочного эффекта не было.
Этих видов дрожания в сталкере на самом деле много, например дрожание камеры при применении эффекторов https://youtu.be/5Loj49bT4zs?t=5456 (как это фиксить неизвестно)
Ещё худ (оружие и тп) может дрожать на больших локациях, если актор находится далеко от нулевых координат локации. (этого фикса в OGSR нет, я планировал добавить но забыл), [тут он](https://www3.gameru.net/forum/index.php?showtopic=23443&view=findpost&p=1670743)

**Comment by KRodinn** [comment]
@marlock9 проверь на [>>этой<<](https://github.com/OGSR/OGSR-Engine/suites/692200883/artifacts/6546637) версии. Теперь в режиме не прицеливаясь должно быть как раньше.

**Comment by marlock9** [comment]
Проверил, всё как ожидается: обычная ходьба плавная, при ходьбе в прицеливании дрожь.
Без этой правки с дрожанием совсем никак не обойтись?

**Comment by KRodinn** [comment]
Ну пока так. В будущем может придумаем что-то получше. Теоретически, если [добавление вот этих правок](https://www3.gameru.net/forum/index.php?showtopic=23443&view=findpost&p=1670743) сможет убрать все дрожания оружий, то от тех костылей наверное можно будет избавиться.
Этот Issue пусть до того времени остаётся открытым.

**Comment by marlock9** [comment]
Окей, подожду лучшего решения.
Всё-таки хочется, чтобы все моды, которые переносят на OGSR, также были избавлены от этой проблемы.

**Comment by KRodinn** [comment]
В последнем релизе вернул как было до этой проблемы. А дрожания оружий решил оставить до лучших времен, щас как-то лень с ними возиться.
