### ISSUE TITLE
Древний баг с музыкальным эмбиентом

### ISSUE THREAD

**Issue by TechNoir1982** [OGSR/OGSR-Engine#197]
Давно заметил, что в ТЧ музыкальный эмбиент не работает с 22:00 до 6:00. Смотрел конфиги — все выставлено и настроено. На АМК форумах тоже кто-то спрашивал про такое, но никто не знает с чем связана сама проблема. Немного поковырял конфиги я понял, что эмбиент не работает только с 22:00 до 23:59. Приведу пример из оригинала:
[l01_escape_musics]
music\amb01					=  6, 22,   0.2,   20, 40
music\amb20		    		= 22, 6,    0.2,   20, 40

В итоге эмбиент играет до 22:00 а потом до 6 утра будет гробовая тишина, но если немного изменить и сделать вот так:

music\amb01					=  6, 22,   0.2,   20, 40
music\amb20		    		= 0, 6,    0.2,   20, 40

То с 24:00 будет проигрываться эмбиент. Что ещё интересно, в подземках, где эмбиент должен играть круглосуточно:
music\amb11					=  0, 0,   0.2,   20, 40
Всё работает правильно и нет никакой паузы с 22:00 до 23:59

UPD. Примечательно, что такое есть только в Тень Чернобыля, а в аддонах всё работает правильно

**Comment by KRodinn** [comment]
В ЗП код действительно отличается. Я поправил, но не проверял, изменилось ли что-то.
Проверь и отпиши о результате.

**Comment by TechNoir1982** [comment]
Я бы проверил, но если честно немного не шарю как фикс добавить в движок

**Comment by KRodinn** [comment]
Тут каждый коммит собирается, вообще-то. Скачай собранный и проверь: https://github.com/OGSR/OGSR-Engine/actions/runs/164696540

**Comment by TechNoir1982** [comment]
Всё работает правильно, как в ЗП.

**Comment by TechNoir1982** [comment]
Потестил несколько часов, как оказалось, стало ещё хуже. Если на уровне выставлен круглосуточный эмбиент:

music\amb11					=  0, 0,   1.0,   20, 40

Он не работает вообще. Также по каким-то причинам ночной эмбиент может играть ночью, хотя он там даже близко не прописан

**Comment by KRodinn** [comment]
Это и в ЗП так?

**Comment by TechNoir1982** [comment]
нет, в ЗП всё отлично работает, там вообще никаких изъянов с эмбиентом

**Comment by KRodinn** [comment]
Ну тогда я просто верну как было. Мне лень в этом эмбиенте глубоко копаться, он не интересный.

**Comment by TechNoir1982** [comment]
А жаль, одна из важнейших составляющих сталкера. Но да, понимаю

**Comment by Egor179** [comment]
> А жаль, одна из важнейших составляющих атмосферы сталкера. Но да, понимаю

Так если проблема решается правкой конфига, есть ли смысл в движке копаться?
