### ISSUE TITLE
Баг с anim_idle_moving

### ISSUE THREAD

**Issue by TechNoir1982** [OGSR/OGSR-Engine#198]
Раскачка ходьбы сбивается если выглянуть влево/вправо. Прикладываю видео:
https://youtu.be/vpD8OwJqas4

**Comment by joye-ramone** [comment]
Я бы так и оставил.

**Comment by TechNoir1982** [comment]
> Я бы так и оставил.
Зачем?

**Comment by joye-ramone** [comment]
Движение с "выглядывание" медленее. Фактичски ГГ переходит с бега на шаг.
Раскачка с той же силой будет выглядит странно.

**Comment by joye-ramone** [comment]
Хотя, та же анимация играется и при движении шагом и в присядь. Может ты и прав.

**Comment by TechNoir1982** [comment]
В принципе, если заморочиться, то можно как в GUNSLINGER замедлить анимацию когда игрок ходит пешком/в приседе.

**Comment by KRodinn** [comment]
Это на самом деле не раскачка, а анимация оружия при ходьбе - `anim_idle_moving`.
Именно с раскачкой - таких проблем нет, она работает по другой технологии.
