### ISSUE TITLE
Action с параметрами в скриптовых диалогах

### ISSUE THREAD

**Issue by Shiroe-san** [OGSR/OGSR-Engine#200]
Пытаюсь добавить action в диалоге:
`phrase_script:AddAction( "darkholme.take_art(\""..k:section() .. "\")")`
и ловлю вылет:

> [error]Expression    : FATAL ERROR
> [error]Function      : CPhraseScript::Action
> [error]File          : e:\ogsr-engine\ogsr_engine\xrgame\phrasescript.cpp
> [error]Line          : 231
> [error]Description   : darkholme.take_art("af_soul_dyn1d") not found

Такого функционала не предусмотрено или я что-то делаю не так?

**Comment by joye-ramone** [comment]
Вылет именно на phrase_script:AddAction
или же в момент выбора этого ответа в диалоге ?

**Comment by Shiroe-san** [comment]
В момент выбора ответа.

**Comment by KRodinn** [comment]
Скриптовые экшены когда я это делал, не проверял, но по идее должны и они работать. Проверю на днях.

**Comment by joye-ramone** [comment]
Action и Precondition точно работали. Но я никогда не проверят с текстовыми параметрами.

**Comment by KRodinn** [comment]
я ща не у ПеКа, так что в качестве бреда предложу
```lua
phrase_script:AddAction( "darkholme.take_art("'"..k:section() .. "'")" )
```

**Comment by Shiroe-san** [comment]
Затестил, вылет с тем же логом.

**Comment by KRodinn** [comment]
Всё там работает, только что проверил. На примере скрипта проводников из огср мода `guiders.script`:
```lua
function show_awailable_locations(str, guider, actor, dialog_id, phrase_id)
	log3("~~str = [%s], guider = %s, actor = %s, dialog_id = %s, phrase_id = %s", str, guider:name(), actor:name(), dialog_id, phrase_id)
...
end

function init_guiders_dialog(dlg)
	local script = script_name().."."
...
		phr2:GetPhraseScript():AddAction(script.."show_awailable_locations('testing!', ...)")
...
end
```
Движок у тебя из этого репо взят? А то в одном из форков репо этот функционал кое-кто вырубил, по неведомым мне причинам.

**Comment by Shiroe-san** [comment]
Движок от dsh, сейчас попробую свежий скомпилить

**Comment by KRodinn** [comment]
Во, движок от Dsh, а баги к нам. Почему бы собственно к @dsh2dsh не обратиться? Он же теперь сам по себе, всё такое.
