### ISSUE TITLE
is_torch_enabled и другие каллбеки из xray extensions

### ISSUE THREAD

**Issue by NikitaNikson** [OGSR/OGSR-Engine#201]
Здравствуйте, дорогие разработчики. Пожалуйста, добавьте каллбек is_torch_enabled и остальные каллбеки из xray extensions. Почему-то некоторые из них попросту не были добавлены и/или были забыты

Заранее спасибо

**Comment by KRodinn** [comment]
Не были добавлены, потому что в них не было необходимости.
В вики написано, что "Перенесена **большая часть** правок оригинального OGSE и Xray Extensions...".
Большая часть **!=** все. Большая часть - это **более 50%**.
У кого есть необходимость - тот и добавляет/переносит что то новое.
Многое можно реализовать и без этих коллбеков. is_torch_enabled - это что, надо проверить включенность фонаря? Включенность фонаря можно проверить без всяких каллбеков:
```lua
	local torch = actor:item_in_slot( 9 )
	if torch and torch:is_torch() then torch = get_torch_obj( torch ) end
	local torch_enabled = torch and torch.on
```
Если нужен каллбек на включение фонарика - можно это сделать через каллбек нажатия клавиши.
С фонариком кучу наворотов можно сделать, без всяких спецкаллбеков, вот пример: https://github.com/dsh2dsh/op2ogse/blob/master/gamedata/scripts/dsh/dsh_torch.script
