### ISSUE TITLE
Баг с настройками графики SSAO (Рендер DX11)

### ISSUE THREAD

**Issue by Egor179** [OGSR/OGSR-Engine#205]
Не сохраняется настройка качества SSAO, при выставлении параметра "Очень высоко" игра требует перезагрузку, но после перезагрузки качество по прежнему на "Высоко". И так на OGSR Mod, Народная солянка OGSR, OGSR Engine SHOC EDITION (на других модах не проверял)
В чем может быть проблема?
<img src="https://i.paste.pics/a827379976263de86756ee0d2f47d7e4.png" width="986" height="578" alt="Screenshot">

**Comment by KRodinn** [comment]
Судя по всему, Пыс это сделали специально https://github.com/OGSR/OGSR-Engine/blob/a4cdd0c6f9ffef40c06bf72441d2c464730b432d/ogsr_engine/Layers/xrRenderPC_R4/r4_rendertarget.cpp#L342
Может затычки от багов каких-то.
Кст, ссао в сталкере, вообще не рекомендуют включать, если у тебя на это нет веских оснований. Ссао ж полоски вызывает.

**Comment by Egor179** [comment]
Про полоски узнал только на форуме, никогда их не встречал

**Comment by KRodinn** [comment]
Счастливый человек)
