### ISSUE TITLE
Где нужно создать папку build_config_overrides, чтобы изменить настройки?

### ISSUE THREAD

**Issue by TechNoir1982** [OGSR/OGSR-Engine#208]
Хотел включить статический рендер, но не понимаю где нужно создавать папку build_config_overrides. Я пробовал скопировать её в gamedata, bin_x64 и директорию с игрой, но статический рендер так и не появился. Смотрел сам файл в папке — сохранить после редактирования не забыл. Что я делаю не так?

**Comment by KRodinn** [comment]
Эта папка при сборке движка нужна, вообще-то.
А статического рендера здесь нет давно.
