### ISSUE TITLE
Шейдерные худы масок

### ISSUE THREAD

**Issue by rutrash** [OGSR/OGSR-Engine#211]
А в будущем не планируется добавление шейдерных масок как сделано в Anomaly, или последней версии Lost Alpha DC?

**Comment by KRodinn** [comment]
Если бы они на 100% шейдерные были, типа как rain drops, добавил бы.
Но в аномали у этих масок 87 мб текстур, так что нет.

**Comment by rutrash** [comment]
Может быть можно сделать поддержку масок в движке, а тем кому захочется сами докинут нужные ресурсы?
