### ISSUE TITLE
Подсветка худа рук при включенном фонарике как в ЗП

### ISSUE THREAD

**Issue by artkez** [OGSR/OGSR-Engine#212]
Уже давно гуглю этот момент, копался в исходниках ЗП, но так и не смог решить эту проблему: В ТЧ почему-то руки никак не реагируют на свет от фонарика, при полной темноте это выглядит не очень. (Самый первый скрин из ЗП, остальные из OGSR) 

![ss_user_07-10-20_13-59-38_(jupiter_underground)](https://user-images.githubusercontent.com/33177434/87148201-a79ad500-c2b6-11ea-8a53-0e36749e54bf.jpg)

![ss_user_07-10-20_14-03-46_(jupiter_underground)](https://user-images.githubusercontent.com/33177434/87148276-cbf6b180-c2b6-11ea-9e83-6e14b9bd5a68.jpg)

![ss_user_07-08-20_21-37-42_(jupiter_underground)](https://user-images.githubusercontent.com/33177434/87148351-eb8dda00-c2b6-11ea-9e76-af9a5ff27e6d.jpg)

**Comment by KRodinn** [comment]
Позиция/настройки фонарика могут быть другие, да и вообще, в ЗП система худа совершенно другая.

**Comment by artkez** [comment]
> Позиция/настройки фонарика могут быть другие
если речь о конфигах, то я полностью из ЗП их перенёс, но желаемого результата не достиг. Сейчас попробовал увеличить spot_angle.
![ss_user_07-10-20_14-51-28_(jupiter_underground)](https://user-images.githubusercontent.com/33177434/87151525-af5d7800-c2bc-11ea-98e6-1efe035bb08d.jpg)
Думаю, если отодвинуть подальше кость к которой крепится источник света, то должно получиться. Спасибо за наводку!

**Comment by KRodinn** [comment]
Всё оказалось проще.
Было: 
![ss_admin_07-30-20_19-04-20_(marsh)](https://user-images.githubusercontent.com/16670637/88947569-608e7700-d299-11ea-9031-16833f5f30f9.jpg)
Стало:
![ss_admin_07-30-20_19-09-44_(marsh)](https://user-images.githubusercontent.com/16670637/88947595-684e1b80-d299-11ea-9f6d-48f2598de4df.jpg)

**Comment by TechNoir1982** [comment]
> > ![ss_user_07-10-20_14-51-28_(jupiter_underground)](https://user-images.githubusercontent.com/33177434/87151525-af5d7800-c2bc-11ea-98e6-1efe035bb08d.jpg)
Это текстура для стандартных ТЧ рук? Можешь мне её отправить?

**Comment by artkez** [comment]
@TechNoir1982 это модель рук для долговской брони, брал из STCoP 2.9
