### ISSUE TITLE
Черные грани асфальта в Припяти

### ISSUE THREAD

**Issue by rutrash** [OGSR/OGSR-Engine#214]

**Comment by rutrash** [comment]
Приветствую! 
Столкнулся вот с такой проблемой, и даже не знаю причины этого, может ошибка в шейдерах?
P.S. Я ничего не редактировал, никаких тектур не добавлял, скрины сделал на чистом движке.
http://i-fotki.info/26/8b46a636334fd6a8530851944ad15aa12eacde377744275.jpg.html
http://i-fotki.info/26/830df809d99223354e43a9100dcb2cb62eacde377744275.jpg.html
http://i-fotki.info/26/1de401441bf5a021164c5e372877cea92eacde377744275.jpg.html
http://i-fotki.info/26/ee6c3b6ed7956493be7aae5502f7e5a42eacde377744275.jpg.html
http://i-fotki.info/26/5c68f99bfbc7e8f3aaa8175749583c982eacde377744275.jpg.html

**Comment by KRodinn** [comment]
Это оригинальная припять?

**Comment by rutrash** [comment]
Да, я же написал, стоит ванила и последняя версия движка.

**Comment by KRodinn** [comment]
У тебя вообще скрины как-то кринжово выглядят, как будто всё на самый-самый минимум выкручено.
Поставь этот юзер.лтх и проверь на нём: https://yadi.sk/d/C2LAKpNTtH6deQ

**Comment by rutrash** [comment]
Ахаххахах, я извиняюсь, забыл для скринов графен выкрутить :)

**Comment by KRodinn** [comment]
![parrot](https://user-images.githubusercontent.com/16670637/87855781-2c26cc80-c923-11ea-8640-ad14b81889ee.png)

**Comment by rutrash** [comment]
Фух, еле скрины на таких настройках сделал, чуть комп не взорвался, но не в этом суть, юзер толку не дал как этот баг был так и остался:
http://i-fotki.info/26/3deced1bcf816761c9a761ad1d008a842eacde377745779.jpg.html

**Comment by KRodinn** [comment]
хмм, а ты уверен, что это не ванильный баг локации? У меня ощущение, что там проблема с лайтмапами.

**Comment by artkez** [comment]
Посмотрел у себя - всё норм, такой фигни нет. Правда у меня не совсем ванила, стоит мод на погоду. Но локации стандартные.
![ss_user_07-18-20_18-39-26_(l11_pripyat)](https://user-images.githubusercontent.com/33177434/87856182-03ec9d00-c926-11ea-9156-a03722dfcee0.jpg)
![ss_user_07-18-20_18-39-42_(l11_pripyat)](https://user-images.githubusercontent.com/33177434/87856183-051dca00-c926-11ea-9132-5c67879b5db8.jpg)

**Comment by rutrash** [comment]
Спасибо что отметился, теперь осталось понять в чём может быть проблема у меня - к тому же думаю стоит упомянуть, что у меня такая хренотеть не только в последней версии движка появилась, а уже давно, к тому же помню что ставил SWTC погоду - и была такая же проблема.

**Comment by artkez** [comment]
А, действительно, сейчас поставил геймдату OGSR (та которая в папке Resources_SoC_1.0006), и вот: 
![ss_user_07-18-20_18-48-41_(l11_pripyat)](https://user-images.githubusercontent.com/33177434/87856302-ebc94d80-c926-11ea-890b-6fd13bae3e6a.jpg)

**Comment by rutrash** [comment]
Спасибо за содействие :D

**Comment by exostalker** [comment]
Found the culprit. Adding in this texture (for example, I simply pasted and changed the asphalt texture to this name) fixes these.

[01.09.20 17:25:59.331] ! Can't find texture 'detail\detail_grnd_sand'
[01.09.20 17:25:59.332] ! Fallback to default bump map: detail\detail_grnd_sand_bump
