### ISSUE TITLE
Цветной спекуляр

### ISSUE THREAD

**Issue by artkez** [OGSR/OGSR-Engine#215]
В оригинале спекулярный блик всегда имеет белый цвет, не зависимо от цвета источника освещения. 
Вот видео, демонстрирующее такую фичу: https://www.youtube.com/watch?v=tzzyrB2wXJc&feature=youtu.be
Ещё такое реализовано в LA: 
![ss_user_07-18-20_18-30-02_(la02_garbage)_w_default_ladc_cloudy_08_00_to_default_ladc_cloudy_09_00_gt_08-18](https://user-images.githubusercontent.com/33177434/87856735-b6722f00-c929-11ea-9f3b-4e959683e8d1.jpg)
![ss_user_07-18-20_18-30-09_(la02_garbage)_w_default_ladc_cloudy_08_00_to_default_ladc_cloudy_09_00_gt_08-18](https://user-images.githubusercontent.com/33177434/87856736-b7a35c00-c929-11ea-8d94-33f0df4a464b.jpg)

**Comment by KRodinn** [comment]
Для старого рендера нам присылали PR #128 , там был реализован Colored specular.
Можно и для новых рендеров завести, я думаю.

**Comment by KRodinn** [comment]
@artkez проверь, изменилось ли что то, вот шейдер 
[combine_1.zip](https://github.com/OGSR/OGSR-Engine/files/4943506/combine_1.zip)

**Comment by artkez** [comment]
@KRodinn проверил бы, но увы сегодня нет возможности. Завтра смогу проверить.

**Comment by bigmack2304** [comment]
Я проверил, изменения есть.
![Безымянный](https://user-images.githubusercontent.com/37216622/87874676-e8e95e00-c9f5-11ea-9557-609c9947caeb.png)

**Comment by artkez** [comment]
Аналогично. Спасибо, KRodinn!
