### ISSUE TITLE
Выпадения дропа под текстуры

### ISSUE THREAD

**Issue by rutrash** [OGSR/OGSR-Engine#216]
Планируется ли фикс выпадения вещей под текстуры, например когда ломаешь ящики и дроп под текстуры проваливается, или я что-то не понимаю и это не в движке делается?

**Comment by KRodinn** [comment]
Конкретно для вещей из ящиков фиксится [**тут**](https://github.com/OGSR/OGSR-Resources/blob/bb08a2d3c7d15dd52e84111eda5936b68a8f351f/gamedata/scripts/xr_box.script#L128) в трёх местах.
