### ISSUE TITLE
Прицеливание кликом мыши или функция "wpn_aim_toggle"

### ISSUE THREAD

**Issue by BenRaven3409** [OGSR/OGSR-Engine#218]
Есть ли возможность добавить данную функцию в движок. Чисто субъективно, в первом сталкере не хватает прицеливания просто кликом мыши, как в Чистом Небе и Зове Припяти.

**Comment by joye-ramone** [comment]
Уже есть предложение https://github.com/OGSR/OGSR-Engine/pull/141

**Comment by BenRaven3409** [comment]
У меня получилось ввести эту функцию в движок путём копирования нескольких строк кода из исходников OpenXRay(файлы console_commands.cpp и Weapon.cpp). надеюсь никто тапками за такую наглость не закидает. Тестирую пока-что только второй день, но всё работает стабильно, вроде.
Сегодня проверил на последней версии движка, тоже работает.

Я далеко не програмист и на гитхабе недавно, поэтому не знаю как, и вообще нужно ли, заливать мои модифицированные файлы.

**Comment by KRodinn** [comment]
??? Как бы уже есть PR с этим функционалом, о чём выше и сказано. Зачем нам ещё один такой же PR, либо какой-то архив?
