### ISSUE TITLE
Работают ли старые сохранения и что по совместимости с модами?

### ISSUE THREAD

**Issue by DarkKel** [OGSR/OGSR-Engine#219]
Вопрос в названии. 

Нужна ли НИ, или работает с сейвами (сейв запустился, но на открытии диалога с рандомным нпц крашнуло с ошибкой по диалог энгину (не сохранил ошибку..)).

И как с совместимостью с модами для тч ?

**Comment by KRodinn** [comment]
Сохранения созданные на ориг. движке - работают. Обратно - нет.
По адаптации - [**>>тут<<**](https://github.com/OGSR/OGSR-Engine/wiki/%D0%90%D0%B4%D0%B0%D0%BF%D1%82%D0%B0%D1%86%D0%B8%D1%8F-%D0%BC%D0%BE%D0%B4%D0%BE%D0%B2-%D0%BF%D0%BE%D0%B4-%D1%8D%D1%82%D0%BE%D1%82-%D0%B4%D0%B2%D0%B8%D0%B6%D0%BE%D0%BA).
А вылеты из за диалогов могут быть если ты пытаешься запустить двиг на игре с 4 патчем, насколько я помню.

**Comment by DarkKel** [comment]
> 
> 
> Сохранения созданные на ориг. движке - работают. Обратно - нет.
> По адаптации - [**>>тут<<**](https://github.com/OGSR/OGSR-Engine/wiki/%D0%90%D0%B4%D0%B0%D0%BF%D1%82%D0%B0%D1%86%D0%B8%D1%8F-%D0%BC%D0%BE%D0%B4%D0%BE%D0%B2-%D0%BF%D0%BE%D0%B4-%D1%8D%D1%82%D0%BE%D1%82-%D0%B4%D0%B2%D0%B8%D0%B6%D0%BE%D0%BA).
> А вылеты из за диалогов могут быть если ты пытаешься запустить двиг на игре с 4 патчем, насколько я помню.

Да не, патч 1.0006. Гог-версия

**Comment by DarkKel** [comment]
и по совместимости - я не кодер, чтобы понимать что\как правильно править ))

Не определено с чем оно работает "сразу", а чему может требоваться адаптация?

Сейчас накинул движок на пак из: hd model addon, photo realistic zone (ретекстур), Vurt flora GCO, Prone mod (ГГ ложится, типа как в Anomaly), OWR3_SoC (оружейный реплейсер), Vivid Weather (шейдеры переписываются этим движком) и Butcher mod (нужен нож для отрезания конечностей мутантов, убирает окно их инвентаря).
Вроде как работает, но был разок упомянутый выше краш, и хз как "на дистанции" оно продолжит работать..

**Comment by KRodinn** [comment]
> Не определено с чем оно работает "сразу"

С тем что не затрагивает скрипты. Ну и сторонние шейдеры использовать нельзя.

> Вроде как работает, но был разок упомянутый выше краш

Ну если повторится, пришли полный лог после краша.

**Comment by DarkKel** [comment]
Скрипты есть в butcher mod - bind_monster.script

и в 

Vivid weather - bind_stalker.script, ui_main_menu.script, vivid_sun.script

**Comment by KRodinn** [comment]
ну скрипт меню точно нельзя менять. Да и я сомневаюсь, что он сильно нужен для погоды. Там небось просто какой нибудь показ версии мода в меню приписали.

**Comment by DarkKel** [comment]
> 
> 
> ну скрипт меню точно нельзя менять. Да и я сомневаюсь, что он сильно нужен для погоды. Там небось просто какой нибудь показ версии мода в меню приписали.

Версия, и в конце это:

function set_vivid_1()
level.set_weather("vivid",true)
news_manager.send_tip(db.actor, "%c[0,0,255,25]Clear пресет первой версии", nil, nil, 10000)	
end
function set_vivid_2()
level.set_weather("vivid_cloudy",true)
news_manager.send_tip(db.actor, "%c[0,0,255,25]Cloudy пресет", nil, nil, 1000)	
end
function set_vivid_3()
level.set_weather("vivid_stormy",true)
news_manager.send_tip(db.actor, "%c[0,0,255,25]Stormy пресет", nil, nil, 1000)	
end
function set_vivid_4()
level.set_weather("vivid_pure",true)
news_manager.send_tip(db.actor, "%c[0,0,255,25]Clear пресет", nil, nil, 1000)	
end
function set_vivid_5()
level.set_weather("vivid_foggy",true)
news_manager.send_tip(db.actor, "%c[0,0,255,25]Foggy пресет", nil, nil, 1000)	
end

**Comment by KRodinn** [comment]
тестовые штуки походу

**Comment by DarkKel** [comment]
.ltx файлы с такими названиями есть в config/weather. weather_vivid_cloudy.ltx и т.д.

**Comment by DarkKel** [comment]
"На всякий" начал новую игру. Убрал vivid weather.
~2 часа работало, потом краш с окном "fatal error"...

Лог:

https://drive.google.com/file/d/1elIYr4ZCXBVnN8HED3eBdyC6QK0k-fTa/view?usp=sharing
