### ISSUE TITLE
У человека вылетает при запуске с двумя ошибками (стим-версия)

### ISSUE THREAD

**Issue by DarkKel** [OGSR/OGSR-Engine#222]
Проблема в заголовке.

Скрины ошибок:

https://imgur.com/RQyNETc

https://imgur.com/P6zDGJj

**Comment by rutrash** [comment]
-steam в параметрах запуска прописывал?

**Comment by KRodinn** [comment]
Очевидно что не прописал. Причем об этом на главной странице репо написано, почему никто не читает???

**Comment by DarkKel** [comment]
да, решена проблема.
Просто у меня работает без прописания, вот и просил.. сорри )
