### ISSUE TITLE
Проблема со звуковым модом

### ISSUE THREAD

**Issue by DarkKel** [OGSR/OGSR-Engine#223]
В логе звуковой мод выдает вот это:
! Invalid ogg-comment version, file:  k:\games\s.t.a.l.k.e.r. shadow of chernobyl\gamedata\sounds\ambient\rain.ogg

Можно ли исправить и как ? (без ogsr ошибки не возникает)

У меня такое в лог пишет, но игра работает (и сам мод тоже) У другого человека игра крашит с этой ошибкой.

**Comment by KRodinn** [comment]
звук дождя должен быть этот https://github.com/OGSR/OGSR-Engine/tree/main/Game/Resources_SoC_1.0006/gamedata/sounds/ambient . Я же не просто так его туда положил. Ну или любой другой из ЗП.

**Comment by DarkKel** [comment]
Безвариантно (адаптация или еще как)? Который с ogsr идет - практически отсутствует звук, а в этом моде эффект "капель по шлему" )

**Comment by KRodinn** [comment]
Ну от ЗП должны подходить.

**Comment by DarkKel** [comment]
Вот и не понятно.. Повторюсь - у меня все ок (хоть в логе и есть ошибка), а у другого человека краш с этой ошибкой в буфере..

**Comment by KRodinn** [comment]
Если у тебя работает а у кого-то нет, значит этот кто то что то не так делает.

**Comment by rutrash** [comment]
Кстати, поскольку тут зашла тема дождя хочу спросить: у меня одного капли на экране сжирают фпс на уровне включения саншафтов каких нибудь?

**Comment by DarkKel** [comment]
Но при этом вышеупомянутая ошибка у меня тоже есть ) Просто она не приводит к крашу

**Comment by KRodinn** [comment]
> Но при этом вышеупомянутая ошибка у меня тоже есть )

То что это пишется в лог, это норма, но вылетать там не может, ассерта там нет:
https://github.com/OGSR/OGSR-Engine/blob/0a2f0d1c59cf4c316f801166adf61e9229d00117/ogsr_engine/xrSound/SoundRender_Source_loader.cpp#L120

**Comment by KRodinn** [comment]
> Кстати, поскольку тут зашла тема дождя хочу спросить: у меня одного капли на экране сжирают фпс на уровне включения саншафтов каких нибудь?

Если у тебя слабый пека, то возможно. У меня далеко не топ ( RX 560 ) но заметной разницы от капель я не видел.

**Comment by rutrash** [comment]
Очень печально конечно что не поиграть с ними, ведь выглядит просто супер.

**Comment by KRodinn** [comment]
а что за пека то?

**Comment by rutrash** [comment]
gtx 630m 1gb, 4 озу, intel i5 2450m.

**Comment by KRodinn** [comment]
Да, мобильные видеокарты - это печалька конечно. Я в своё время тоже намучался с ноутами, знаю, как с ними тяжело играть и какое они говно.

**Comment by rutrash** [comment]
Ну фпс более менее вприципе могу и на dx11 играть, рендеры я заметил особо на фпс не влияют.

**Comment by DarkKel** [comment]
Еще бы фризов (ванильных-стелкеровских) небыло... )

**Comment by KRodinn** [comment]
> Ну фпс более менее вприципе могу и на dx11 играть, рендеры я заметил особо на фпс не влияют.

Ну сам по себе дх11 он должен быстрее работать чем дх9, другое дело что на дх10-11 тут активированы отражения в воде, настройку для вкл/выкл которых мне до сих пор лень вынести в меню. Сейчас это может сажать фпс по сравнению с дх9.

**Comment by rutrash** [comment]
Да вроде вообще не напрягает)

**Comment by KRodinn** [comment]
> Еще бы фризов (ванильных-стелкеровских) небыло... )

Ну это надо скрипты править. Значительная часть фризов из за загрузки озвучки при выходе в онлайн НПСа происходит.

**Comment by DarkKel** [comment]
> 
> 
> > Еще бы фризов (ванильных-стелкеровских) небыло... )
> 
> Ну это надо скрипты править. Значительная часть фризов из за загрузки озвучки при выходе в онлайн НПСа происходит.

Я вроде про другие - которые при спауне-прогрузке нпц (типа входа в бар и т.п.). Фризы как и в ЗП до 3-4 секунд порой..

**Comment by rutrash** [comment]
Про бар проде dsh писал, там нужно вроде конфиги править.

**Comment by rutrash** [comment]
Вот нашёл. Цитата: Принудительным выводом всех в онлайн из net_spawn актора.

**Comment by KRodinn** [comment]
Ну при подходе к бару куча нпс выходит в онлайн, это в т.ч. то что я описал.
Можно их всё время в онлайне держать, у @dsh2dsh так и сделано.

**Comment by rutrash** [comment]
Жалко то, что такие вот вещи например для ванилы не выкладывают, просто в таких вещах надо неплохо шарить чтобы понимать что делать.

**Comment by KRodinn** [comment]
Если полезешь в оригинальные скрипты что-то исправлять/переписывать/добавлять, остановиться сложно. Из этого процесса не вылезешь потом.
Я вот перепилил кучу скриптов огср мода, потратил кучу времени в никуда и не понятно к чему пришел...

**Comment by rutrash** [comment]
Пришёл к созданию лучшего мода 2020-го года :D

**Comment by KRodinn** [comment]
Ну я бы так не сказал. Там куча специфических проблем осталась, которыми я не доволен.
Самая главная из них - рандомные краши внутри d3d11.dll на версиях Windows младше Windows 10. Это моя боль.
Причем, это не проблема движка, в других модах с этим движком такой проблемы нет. Вот конкретно в огср моде эта проблема. Чёрная магия да и только. Хотя конечно можно сказать что это проблема самой винды/драйверов. Но очень странно, что на Windows 10 всё ок, а на более младших вот такая беда.

**Comment by rutrash** [comment]
Да вроде всё ок, у меня очень мало вылетов было.

**Comment by rutrash** [comment]
Был бы он так плох у него не было бы такого высокого рейтинга)

**Comment by DarkKel** [comment]
"держать в онлайне" - это не чревато крашами? (типа из-за перегрузок и т.п.)

**Comment by KRodinn** [comment]
> Был бы он так плох у него не было бы такого высокого рейтинга)

Ну может быть) Просто у меня очень высокие требования к качеству. Я вот например любые стримы по сталкеру смотрю - в первую очередь все баги вижу. 95% людей их не заметят. Это комплекс разработчика наверно.

> "держать в онлайне" - это не чревато крашами? (типа из-за перегрузок и т.п.)

Перегрузок чего? Памяти? Тут во первых x64, во-вторых, в последних версиях движка текстуры в оперативную память не грузятся. Тут нечему перегружаться.

**Comment by rutrash** [comment]
Да не нужно себя так загонять, идеальный мод сделать практически нереально.

**Comment by DarkKel** [comment]
> Перегрузок чего? Памяти? Тут во первых x64, во-вторых, в последних версиях движка текстуры в оперативную память не грузятся. Тут нечему перегружаться.

Ну тут я "не шарю" )
Постоянный онлайн чем-либо опасен? И как его включить? )

**Comment by KRodinn** [comment]
> Постоянный онлайн чем-либо опасен? И как его включить? )

Тут сделано https://github.com/dsh2dsh/op2ogse можешь поискать, но если в скриптах не разбираешься, лучше не лезть в это.

**Comment by DarkKel** [comment]
> 
> 
> > Постоянный онлайн чем-либо опасен? И как его включить? )
> 
> Тут сделано https://github.com/dsh2dsh/op2ogse можешь поискать, но если в скриптах не разбираешься, лучше не лезть в это.

ясн )

**Comment by DarkKel** [comment]
Раз уж пошло общее обсуждение - спрошу тут..

1. Есть ли возможность реализации в ТЧ квик-слотов полноценных, или максимум - вывод на экран количество определенных предметов и привязка кнопок для их использования?

2. Почему солнечные лучи применяются и к луне? )

**Comment by joye-ramone** [comment]
1. Делается скриптами сейчас элементарно. Зачем это в движок тянуть ?

**Comment by DarkKel** [comment]
>     1. Делается скриптами сейчас элементарно. Зачем это в движок тянуть ?

А есть рабочие реализации?
Я видел только один подобный мод, но он работает так как я описал (т.е. то, что в "слотах" задается в конфиге, в игре их не изменить)

**Comment by joye-ramone** [comment]
Готового примера что бы взять и включить - нету
Но движок сейчас позволяет сделать все, что надо для этих быстрых слотов я думаю.

**Comment by KRodinn** [comment]
> Почему солнечные лучи применяются и к луне? )

это ж источник света. Они вроде и к молниям применяются (но это не точно).

**Comment by rutrash** [comment]
Да, на молниях тоже работает.
