### ISSUE TITLE
Перевод движка на сербский и английский

### ISSUE THREAD

**Issue by Nemrtvi** [OGSR/OGSR-Engine#224]
Здравствуйте, ребята.

Я веду разработку **[перевода ТЧ на сербский](https://sites.google.com/view/slavictranslations-ru/projects/shadow-of-chernobyl)** и хотел бы для его следующую версию перевести на сербский OGSR Engine.

Насколько я вижу, текстовых файлов в проекте всего два. Тем не менее, я хочу на всякий случай спросить, присутствуют ли какие-нибудь нелокализованные файлы (т.е. скиптовые файлы с текстом на русском), на которые нужно обратить внимание при переводе.

Если переводчика на английский язык уже не имеется, я мог бы протянуть руку и помочь перевести и на него (ведь дело у вас доброе!), но это будет после перевода на сербский.

**Comment by KRodinn** [comment]
Приветствую.

> Насколько я вижу, текстовых файлов в проекте всего два.

Да, два. В основном это тексты для меню.

Только вот какой смысл в этих переводах? Это ж движок, а не мод. Движок - он для разработчиков модов в первую очередь. Переводить моды на какие-либо языки, это задача этих самых разработчиков модов.

**Comment by Nemrtvi** [comment]
> Движок - он для разработчиков модов в первую очередь.

Это понятно. Тем не менее, и без модов приятнее играть на обновлённом платформе.

>  Переводить моды на какие-либо языки, это задача этих самых разработчиков модов.

То, что авторы ответят за переводы своих модов, разумеется. С другой стороны, если им придётся ещё и переводить новые параметры движка — для которого мог бы существовать официальный перевод — то получится лишняя работа, не так ли?

**Comment by KRodinn** [comment]
Ну если очень хочется - сделай перевод, я добавлю.

**Comment by Nemrtvi** [comment]
Я закончил перевод на сербский (не включая неиспользуемые в движке строки, которых было немало) и вскоре начну на английский переводить. Всё пришлю в одном PR.

![Perevod](https://steamuserimages-a.akamaihd.net/ugc/1479949943050306245/362BF11EC79C3C5434D611D0AD8F85BA4989A2C0/)

**Comment by Nemrtvi** [comment]
Всё:
https://github.com/OGSR/OGSR-Engine/pull/231
