### ISSUE TITLE
Лужи из < 2.0.777 

### ISSUE THREAD

**Issue by artkez** [OGSR/OGSR-Engine#225]
Недавно поиграл в новый мод который базируется на версии 1.0.688, и там увидел эти лужи - отличная фича. Не планируете переносить её на новые версии?

**Comment by rutrash** [comment]
Разве не было уже описано как их сделать в разделе "О лужах, фларах, объёмном тумане и не только (KD, 24.05.2015)"?

**Comment by artkez** [comment]
@rutrash в этом разделе в шапке написано:
![image](https://user-images.githubusercontent.com/33177434/90023978-0b049200-dcbd-11ea-8e48-0364bb163cac.png)

**Comment by KRodinn** [comment]
В том виде - нет. То ж огсе-лужи. Во-первых, мне их реализация не нравится, а во-вторых не нравится, что их надо руками на локациях расставлять, в отличие от луж на асфальте.
