### ISSUE TITLE
Не спаунится квестовый предмет в тайнике

### ISSUE THREAD

**Issue by DarkKel** [OGSR/OGSR-Engine#226]
Квест "Фамильное ружье" - в тайнике пусто.. Еще заметил, что некоторые обычные (не квестовые) тайники тоже пустые, но не все..

**Comment by rutrash** [comment]
Ты какие-то моды поверх накатывал?

**Comment by DarkKel** [comment]
Ничего, что задевало бы контент\спаун\экономику и т.п. (единственное - оружейный, но он только в виде реплейсера, без новых).
Да и на этой же подборке без ogsr такого не возникало..

**Comment by DarkKel** [comment]
Идеи-предложения? )

**Comment by rutrash** [comment]
Прям каждый раз проваливается? Ты не переигрывал?

**Comment by DarkKel** [comment]
Нет, не переигрывал

**Comment by rutrash** [comment]
А в чём проблема переиграть и проверить снова?

**Comment by rutrash** [comment]
Я сейчас проверил, ружье на месте
http://i-fotki.info/26/fe27d9f944464fb82b06f488c0cf49e42eacde380178183.jpg.html

**Comment by DarkKel** [comment]
> 
> 
> Я сейчас проверил, ружье на месте
> http://i-fotki.info/26/fe27d9f944464fb82b06f488c0cf49e42eacde380178183.jpg.html

Эм.. это в "месте его спауна" или что? Мы об одном и том же говорим?

У меня там шкафчики, в них ящик-тайник, в нем ничего.

**Comment by rutrash** [comment]
Какой ещё ящик? Это "Фамильное ружье" всегда в контейнере валялось.

**Comment by DarkKel** [comment]
Можешь скрин со входом в контейнер сделать? Я чтоли туплю... )

**Comment by KRodinn** [comment]
кто-то походу гуглом пользоваться не умеет
