### ISSUE TITLE
Однако, вылетат.

### ISSUE THREAD

**Issue by nasar75** [OGSR/OGSR-Engine#232]

**Comment by nasar75** [comment]
https://www.amk-team.ru/forum/topic/14229-narodnaya-solyanka-2016-ogsr-engine/?do=findComment&comment=1347044

**Comment by KRodinn** [comment]
Мда, печалька. Скорее всего это из за https://github.com/OGSR/OGSR-Engine/commit/b1a591ef44b2c769c09b6ae702206f3ae6f3dd8c . Хотел как лучше, а получилось как всегда. Странно что это заметили только щас, тот коммит был месяц назад. Придётся откатить его.
