### ISSUE TITLE
Странный рендеринг

### ISSUE THREAD

**Issue by NikitaNikson** [OGSR/OGSR-Engine#236]
Добрый день. Мой хороший друг столкнулся с очень странной проблемой: странные пересветы, которые, возможно, идут от ГГ. Юзер на дефолт откатывали и шейдер кеш чистили - не помогает
Ревизия 2.1.79
![jlRWh8ToIdA](https://user-images.githubusercontent.com/58656613/92082809-7c2bf680-edde-11ea-8d85-eedfe7d0d6f6.jpg)
![UTqnr2eudm4](https://user-images.githubusercontent.com/58656613/92082825-80f0aa80-edde-11ea-91fb-2887833f3f26.jpg)

Вот цитата напрямую: "Вблизи от гг будто пересвет какой то идет. Вот именно вблизи. Все, что дальше, вроде норм. На этой же дистанции люто вырвиглазные бампы. Может это как-то поможет, но команда r2_sun_lumscale_hemi влияет на этот эффект. Но я не могу поставить ее на ноль, будет достаточно жутко выглядеть в других местах)"

**Comment by KRodinn** [comment]
Отключение каких-то граф. опций ничего не меняет? Отражения в лужах например попробовать выключить, если это только на асфальте проявляется. И посмотреть, изменится ли что то.
Ну и этот юзер попробовать , например https://yadi.sk/d/C2LAKpNTtH6deQ

**Comment by NikitaNikson** [comment]
День добрый. Проблему нашли: странный конфиг погоды. Насколько я понял, с ТЧ-шной такого не наблюдалось

Думаю, надо закрыть топик

**Comment by Xottab-DUTY** [comment]
Привет
@NikitaNikson а есть ли возможность скинуть этот странный конфиг сюда?
