### ISSUE TITLE
вылет на динамике из-за модельки

### ISSUE THREAD

**Issue by Maxx-imum** [OGSR/OGSR-Engine#238]
Krodin привет. у меня вылетает ОГСР на втором рендере. методом проб и ошибок вскрылось, что всёму виной модельки оружия. самое обидно это то, что с теми-же модельками обычная тч запускается без всяких проблем

сейчас сбросил модельки на дефолт, кроме своих. Некоторые уровни грузятся, а некоторые вылетают
кстати, на статике(я добавлял) всё работает без вылетов

сами строки лога залил на pastebin https://pastebin.com/mZ3rcHGX

**Comment by KRodinn** [comment]
Тут вылет из-за аномалии. По логу могу предположить что некорректный `idle_light_anim` прописан у какой-то аномалии, либо что-то не так с файлом `lanims.xr`

**Comment by Maxx-imum** [comment]
спасибо, проверю.
напишу, если исправлю (+ оставлю название модели)

**Comment by NikitaNikson** [comment]
Приветствую. Похожая проблема
Откат lanims.xr помог

**Comment by KRodinn** [comment]
где вы такие оружейные паки берёте, которые lanims.xr заменяют??? Этот файлик ведь к оружию никакого отношения не имеет.
