### ISSUE TITLE
hud_adjust_mode not working

### ISSUE THREAD

**Issue by seaz5150** [OGSR/OGSR-Engine#239]
None of the modes work, only the showing of values with P works.

**Comment by KRodinn** [comment]
The zoom_offset setting works exactly, I personally tested it. And everything else is a duplicate of #116

**Comment by artkez** [comment]
@KRodinn такой вопрос - а position и orientation можно управлять этой командой?

**Comment by KRodinn** [comment]
лично я только точки прицелов настраивал этой командой.
