### ISSUE TITLE
Анимации смерти

### ISSUE THREAD

**Issue by Winsor** [OGSR/OGSR-Engine#240]
Уважаемый KRoddin - в Вашем движке Вы переносили из ЧН/ЗП анимации смерти НПС-ей. А именно аналог death_anims.h. Я попытался сделать аналогично - но всего чего я добился - труп бота при смерти просто "подпрыгивает". По дебагу анимация выбирается корректно из type_motion-ов и передается в m_interactive_motion->play(m_pPhysicsShell);
Не подскажете - чего не хватает для корректного проигрывания анимации?

**Comment by dsh2dsh** [comment]
А можно, предварительно, увидеть Ваш публичный репозиторий, уважаемый Winsor? А то как-то не красиво получается.

**Comment by Winsor** [comment]
Наличие публичного репозитария является обязательным требованием для получения ответа? На данный момент он закрыт, будет доступен после релиза мода. И в чем некрасивость? С Вашего репозитария данные файлы не брались.

**Comment by dsh2dsh** [comment]
Наличие публичного репозитория является хорошим тоном при просьбах о помощи у публичных проектов. Если ты ничего не дал сообществу, то кому ты сдался помогать тебе.

**Comment by Winsor** [comment]
Ок. Ваша позиция ясна.
