### ISSUE TITLE
Проблема со слотами

### ISSUE THREAD

**Issue by rutrash** [OGSR/OGSR-Engine#241]
Приветствую, у меня проблема: в external.ltx я включил доп. слоты из OGSE, и слоты работали, но при включении движковой раскачки слоты не работают. В чем может быть проблема?

**Comment by KRodinn** [comment]
никакой связи между этими настройками нет. Небось как-то криво поправил файлик/кодировку побил

**Comment by rutrash** [comment]
Ну не знаю,который раз это замечал слоты до раскачки работоспособны, а после включения они отключаются.

**Comment by KRodinn** [comment]
покажи конфиг с вкл раскачкой

**Comment by rutrash** [comment]
Вот, пожалуйста - https://yadi.sk/d/53LmoztwMEutiA.

**Comment by KRodinn** [comment]
не, ну это прекрасно
```ini
; Эффект раскачки оружия при движении.
; Для работы требуется секция с названием wpn_bobbing_effector. Пример настроек находится чуть ниже.
wpn_bobbing = true
[wpn_bobbing_effector]
limp_amplitude = 0.011
limp_speed     = 4.6
...
```
Если ты не понимаешь, почему это ломает все настройки ниже, то тебе стоит сначала изучить, как устроены конфиги в сталкере.

**Comment by rutrash** [comment]
Найс ответ(

**Comment by KRodinn** [comment]
у тебя настройки ниже, в тч. слоты, уже в секции `[wpn_bobbing_effector]` находятся, а не в `features`.
Нафига ты эту секцию прям там раскомментировал?

**Comment by rutrash** [comment]
Пипец я тугой, нихрена не понимаю, как слоты в бобинг факторе могут быть?

**Comment by joye-ramone** [comment]
[wpn_bobbing_effector] не должна быть в external.ltx вообще.
добав ее в effectors.ltx 
[wpn_bobbing_effector]:bobbing_effector
run_amplitude			=	0.005
walk_amplitude			=	0.0025
limp_amplitude			=	0.008

run_speed				=	7.0
walk_speed				=   6.0
limp_speed				=	5.0

crouch_k                = 0.75
;zoom_k                 = 0.1
scope_zoom_k            = 0.1

**Comment by rutrash** [comment]
Вот, вот это понятный ответ, благодарю!

**Comment by KRodinn** [comment]
Тебе бы лучше было самому понять, почему у тебя не работает. Иначе ты подобные ошибки в других конфигах делать будешь, и гадать, почему что-то поломалось. Притом что это далеко не самое сложное в сталкере.

**Comment by rutrash** [comment]
Да мой, косяк всё таки, я понимаю, извини за беспокойство и потраченные нервы.
