### ISSUE TITLE
Нецентрированная в OGSR Engine текстура

### ISSUE THREAD

**Issue by Nemrtvi** [OGSR/OGSR-Engine#244]
В качестве составной части перевода игры на сербский язык я делаю новую систему субтиров. К багрепорту прилагаю [**тестовую версию**](https://github.com/OGSR/OGSR-Engine/files/5317229/ogsr_subtitle_text.zip).

Так вот, за всеми субтитрами будет присутствовать фон. К сожалению, если сравнить с ванилью, в OGSR Engine этот фон центрируется не так, как надо:

<img src="https://user-images.githubusercontent.com/26684396/94810207-02deee00-03f4-11eb-89fc-8f8445ce3370.png" height="200"> <img src="https://user-images.githubusercontent.com/26684396/94810210-04101b00-03f4-11eb-887e-24cb0a6ad2ac.png" height="200">

С другой стороны, как ни странно, если подождать конца первого монолога Сидоровича и услышать "Ну, чё стоишь? Подходи, я не кусаюсь", то фон следующего субтитра будет вполне отцентрирован:

<img src="https://user-images.githubusercontent.com/26684396/94815143-7f74cb00-03fa-11eb-9860-e380b2f658b4.png" height="200">

Что тут происходит? Как решить данную проблему?

------

Код из первых двух скриншотов (`config\ui\closecaption.xml`):

```xml
<characters_voice-scenario-trader-trader_monolog1>
	<global_wnd/>
	<item>
		<length_sec>27.7</length_sec>
		<grab_input>0</grab_input>
		<main_wnd>
			<auto_static start_time="0" length_sec="4.8" x="512" y="640" width="550" height="69" alignment="c" complex_mode="1"> <!-- 2 lines -->
				<auto_static x="0" y="0" width="550" height="69" stretch="1" complex_mode="1">
					<texture a="128">intro\intro_back</texture>
				</auto_static>
				<text x="0" y="-2" font="graffiti32" r="240" g="217" b="182" align="c" vert_align="b">cc_characters_voice-scenario-trader-trader_monolog1-1</text>
			</auto_static>
			<auto_static start_time="5.5" length_sec="3.7" x="512" y="640" width="550" height="69" alignment="c"> <!-- 2 lines -->
				<auto_static x="0" y="0" width="550" height="69" stretch="1">
					<texture a="128">intro\intro_back</texture>
				</auto_static>
				<text x="0" y="-2" font="graffiti32" r="240" g="217" b="182" align="c" vert_align="b">cc_characters_voice-scenario-trader-trader_monolog1-2</text>
			</auto_static>
			<auto_static start_time="9.6" length_sec="4.2" x="512" y="640" width="550" height="69" alignment="c"> <!-- 2 lines -->
				<auto_static x="0" y="0" width="550" height="69" stretch="1">
					<texture a="128">intro\intro_back</texture>
				</auto_static>
				<text x="0" y="-2" font="graffiti32" r="240" g="217" b="182" align="c" vert_align="b">cc_characters_voice-scenario-trader-trader_monolog1-3</text>
			</auto_static>
			<auto_static start_time="14.2" length_sec="2.9" x="512" y="640" width="550" height="69" alignment="c"> <!-- 1 line -->
				<auto_static x="0" y="33" width="550" height="37" stretch="1">
					<texture a="128">intro\intro_back</texture>
				</auto_static>
				<text x="0" y="-2" font="graffiti32" r="240" g="217" b="182" align="c" vert_align="b">cc_characters_voice-scenario-trader-trader_monolog1-4</text>
			</auto_static>
			<auto_static start_time="17.9" length_sec="3" x="512" y="640" width="550" height="69" alignment="c"> <!-- 2 lines -->
				<auto_static x="0" y="0" width="550" height="69" stretch="1">
					<texture a="128">intro\intro_back</texture>
				</auto_static>
				<text x="0" y="-2" font="graffiti32" r="240" g="217" b="182" align="c" vert_align="b">cc_characters_voice-scenario-trader-trader_monolog1-5</text>
			</auto_static>
			<auto_static start_time="21.5" length_sec="4.9" x="512" y="640" width="550" height="69" alignment="c"> <!-- 2 lines -->
				<auto_static x="0" y="0" width="550" height="69" stretch="1">
					<texture a="128">intro\intro_back</texture>
				</auto_static>
				<text x="0" y="-2" font="graffiti32" r="240" g="217" b="182" align="c" vert_align="b">cc_characters_voice-scenario-trader-trader_monolog1-6</text>
			</auto_static>
		</main_wnd>
	</item>
</characters_voice-scenario-trader-trader_monolog1>
```

Код из второго скриншота (`config\ui\ui_custom_msgs.xml`):

```xml
<closecaption_2 x="512" y="640" width="550" height="69" alignment="c" complex_mode="1">
	<auto_static x="0" y="0" width="550" height="69" stretch="1">
		<texture a="128">intro\intro_back</texture>
	</auto_static>
	<text x="0" y="-2" font="graffiti32" r="240" g="217" b="182" align="c" vert_align="b"/>
</closecaption_2>
```

**Comment by KRodinn** [comment]
> если подождать конца первого монолога Сидоровича и услышать "Ну, чё стоишь? Подходи, я не кусаюсь", то фон следующего субтитра будет вполне отцентрирован:

> Что тут происходит? Как решить данную проблему?

Найти код, отвечающий за этот следующий субтитр, сравнить с остальными, ну и соотв. поправить эти остальные.

Ну и тут отписать, в чем разница. Самому интересно. Если в ваниле это работает по-другому, то это странно, да.

**Comment by Nemrtvi** [comment]
Стоит отметить, что способ отображения этих субтитров отличаются друг от друга. В первых скриншотах - туториалом, в другом - с помощью функции `hud:AddCustomStatic` в скрипте _closecaption.script_.

В соотношении 4:3 проблему можно исправить, задав координаты `x="14"` в автостатике фона в `config\ui\closecaption.xml`, а в 16:9 - `x="-50"`. Почему так - не знаю, но хотя бы работает.

**Comment by KRodinn** [comment]
скинь файлы для ТЧ, чтоб я смог запустить и на это посмотреть.

**Comment by Nemrtvi** [comment]
Вот, уже приложил в шапке репорта:
https://www.dropbox.com/s/8jd2jam3m1gcaq6/ogsr_subtitle_text.7z?dl=1

**Comment by Nemrtvi** [comment]
Закроем?

**Comment by KRodinn** [comment]
Когда след. релиз будет - само закроется.
