### ISSUE TITLE
забивание лога (ошибка в логике)

### ISSUE THREAD

**Issue by Maxx-imum** [OGSR/OGSR-Engine#245]
Добрый день! Переношу один мод на ОГСР (STALKER OFFLINE)
Туда я запихнул аи пак AI ADDITIONS SHOC 2.0. Сталкнулся с одной очень плохой проблемой: из-за этого пака, лог постоянно засирается. Это происходит только при каком-либо взаимодействии между НПС (будь то хит, открытие диалога и тд) В том числе и когда НПС реагируют на что-ли (например, на противника в лице сталкера или мутанта)

В лог постоянно идёт такая фраза:
[01.10.20 17:54:12.025] ! [CProblemSolverAbstract::evaluator]: condition_id 18573 ( 0, single_player, 18573 ) not found in evaluators()

Огромная просьба помочь. Заранее спасибо))

**Comment by KRodinn** [comment]
Эти строки в логе значат, что у НПС критические проблемы с планировщиком схем. Скорее всего, аи пак адаптирован некорректно / конфликтуют схемы.

**Comment by rutrash** [comment]
Мод основанный на Freeplay Start адаптировал? 0_0 я когда пытался адаптировать не получилось(

**Comment by Xottab-DUTY** [comment]
> Скорее всего, аи пак адаптирован некорректно / конфликтуют схемы.

А я думаю, что, скорее всего, дело в самом AI Additions. В ЗП и в ЧН он использует несуществующие эвалуаторы изначально, т.е. даже в оригинальной версии мода... Скорее всего, в версии для ТЧ тоже самое.

**Comment by KRodinn** [comment]
Да, возможно.
