### ISSUE TITLE
Arm texture changing bug

### ISSUE THREAD

**Issue by seaz5150** [OGSR/OGSR-Engine#246]
I am using the arm texture changing script from New Arsenal and I have noticed that the changing of bump maps works very unreliably. Basically the texture gets changed every time, but the bump maps very often get stuck on some of the weapons. One weapon might have the correct bump map but when switching to a bolt for example it has the wrong one (of the first suit worn for example).

Some of the time it can look like it is working fine but after reload it is broken again etc.

In New Arsenal it didn't matter because the bump maps are so flat you couldn't tell it was wrong. This could be the fault of the script, but I don't think it is. When you remove the line changing the texture and only keep the bump map change, it changes the bump maps correctly.

Hope you can help me, can send the script over if needed. Thanks)

**Comment by KRodinn** [comment]
Maybe you have bumps registered in `textures.ltx` / `.thm` for **ALL** hand textures?
They should not be prescribed for everyone, but only for those who are being replaced:
```lua
local arm_config = {
	-- These textures must have bumps in textures.ltx / thm
	["textures_to_replace"] = {
		"act\\act_arm_perchatka_cs",
		"act\\act_arm_perchatka_cs_bump",
		"act\\act_arm_css",
		"act\\act_arm_css_bump",
	},

	-- All other textures should not have .thm and should not be registered in textures.ltx.
	...
```
At least I have done this, and the bumps change, absolutely for sure.

**Comment by bigmack2304** [comment]
Я тоже решил поэксперементировать с этой проблемой и вот к чему пришел.
Использовал у себя такой код;
`   local t = texture_find("act\\act_arm_perchatka_cs")
      if t then
        local tex = t[ "act\\act_arm_perchatka_cs" ]
        local name = "hands\\"..perchatka
        tex:load(name)
      end
    local tb = texture_find("act\\act_arm_perchatka_cs_bump")
      if tb then
        local texb = tb[ "act\\act_arm_perchatka_cs_bump" ]
        local nameb = "hands\\"..perchatka.."_bump"
        texb:load(nameb)
      end
    local tbr = texture_find("act\\act_arm_perchatka_cs_bump#")
      if tbr then
        local texbr = tbr[ "act\\act_arm_perchatka_cs_bump#" ]
        local namebr = "hands\\"..perchatka.."_bump#"
        texbr:load(namebr)
      end`
Удалил новые текстуры и бампы рук из textures.ltx и вроде как действительно все работало, менялась основная текстура и бампы. Но вот только менялось все это так как надо только на худе с биноклем, если взять в руки оружие то меняется только основная текстура а бампы перестают отображаться. В дальнейшем я закомментировал все строчки связанные с заменой бампа но от этого тоже ничего особо не изменилось, на худе с биноклем был бамп от act_arm_perchatka_cs, что касается остальных худов, там он по прежнему не отображался. Однако если менять не основную текстуру а только bump и bump# то они нормально меняется на всех худах.

**Comment by seaz5150** [comment]
I just tried going through all the textures and making sure only and all arm textures included in the script are in textures.ltx. Didn't help. From using google translate it seems colleague here has the same problem.

**Comment by KRodinn** [comment]
![72gi](https://user-images.githubusercontent.com/16670637/95677908-a5a42300-0bd1-11eb-84f6-93413e4fa675.gif)

**Comment by seaz5150** [comment]
By the way I tried just keeping the bump map change in the script and then copying the functions to ui_main_menu, keeping only texture change line and calling it with a key. I think that worked every time. For some reason calling it at once doesn't work.

**Comment by xplhal03** [comment]
Would you check this out when you have time/feel like it? I really think it is a bug in the engine and would like to be able to use bump maps for the hands.

**Comment by seaz5150** [comment]
Would you check this out when you have time/feel like it? I really think it is a bug in the engine and would like to be able to use bump maps for the hands.

**Comment by KRodinn** [comment]
If your bump changes only for the active object at the time of the texture change, this is strange. I cannot explain why this is happening. Just try to change the script so that the textures reload when the object is changed in the hands of the actor. But this is a bad solution, and I cannot suggest another.

**Comment by seaz5150** [comment]
Not really, sometimes it happens like that, but it is very inconsistent. Well no bumps it is then.
