### ISSUE TITLE
Проблема с ЗП погодой + небольшой баг

### ISSUE THREAD

**Issue by OneMorePseudoCoder** [OGSR/OGSR-Engine#247]
Приветствую разработчиков, у меня есть вопрос. 

Захотел опробовать ЗПшную погоду в ТЧ и перекомпилировал движок с дефайном USE_COP_WEATHER_CONFIGS в VS 2019. Никаких других правок не было. После компиляции запихнул в gamedata ТЧ конфиги, текстуры, звуки и скрипт level_weather и подключил его в bind_stalker. Так же вырезал из level_weather упоминания скрипта benchmark. Пришлось добавить недостающий скрипт xr_s для работы с ltx. В game_maps_single прописал нужную погоду. В fsgame.ltx пути добавил соответственно.

Захожу и вижу, что погода не меняется и скайбокс (именно скайбокс, а не освещение) темнеет, но потом снова проявляется. Никаких шейдеров, материалов и партиклов из ЗП я не портировал и полагаю, что проблема именно в этом. И к слову: я использую не чистый ТЧ, а ТЧ с RMA модом и оружейным паком, **НО** уверяю вас: точно такое же явление происходило и в оригинале на более старой версии движка. Скажите, проблема в шейдерах или материалах? Может, в скрипте level_weather? И вообще хотелось бы видеть инструкцию по использованию ЗП погоды.

**А, ну и небольшой баг**: когда игра в оконном режиме, то окно показывает, что я играю в ЗП, т.е. написано "S.T.A.L.K.E.R: Call of Pripyat", а должно быть ТЧ, ну или какой нибудь "STALKER SOC OGSR". Тут уже на ваше усмотрение. Полагаю, вы забыли поменять название приложения в **Device_Initialize.cpp**. Это, конечно, не критично, но всё же баг.

**Comment by KRodinn** [comment]
Вот моя старая адаптация SWTC для ТЧ, когда я экспериментировал с ЗП погодами, там таких проблем вроде нет https://yadi.sk/d/YGh5O-tevm3iSg

> когда игра в оконном режиме, то окно показывает, что я играю в ЗП, т.е. написано "S.T.A.L.K.E.R: Call of Pripyat", а должно быть ТЧ

> Это, конечно, не критично, но всё же баг.

Нет, это сделано намеренно. Я исхожу из предположения, что разработчики драйверов делают какие-то костыли для поддержки старых игр, что б они лучше работали / не вылетали и тп. Ну и как вариант, они могут эти игры определять по имени окошка. И раз у нас рендеры ЗП, логично именовать окошко как в ЗП. Но я лишь предполагаю, может там всё совсем не так происходит.

**Comment by Xottab-DUTY** [comment]
> Ну и как вариант, они могут эти игры определять по имени окошка.

Как минимум, GeForce Experience определяет игру по пути и имени файла:
ТЧ – bin/XR_3DA.exe
ЧН/ЗП – bin/xrEngine.exe
Как оно отличает ЧН и ЗП не знаю, возможно читает данные вшитые в движок, в том числе, может имя окна.
Но если хоть что-то отличается, например папка bins, а не bin, или экзешник назван по-другому, то игру у́же не определяет.
Возможно, и драйвер нвидии так же определяет, или может у него ещё больше методов.. Ну а про AMD я не знаю)

**Comment by VovaMiller** [comment]
Вдруг кому-то поможет. Столкнулся с такой же проблемой при переходе на погоду ЗП: в определённые моменты игрового времени скайбокс темнел. У меня причиной этому послужили банально отсутствующие текстуры скайбоксов, достаточно их просто достать из ЗП.
