### ISSUE TITLE
Порт SSLR из R4 на R3

### ISSUE THREAD

**Issue by DoK74rus** [OGSR/OGSR-Engine#248]
Здравствуйте, пришел пополнить этот список своим странным вопросом) Дело в том что я не могу оценить работу SSLR так как мой комп банально не поддерживает Dx11 по этому я решил портировать этот эффект с помощью коммитов на DX10 рендер, в целом у меня получилось это сделать, по крайней мере проект собирается без ошибок но в игре оно всё равно не работает. 
Короче те файлы в папке shader/r3 заточены исключительно под 4 рендер или всё дело в кривом порте? 

Заранее спасибо за ответ если он будет)

**Comment by KRodinn** [comment]
Приветствую.

> Короче те файлы в папке shader/r3 заточены исключительно под 4 рендер

Нет, эти рендеры используют одни и те же шейдеры.

На самом деле sslr включен только для р4 всего по одной причине: я не придумал как сделать чтоб оно не конфликтовало с msaa. Поэтому сейчас так: на р3 есть msaa но нет sslr, на р4 есть sslr, но нет msaa.

А вообще желаю апгрейднуть пека. Щас даже всякие встроенные Intel HD умеют в дх12, не говоря уж про дх11.
