### ISSUE TITLE
Возможность добавить анимации к заклину и переключению режима огня

### ISSUE THREAD

**Issue by NikitaNikson** [OGSR/OGSR-Engine#250]
Добрый день. Можно ли ожидать в будущем такую фичу, как проигрывание анимации при клине пушек и переключению режима огня?

Насколько я понял, фичу с анимкой при клине оружия разрабы хотели добавить еще в 2005 (может даже раньше)
![f43](https://user-images.githubusercontent.com/58656613/98013611-648fdf00-1e1c-11eb-9e52-5bbf114685d5.png)

Также, было бы круто добавить anm_X эффекты для оружия (во избежании конфликтов, можно вынести это в отдельный define)

**Comment by AffectedOne** [comment]
Yes, i would like to see that to. I was looking at the code one time and, i think, saw possibility to enable some additional animations for weapons IF there is animations in weapon model and proper config file. Don't remember where exactly, though. But i'm assuming, someone who understand code, could put something like that and make it optional, so modders would be able to use the functionality.

**Comment by KRodinn** [comment]
Duplicate of #220
