### ISSUE TITLE
Вопрос по обновленному FastDelegate.

### ISSUE THREAD

**Issue by BeglViglosh** [OGSR/OGSR-Engine#252]
Здравствуйте. Пытаюсь перенести обновленный FastDelegate под свой проект в рамках Visual 2013 C++11. Так как,это единственный проект, где это производилось (хотя, может плохо искал), то хочу спросить у вас.
1) Имеется файл ChooseTypes.H (xrCore) в вашем проекте. Его не коснулось обновление. Интересуют эти строчки:
```cpp
  typedef fastdelegate::FastDelegate2<ChooseItemVec&,void*>	   	TOnChooseFillItems;
  typedef fastdelegate::FastDelegate2<SChooseItem*, PropItemVec&>	TOnChooseSelectItem;
  typedef fastdelegate::FastDelegate3<LPCSTR, HDC, const Irect&> 	TOnDrawThumbnail;
  typedef fastdelegate::FastDelegate0<>						   	TOnChooseClose;
```
Это верно под новый FastDelegate? Прошу меня поправить, если что не так.
```cpp
using TOnChooseFillItems  = fastdelegate::FastDelegate<void(ChooseItemVec&, void*)>;
using TOnChooseSelectItem = fastdelegate::FastDelegate<void(SChooseItem*, PropItemVec&)>;
using TOnDrawThumbnail    = fastdelegate::FastDelegate<void(LPCSTR, HDC, const Irect&)>;
using TOnChooseClose      = fastdelegate::FastDelegate<void()>;
```
2)В одной ситуации компилятор выдает ошибку **error C2593: 'operator =' is ambiguous	X:\trunk\xray\xr_3da\xrGame\ai\phantom\phantom.cpp**
Проблема, для примера, тут: 
```cpp
void CPhantom::SwitchToState_internal(EState new_state)
{
	if (new_state!=m_CurState){
		CKinematicsAnimated *K	= smart_cast<CKinematicsAnimated*>(Visual());
		Fmatrix	xform			= XFORM_center	();
		_UpdateEvent = 0; - здесь ошибка._
		// after event
		switch (m_CurState){
		case stBirth:		break;
...
```
 Такие ошибки есть у меня еще в Grenade.cpp,  GamePersistent.cpp, где есть подобные "приравнивания" к 0. 
Попробовал вот так, но не уверен, что это вообще правильно(для примера phantom.h):
```cpp
 	fastdelegate::FastDelegate<void()> UpdateEvent;
```
Замена:
```cpp
 	using UpdateEvent = fastdelegate::FastDelegate<void()>;
private:
	UpdateEvent		m_UpdateEvent;
```
Cоответственно, в Phantom.cpp:
```cpp
        UpdateEvent = 0;
```
На
```cpp
        m_UpdateEvent = UpdateEvent(0);
```
Это вообще правильно? Подскажите, пожалуйста, как выйти из этой проблемы.
На этом все. Спасибо и прошу прощения за небрежность оформления.

**Comment by KRodinn** [comment]
> Имеется файл ChooseTypes.H (xrCore) в вашем проекте.

Его надо удалить, он не используется. Какой-то кусок сдк недорезанный походу.

> Это верно под новый FastDelegate?

На первый взгляд - да. Если не верно, оно и не соберется скорее всего.

> Такие ошибки есть у меня еще в Grenade.cpp, GamePersistent.cpp, где есть подобные "приравнивания" к 0.

Это не приравнивание к нулю, а присвоение нулевого указателя. Нулевой указатель в современном C++ - это nullptr, а не 0, т.е. должно быть так:
```cpp
m_UpdateEvent = nullptr;
```
