### ISSUE TITLE
Вопрос: как выполнить мердж с ZRP / Question: is it possible to merge this with ZRP?

### ISSUE THREAD

**Issue by AL-97** [OGSR/OGSR-Engine#253]
Здравствуйте.
Не знаток, поэтому нужна помощь. Насколько я понимаю, по-умолчанию OGSR-Engine не поддерживает Zone Reclamation Project - вылетает с ошибкой. Но видел несколько любительских сборок которые мерджат движок с ZRP. Ни одна из них мне не подходит, хочется сделать под свой вкус. Подскажите пожалуйста, как можно ZRP заставить работать вместе с OGSR-Engine.

Hello.
I am a bit of a novice here, so I need some help. As far as I understand, OGSR-Engine doesn't work out of the box with Zone Reclamation Project, it crashes on starting the new game. However, I saw sever fan packs that merge those two. Unfortunately, neither of those would work for me as they add some mods that I'm not interested in, plus they are using older versions of the engine. So my question is how can I make OGSR-Engine work with ZRP?

[xray_al-97.log](https://github.com/OGSR/OGSR-Engine/files/5563534/xray_al-97.log)

**Comment by KRodinn** [comment]
I have no idea. This is the first time I hear about this mod) And in general, I do not do adaptations if I myself am not interested in it. [**>>Here<<**](https://github.com/OGSR/OGSR-Engine/wiki/%D0%90%D0%B4%D0%B0%D0%BF%D1%82%D0%B0%D1%86%D0%B8%D1%8F-%D0%BC%D0%BE%D0%B4%D0%BE%D0%B2-%D0%BF%D0%BE%D0%B4-%D1%8D%D1%82%D0%BE%D1%82-%D0%B4%D0%B2%D0%B8%D0%B6%D0%BE%D0%BA) are the top, most basic adaptation tips. All other errors, as a rule, can be corrected by looking at the code, they will be more obvious. In that log that you showed, without scripts, I can not say anything.
