### ISSUE TITLE
[feature] Анимация установки аддонов на оружие

### ISSUE THREAD

**Issue by NikitaNikson** [OGSR/OGSR-Engine#256]
Собственно, титульник говорит сам за себя 

Было бы неплохо сделать возможность установки особых анимаций на стволы. Сама тестовая анимка есть

**Comment by joye-ramone** [comment]
Аддонты в основном ставятся через инвентарь, как там и когда анимации показывать ?

**Comment by NikitaNikson** [comment]
ой, лол

забыл

однако, всё равно будет круто, если запилите :)

**Comment by joye-ramone** [comment]
есть скриптовый play_hud_animation
через него можно играть любые анимации в любом момент
