### ISSUE TITLE
при переходе с х10 на радар, при повторной загрузке дублируется звук.

### ISSUE THREAD

**Issue by Kokokokoka** [OGSR/OGSR-Engine#258]
windows 10.
это баг, событие воспроизведения звукового оповещения живёт после повторной загрузки сохранения.
steps to reproduce:
выключить выжигатель, выйти из лабы, дождаться начала разговора военных, загрузиться.
expected behavior:
играет только одно оповещние. элементы, которые относятся к предыдущему уровню/сейву жить не должны.

**Comment by KRodinn** [comment]
Ну как бы такое же можно и на приветственной речи сидора в самом начале игры воспроизвести, если задаться такой целью, и что? Я сам замечал это очень давно. Я не могу 100% сказать, что это баг именно движка, т.к. эти все сюжетные звуки из скриптов играются.

**Comment by Kokokokoka** [comment]
Спасибо за объяснение, тогда вопрос про баговость снимается.
