### ISSUE TITLE
Рандомные краши на свалке с неинформативным логом

### ISSUE THREAD

**Issue by kprintf** [OGSR/OGSR-Engine#259]
Спустя где-то минуту игры крашится. Пробовал сборку 2.1.152 и сборку мастера на момент сейчас (в дебаг билде не воспроизводится)
[xray_user.log](https://github.com/OGSR/OGSR-Engine/files/5647912/xray_user.log)

**Comment by KRodinn** [comment]
Ну для огср мода это норма как бы. Я подобное и раньше видел в логах. Если повторяется, скинь сейв, может в этот раз удастся что-то с этим сделать.

**Comment by kprintf** [comment]
Оно стабильно повторяется с стектрейсом в UIWindow, но почему-то только в релизном билде.
[user_quicksave.zip](https://github.com/OGSR/OGSR-Engine/files/5648562/user_quicksave.zip)

**Comment by kprintf** [comment]
Вот кстати, с того же сейва при попытке уйти с локи крашнуло, но в логе на этот раз более информативно (а ещё всплывающих окошек с ошибками аж две штуки выпало), кроме UIWindow есть что-то про луа скрипты
[xray_user.log](https://github.com/OGSR/OGSR-Engine/files/5649516/xray_user.log)

**Comment by KRodinn** [comment]
Вот почему я не могу это поправить, у меня они не повторяются, вот вообще. Гружу твой сейв, уже 10 минут игра идет в фоновом режиме, и ничего.

Попробуй добавь сюда в начало файла https://github.com/OGSR/OGSR-Engine/blob/0c3e00ddbc1344beef4a369e91889abc8cf6be02/ogsr_engine/xrGame/ui/UIWindow.cpp#L10
```cpp

#pragma optimize("", off)

```

И отпиши, изменится ли что то.

**Comment by kprintf** [comment]
Спустя пару дней (после перезагрузки компа) у меня с того же сейва оно тоже перестало воспроизводиться :(
Хотя именно когда вылетало, то после старта игры по новой воспроизводилось.
Видимо тут ничего не поделать, но если встречу вылеты то попробую и отпишусь.
