### ISSUE TITLE
Minor HUD glitches

### ISSUE THREAD

**Issue by dezo2** [OGSR/OGSR-Engine#260]
Hi, I run the EN version of gamefiles with "-steam" parameter and have found some glitches in HUD icons in bottom left corner:
- for binoculars there is 9x19 FMJ ammo displayed instead of bino icon
- for bolt there is a part of grenade launcher attachment (I think) displayed

Also on 2560x1440 dx11 all crosshairs (including bino) look weird with texture repeating on screen corners. But that I can fix myself by altering crosshair textures a bit in GIMP by resizing canvas of vanilla images to 1280x1024 without altering aspect ratio. Otherwise this engine is just great with those additions in graphics department and dx11 API. And it looks even better with mods, I really like it!

**Comment by joye-ramone** [comment]
Hi, that is not engine bug. all this can be fixed in gamedata.

**Comment by dezo2** [comment]
Thanks, I found the bino in gamedata\config\external.ltx -> binoc_firing = false. Maybe it should be set as default this way.

**Comment by dezo2** [comment]
Also found another switch for the crosshairs -> scope_textures_autoresize = false.
Crap, next time I dig in the gamedata before posting an "issue" here, sorry.
