### ISSUE TITLE
Застревает курсор при превышении веса

### ISSUE THREAD

**Issue by AL-97** [OGSR/OGSR-Engine#262]
Если в рюкзак набрать барахла больше лимита в 60кг, то курсор застревает в правом нижнем углу и, даже при открытии инвентаря, выложить ничего не получится. Туториал о превышении веса не уходит с экрана, также нельзя выйти в главное меню - выход из игры только через завершение процесса.

Сэйв с ошибкой: [al-97_quicksave.zip](https://github.com/OGSR/OGSR-Engine/files/5669079/al-97_quicksave.zip)

Сэйв перед ящиком с хабаром. Забираем барахло из ящика - получаем скрытый курсор и неубираемый туториал: [save.zip](https://github.com/OGSR/OGSR-Engine/files/5669230/save.zip)

**Comment by KRodinn** [comment]
Заспавнил в ящик кучу хлама, подошел, забрал, курсор сместился, но не застрял, двигается, нормально, окно туториала закрывается по esc, всё норм. И что это за сейвы? откуда?
Не могу сказать что я понял проблему.

**Comment by AL-97** [comment]
Первое сохранение должно показать ошибку "в действии", с застрявшим в нижнем углу курсором. Второе, способ повторить ошибку.
Но это неважно уже. Ошибка была на моей стороне - сэйв был старый, сделанный на одной из предыдущих версий движка. Если начать новую игру, то ошибка не дуплицируется. Можно закрывать. Прошу прощения за неразбириху.
