### ISSUE TITLE
Как адаптировать огсм под это дело?

### ISSUE THREAD

**Issue by sairento-hiruzu** [OGSR/OGSR-Engine#263]
На кордоне всё норм, но при переходе на свалку вылет. Говорят, дело в bind_stalker, но что именно править я не нашёл. Неужто придется каждое изменение в скрипте проверять вручную?

**Comment by KRodinn** [comment]
Главные правила [**》тут《**](https://github.com/OGSR/OGSR-Engine/wiki/%D0%90%D0%B4%D0%B0%D0%BF%D1%82%D0%B0%D1%86%D0%B8%D1%8F-%D0%BC%D0%BE%D0%B4%D0%BE%D0%B2-%D0%BF%D0%BE%D0%B4-%D1%8D%D1%82%D0%BE%D1%82-%D0%B4%D0%B2%D0%B8%D0%B6%D0%BE%D0%BA), все остальные проблемы как правило индивидуальны и править их придется самостоятельно.

**Comment by joye-ramone** [comment]
Любом мод надо будет адаптировать. И это не вопрос к движку, в вопрос к кривым модам которые чудом работали

**Comment by rutrash** [comment]
В адаптации под огсм не вообще ничего сложного.

**Comment by sairento-hiruzu** [comment]
увы, в логе вылета ничего полезного я не нашёл, а в слепую неоч как то копать
