### ISSUE TITLE
3D пда

### ISSUE THREAD

**Issue by i-love-kfc** [OGSR/OGSR-Engine#265]
Возможно ли на ТЧ реализовать 3д пда, как в аномалии или в ганслингере?

**Comment by KRodinn** [comment]
Если кто-то сделает худовую 3д-модель пда, то можно об этом подумать.

**Comment by OneMorePseudoCoder** [comment]
> Если кто-то сделает худовую 3д-модель пда, то можно об этом подумать.

Можно временно использовать модель из Gunslinger'a или Anomaly.

**Comment by KRodinn** [comment]
так в зп ж система рук другая, не подойдет

**Comment by artkez** [comment]
> так в зп ж система рук другая, не подойдет
Есть у кого распакованная геймдата Anomaly?
Скиньте худовую (ну и мировую желательно) модель пда, и .omf файлы с анимациями для пда и рук. 
Если скинут, то на выходных перенесу на ТЧшную систему рук и выложу в этот топик.

**Comment by KRodinn** [comment]
Да мне скинули уже.
Всё равно я этим заниматься не буду, как минимум в этом году.

**Comment by StereoPunk** [comment]
> Да мне скинули уже.
> Всё равно я этим заниматься не буду, как минимум в этом году.

Не могли бы поделится моделькой ?

**Comment by KRodinn** [comment]
https://cdn.discordapp.com/attachments/775460551727906887/788778661699649606/73c763c76ce2a8ce.rar
