### ISSUE TITLE
Ошибка 0xc000007b

### ISSUE THREAD

**Issue by PiratBuildov** [OGSR/OGSR-Engine#266]
Положил в папку bin_x64 все требуемые xrEngine'ом dll'ки и при запуске вылазит ошибка:
![image](https://user-images.githubusercontent.com/76006289/102119185-c565fa80-3e51-11eb-9880-fefd26dce3b1.png)

**Comment by KRodinn** [comment]
никакие дллки ложить в эту папку не надо. Надо зайти вот сюда https://github.com/OGSR/OGSR-Engine/issues/50 , прочитать там всё внимательно и сделать как там написано.

**Comment by PiratBuildov** [comment]
Убрал те dll'ки, указанное в #50 все установлено было ещё до этого, но при запуске теперь такое:
![image](https://user-images.githubusercontent.com/76006289/102236794-fa7f5500-3f04-11eb-8382-2560e349d19f.png)

**Comment by PiratBuildov** [comment]
да, на стим ставлю

**Comment by KRodinn** [comment]
Если бы ты внимательно прочитал [**>>ридми<<**](https://github.com/OGSR/OGSR-Engine#for-the-engine-to-work-with-the-worldwide-version-of-soc-use-the---steam-launch-parameter) , то у тебя бы не возникло ни каких проблем с запуском WW-версии игры.

**Comment by PiratBuildov** [comment]
я уже разобрался, спасибо!
