### ISSUE TITLE
Утерянный xrRenderer_R1.dll

### ISSUE THREAD

**Issue by OneMorePseudoCoder** [OGSR/OGSR-Engine#267]
Есть проблема: попытался скомпилировать сборку **dev2** со статикой, но **xrRenderer_R1.dll** в папке не появился, но в самом разрешении он есть. Вы его запороли или решили под корень вырезать?

**Comment by KRodinn** [comment]
Ну как бы мы не поддерживаем статический рендер. Не вырезали, вырезать лень, просто отключили и исключили из сборки. Можешь попробовать напрямую проект этого рендера собрать в студии, если уж очень хочется. Но он кривой был да и вполне возможно сломали давным давно. За это время его ж не собирал никто.

Да и вообще, меня бомбить начинает когда где-то пишут про статику в сталкере. Какая статика в ~~2020~~ **2021** году, алло?
Для всяких бомж-ПК же есть renderer_r2a. Это р2 со статическим солнцем, почти тоже самое что и статика.
И опять же, насколько это должен быть бомж-пека, который в 2021 году не умеет в дх11, не говоря даже про р2???
Имея такой бомж-пека, допустим, надо не о статике думать, а о том, как бы приобрести нормальный пека. Щас уже даже всякие встроенные intel hd в дх12 умеют.
