### ISSUE TITLE
Второй пояс для патронов, и перенос пояса для артов из ЗП, с количеством ячеек в зависимости от костюмов.

### ISSUE THREAD

**Issue by D1m0n93** [OGSR/OGSR-Engine#269]
Оставлю это тут, вдруг когда-нить запилят...

**Comment by KRodinn** [comment]
_Для информации: На данный момент эта система не рассчитана на арты, занимающие больше одной ячейки. Так что имейте ввиду, что всякие колбы по три ячейки, патроны и тп. на пояс сувать не надо, результат будет печальным._
TODO: что-то придумать с этим, или написать в wiki, чтоб так не делали.

**Comment by joye-ramone** [comment]
это все жутко усложнит. проще разрешать вещать на пояс всегда айтемы по одной ячейке
