### ISSUE TITLE
Снова поймал ту самую ошибку...

### ISSUE THREAD

**Issue by Castlesoap** [OGSR/OGSR-Engine#270]
> [13.01.21 04:25:03.703] ***************************[ScriptCrashHandler]**********************************
> [13.01.21 04:25:03.704] stack traceback:
> [13.01.21 04:25:03.704] *********************************************************************************
> [13.01.21 04:25:03.704] ********************************************************************************
> [13.01.21 04:25:03.704] !![LogStackTrace] Thread: [UNKNOWN], ExceptionCode: [c0000005]
> [13.01.21 04:25:04.185] [CPlanner::update] stack_trace:
> Module: [C:\S.T.A.L.K.E.R\bin_x64\xrGame.dll], AddrPC.Offset: [000007FEE07DB14C], File-->Line: [D:\a\OGSR-Engine\OGSR-Engine\ogsr_engine\xrGame\agent_enemy_manager.cpp-->582] + [11 byte(s)]
> Module: [C:\S.T.A.L.K.E.R\bin_x64\xrGame.dll], AddrPC.Offset: [000007FEE07DB4C8], File-->Line: [D:\a\OGSR-Engine\OGSR-Engine\ogsr_engine\xrGame\agent_enemy_manager.cpp-->612] + [5 byte(s)]
> Module: [C:\S.T.A.L.K.E.R\bin_x64\xrGame.dll], AddrPC.Offset: [000007FEE07DF2FD], File-->Line: [D:\a\OGSR-Engine\OGSR-Engine\ogsr_engine\xrGame\agent_manager_actions.cpp-->73]
> Module: [C:\S.T.A.L.K.E.R\bin_x64\xrGame.dll], AddrPC.Offset: [000007FEE07D9EC6], File-->Line: [D:\a\OGSR-Engine\OGSR-Engine\ogsr_engine\xrGame\action_planner_inline.h-->126]
> Module: [C:\S.T.A.L.K.E.R\bin_x64\xrGame.dll], AddrPC.Offset: [000007FEE07D92A1], File-->Line: [D:\a\OGSR-Engine\OGSR-Engine\ogsr_engine\xrGame\agent_manager.cpp-->130]
> Module: [C:\S.T.A.L.K.E.R\bin_x64\xrGame.dll], AddrPC.Offset: [000007FEE08A61FC], File-->Line: [D:\a\OGSR-Engine\OGSR-Engine\ogsr_engine\xrGame\Ai\Stalker\ai_stalker.cpp-->739]
> Module: [C:\S.T.A.L.K.E.R\bin_x64\xrEngine.exe], AddrPC.Offset: [000000013F6496BB], File-->Line: [D:\a\OGSR-Engine\OGSR-Engine\ogsr_engine\xr_3da\xrSheduler.cpp-->356]
> Module: [C:\S.T.A.L.K.E.R\bin_x64\xrEngine.exe], AddrPC.Offset: [000000013F649A79], File-->Line: [D:\a\OGSR-Engine\OGSR-Engine\ogsr_engine\xr_3da\xrSheduler.cpp-->462]
> Module: [C:\S.T.A.L.K.E.R\bin_x64\xrGame.dll], AddrPC.Offset: [000007FEE09BAB78], File-->Line: [D:\a\OGSR-Engine\OGSR-Engine\ogsr_engine\xrGame\GamePersistent.cpp-->590]
> Module: [C:\S.T.A.L.K.E.R\bin_x64\xrEngine.exe], AddrPC.Offset: [000000013F67A1AC], File-->Line: [D:\a\OGSR-Engine\OGSR-Engine\ogsr_engine\xr_3da\pure.h-->86]
> Module: [C:\S.T.A.L.K.E.R\bin_x64\xrEngine.exe], AddrPC.Offset: [000000013F679288], File-->Line: [D:\a\OGSR-Engine\OGSR-Engine\ogsr_engine\xr_3da\device.cpp-->441]
> Module: [C:\S.T.A.L.K.E.R\bin_x64\xrEngine.exe], AddrPC.Offset: [000000013F679570], File-->Line: [D:\a\OGSR-Engine\OGSR-Engine\ogsr_engine\xr_3da\device.cpp-->212]
> Module: [C:\S.T.A.L.K.E.R\bin_x64\xrEngine.exe], AddrPC.Offset: [000000013F679D1E], File-->Line: [D:\a\OGSR-Engine\OGSR-Engine\ogsr_engine\xr_3da\device.cpp-->314]
> Module: [C:\S.T.A.L.K.E.R\bin_x64\xrEngine.exe], AddrPC.Offset: [000000013F67939E], File-->Line: [D:\a\OGSR-Engine\OGSR-Engine\ogsr_engine\xr_3da\device.cpp-->387]
> Module: [C:\S.T.A.L.K.E.R\bin_x64\xrEngine.exe], AddrPC.Offset: [000000013F63EB00], Fun: [Startup()] + [296 byte(s)], File-->Line: [D:\a\OGSR-Engine\OGSR-Engine\ogsr_engine\xr_3da\x_ray.cpp-->217]
> Module: [C:\S.T.A.L.K.E.R\bin_x64\xrEngine.exe], AddrPC.Offset: [000000013F63EE76], Fun: [WinMain_impl()] + [478 byte(s)], File-->Line: [D:\a\OGSR-Engine\OGSR-Engine\ogsr_engine\xr_3da\x_ray.cpp-->417]
> Module: [C:\S.T.A.L.K.E.R\bin_x64\xrEngine.exe], AddrPC.Offset: [000000013F63C5EC], Fun: [WinMain()] + [72 byte(s)], File-->Line: [D:\a\OGSR-Engine\OGSR-Engine\ogsr_engine\xr_3da\x_ray.cpp-->438]
> Module: [C:\S.T.A.L.K.E.R\bin_x64\xrEngine.exe], AddrPC.Offset: [000000013F699DB2], Fun: [__scrt_common_main_seh()] + [262 byte(s)], File-->Line: [d:\agent\_work\63\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl-->288] + [33 byte(s)]
> Module: [C:\Windows\system32\kernel32.dll], AddrPC.Offset: [0000000076BE570D], Fun: [BaseThreadInitThunk()] + [13 byte(s)]
> Module: [C:\Windows\SYSTEM32\ntdll.dll], AddrPC.Offset: [0000000076E4385D], Fun: [RtlUserThreadStart()] + [29 byte(s)]
> [13.01.21 04:25:04.185] ********************************************************************************

Снова поймал ту самую ошибку,что и пол года назад.

Ситуация, вроде как, прояснилась. После стычки сталкеров и вояк на Агропроме, остались лежать 2 раненных сталка и один, добивающий, вояка. Но у этого вояки: как раз оказалось, что есть out_restrictor, поэтому он не может пойти добивать сталкера, т к. сталкер находился в не зоны этого рестриктора. 

А вообще было бы неплохо всунуть в этот движок функцию cast_planner и смотреть, например: на апдейте, что происходит с неписем,  в той или иной ситуации.

2) Насколько критично это сообщение:

>  [CLevel::g_sv_Spawn]: agr_stalker_0000[8500] already net_Spawn'ed, ProcessDestroyQueue()

Посмотрел этого трупика, ничем он не отличается, может в модельке кости не так расположены?

**Comment by KRodinn** [comment]
Да я не забыл про это. Ну смотри, этот коммит вроде как должен это пофиксить (ну наверно): https://github.com/dsh2dsh/OGSR-Engine/commit/aa2b366dff0137d4020fac6246a55a0809eff6e4 , но он имеет некоторые побочные эффекты которые мне до сих пор лень починить, поэтому его здесь нет.
Да и вообще я не знаю, есть ли смысл возиться, если эта ситуация повторяется раз в полгода и не везде.
Duplicate of #237

**Comment by KRodinn** [comment]
Хотя можно просто откатить пока изменения в раненых сделанные ранее, мб так и сделаю.

**Comment by Castlesoap** [comment]
А в коммите  говорится же про сталкера который погиб или ранен, или я чего-то не понимаю?. А если наш раненный будет находится в недосягаемости ( например: у сталкера который назначен убивать раненного есть ин или аут рестрикторы или, на худой конец, раненный находится в невалидном вертексе...?

**Comment by KRodinn** [comment]
Да мало ли про что там написано, надо на код смотреть, а не на писанину.

**Comment by Castlesoap** [comment]
Это да! Вот только код для начала нужно прочитать и понять, а на это время нужно!

**Comment by KRodinn** [comment]
ну в общем, минут через 15 оно соберется https://github.com/OGSR/OGSR-Engine/actions/runs/481215889 скачаешь проверишь, будут ли там эти проблемы.

**Comment by Castlesoap** [comment]
Как только, так сразу... Прямо сейчас проверить увы не получится!

**Comment by Castlesoap** [comment]
Протестировал откат. И скажу следующее: если сталкер не может добраться до нпс, он ведет по нему огонь, даже если тот ранен, да и другие неписи перестали тупить ( доставать и перезаряжать оружия, хотя я это дело правил в xr_combat_ignore), но обычный юзер может натолкнуться на данную проблему. Из минусов - разве, что всей толпой идут добивать бедолагу. Если до отката момент, когда сталкер не мог добраться до раненного и прибить окончательно учитывался, значит можно подумать оставлять изменения, сделанные раннее.  Иначе можно предвидеть ситуации, когда непись находится на вышке ( к примеру: это на Ростке) откуда ему никогда не выбраться, а ему добавляется раненный сталкер в память. Я вообще думаю, это стоит делать через эвалуаторы, добавлять флажки для схем типа схем: ремарк и кэмпер, а не делать всё в движке! Это сугубо мое мнение!

2) Разобрался я с проблемой в логе` [CLevel::g_sv_Spawn]: agr_stalker_0000[8500] already net_Spawn'ed, ProcessDestroyQueue()`

А также при загрузке сохранения:` processing_enabled ->destroy_queue.push_back`

Оказывается трупик был добавлен в ин рестриктор (agr_space_restrictor_0002). Не стал менять ему (рестриктору) значение, мало ли там баг в аи сетке, и неписи в будущем будут пытаться преодолеть его. А просто телепортул чувака в эпицентр перестрелки вояк и сталкеров ( пусть там лежит) =)
И ошибка исчезла!
Такое тоже обнаружил у заключенного долговца в ТД, там рестриктор поправил!

3) И как насчет добавить из ЗП функцию cast_planner?

**Comment by KRodinn** [comment]
1. Ну тогда откат оставляю, раз это помогло и ошибок больше нет.
2. Это просто информация, на неё не разработчикам движка обращать внимание не стоит. Конкретно эта запись говорит о том, что `agr_stalker_0000` пытался выйти в онлайн дважды и это предотвращено. Ориг. движок такое не предотвращает. Конкретно для тебя эта информация значения в общем-то не имеет никакого. Что-то менять, кого-то телепортировать куда-то нет никакой необходимости.
Стоит обращать внимание на красные сообщения в консоли ( в логе начинаются на `!` ) и то не на все и не всегда.

> И как насчет добавить из ЗП функцию cast_planner?

Это для скриптов, несколько я вижу. А что она даёт?

**Comment by Castlesoap** [comment]
С помощью нее можно работать в внутренними планировщиками в таблице stalker_ids, которые в игре обозначены как константы. 
Можно делать подобное: 
```
--
local action = manager:action(stalker_ids.action_combat_planner)
local combat_action_planner = cast_planner(action)
combat_action_planner:remove_action(stalker_ids.action_kill_wounded_enemy) --33
--
```

**Comment by KRodinn** [comment]
Ок, можешь отдельный issue создать про это, чтоб я не забыл?

**Comment by Castlesoap** [comment]
Ок, я таки сделал. Но тогда у меня вопрос про двойную регистрацию. А не будет ли такого, что при повторной регистрации обжекта заменит существующий id , на другой. Это может привести к коллизиям, разве нет? Или в движке и это учтено?

**Comment by KRodinn** [comment]
нет, всё норм будет
