### ISSUE TITLE
Патроны на поясе(несовместимость)

### ISSUE THREAD

**Issue by stalkersof** [OGSR/OGSR-Engine#273]
В последней ревизии движка 181. Перестал работать патроны на поясе. Скорее всего из-за чтения параметра max_belt поясом для артефактов. Если есть возможность поправьте.

Старенький баг еще если включить билдовскую раскачку в конфигурационном файле external.ltx, то перестают читаться параметры настроек из этого файла находящиеся ниже. Выход есть просто перенести то что нужно выше.

И еще хотелось бы инверсивную кинематику чтобы сделали опционально, т.к у меня пак моделей нпс с другими файлами анимации и весь лог забивается руганью
!![CIKLimbsController::PlayLegs] No foot stseps for animation: animation name: [idle_2_idle_1], animation set: [actors\fat_npc_animation.omf]
Ну или сделать опционально вывод лога, вылета нет в данном случае.

**Comment by KRodinn** [comment]
> Перестал работать патроны на поясе.

Как именно перестали работать? Они не должны были сломаться.Я щас не у пека, но не представляю, как они могут перестать работать.

Насчет кинематики - это сообщение значит что кинематика в омфах как бы включена но типа не настроена. Надо долбить автора чтоб пофиксил. Ну или заменить этот омф на обычный, или переопределить омф для конкретных моделей, которые юзают этот проблемный омф. В wiki ест  инструкция как это сделать.

> Старенький баг еще если включить билдовскую раскачку в конфигурационном файле external.ltx, то перестают читаться параметры настроек из этого файла находящиеся ниже. Выход есть просто перенести то что нужно выше.

Баг? Это просто пример. Никто же не говорит что его надо раскомментировать прям там. Да и в здравом уме никто не будет его там раскомментировать. Т.к. если кто-то так сделает, значит он не понимает принцип работы ini файлов - самых простейших файлов конфигурации, которые есть в винде. ( ltx - этот тот же самый ini по сути своей ). А раз не понимает настолько простые вещи  - значит в моддинге , а уж тем более в движках и тп ему делать  нечего, ничего хорошего из этого не выйдет.

**Comment by joye-ramone** [comment]
Блин уже второй раз пишут про раскачку. неужели не ясно что если в конфиге тут же раскомментировать пример, то в примере идет имя секции, и весь файл после читаться уже будет неправильно....
