### ISSUE TITLE
Анимации

### ISSUE THREAD

**Issue by StereoPunk** [OGSR/OGSR-Engine#277]
Приветствую разработчиков, можно ли на данном движке заблокировать анимации, то есть не проигрывать например анимацию спринта или ходьбы для определенного оружия?

**Comment by StereoPunk** [comment]
А если ее в моделе нету вовсе, получится таким методом ее убрать?

ср, 17 февр. 2021 г. в 00:14, Krodin <notifications@github.com>:

**Comment by KRodinn** [comment]
Што? Ты хочешь убрать то чего в модели нет?
Я не понял вопроса совсем.

**Comment by StereoPunk** [comment]
Нет, нужно сделать так чтобы на определенном оружии не проигрывались
анимации бега и ходьбы, оставить только анимации доставания и убирания
оружия.

ср, 17 февр. 2021 г. в 02:01, Krodin <notifications@github.com>:

**Comment by joye-ramone** [comment]
так 
anim_idle_sprint = idle
anim_idle_moving = idle
поставить анимации idle (которой не может не быть) на бег и на спринт. Остальные анимации будут работать.

**Comment by StereoPunk** [comment]
> так
> anim_idle_sprint = idle
> anim_idle_moving = idle
> поставить анимации idle (которой не может не быть) на бег и на спринт. Остальные анимации будут работать.

Ну нету у меня idle анимации в модели 

![image](https://user-images.githubusercontent.com/47627453/108548719-d1bd7680-731e-11eb-94da-c692009c2d26.png)

**Comment by KRodinn** [comment]
Ну так с этого надо было начинать. Мы ж тут думаем что у тебя оружие и поэтому не понимаем, почему у оружия айдловой анимации нет.
Но мне всё равно не понятно, зачем надо запрещать какие-то анимации, будь то спринт и тп.
Я видел реализацию анимированных предметов без всяких запретов анимаций, тут обсуждали https://github.com/OGSR/OGSR-Engine/issues/261#issuecomment-740650751
Там, грубо говоря, надо заспавнить предмет, поместить в слот, чтоб проигралась анимация типа "доставания", по таймеру его удалить, когда анимация проигралась. Всё.

**Comment by StereoPunk** [comment]
Да, именно так и работает эта система. А запрет нужен для того что бы анимация не обрывалась и полностью проигрывалась при ходьбе и беге ( хоть и наблюдается это в редких случаях).

**Comment by KRodinn** [comment]
Во как, ну теоретически такое возможно, однако когда я смотрел, не натыкался на такое. Мб действительно редко.
Ну мне приходит в голову только `level.disable_input()` делать на время анимации чтоб актор двигаться не мог.
Да и кст, с этими анимациями довольно много мелких проблемок можно найти, типа того что на данный момент ты не определишь, что у актора активация слотов заблокирована (если он на лестнице какой-нибудь например и когда там ещё они блокируются? в машине мб). Это из того что я помню.

**Comment by StereoPunk** [comment]
Нет, обездвиживание актора точно не подойдет, думаю пока оставить как есть. Воспроизвести почему то не получилось данную проблему. А вот с лестницами проблема)) [Видео](https://disk.yandex.ru/i/ddSPZyK5KiqgMQ)

**Comment by StereoPunk** [comment]
P.S На опережение звука не обращаем внимание это у меня ноутбук очень слабый что на динамике 15-25 фпс выдает.

**Comment by artkez** [comment]
Вообще запрет спринта (sprint_allowed = false) решает многие проблемы с "обрывами" анимаций. Например если актор упадёт с маленькой ступеньки в спринте, то анимация обрывается. Я запретил спринт при использовании этих предметов, и у меня нет никаких косяков (ну кроме лестниц конечно).

**Comment by StereoPunk** [comment]
Хмм, а можно твой код глянуть?

сб, 20 февр. 2021 г., 17:39 artkez <notifications@github.com>:

**Comment by StereoPunk** [comment]
> Вообще запрет спринта (sprint_allowed = false) решает многие проблемы с "обрывами" анимаций. Например если актор упадёт с маленькой ступеньки в спринте, то анимация обрывается. Я запретил спринт при использовании этих предметов, и у меня нет никаких косяков (ну кроме лестниц конечно).

А можно на ваш код взглянуть?

**Comment by artkez** [comment]
> А можно на ваш код взглянуть?

Код чего? чтобы запретить спринт, достаточно в секцию предмета прописать 
`sprint_allowed = false`

**Comment by StereoPunk** [comment]
> > А можно на ваш код взглянуть?
> 
> Код чего? чтобы запретить спринт предмету в активном слоте, достаточно в секцию предмета прописать
> `sprint_allowed = false`

Нет, интересен сам принцип работы скрипта посмотреть, потому что я более чем уверен что мой код не особо правильный)

**Comment by Laucer7** [comment]
Да тут несколько вариантов. Еще важно какие у тебя модели, кстати. Можно просто проиграть анимацию через `obj:play_hud_animation( anim_name, mix_in ) `. Ну или можно зациклить на апдейте. У каждого из этих вариантов есть свои преимущества и недостатки.

**Comment by StereoPunk** [comment]
> Да тут несколько вариантов. Еще важно какие у тебя модели, кстати. Можно просто проиграть анимацию через `obj:play_hud_animation( anim_name, mix_in ) `. Ну или можно зациклить на апдейте. У каждого из этих вариантов есть свои преимущества и недостатки.

В моем случае Play_hud_animation не к чему либо я не знаю его плюсы и минусы.

**Comment by Laucer7** [comment]
Тогда просто кидай предмет в слот и активируй его. Когда таймер пройдет - удаляй.
