### ISSUE TITLE
Ошибки рендера

### ISSUE THREAD

**Issue by ArgenteusCorvus** [OGSR/OGSR-Engine#280]
1. Разрешения свыше 1920x1080 не доступно при использовании r3 рендера (DX10 и DX11 режимы).

2. При переключении между полноэкранным и оконным режимом, курсор "запоминает" границы последнего. Управлять пунктами меню приходится через клавиатуру. (Добавить принудительный перезапуск игры?)

**Comment by Xottab-DUTY** [comment]
> Добавить принудительный перезапуск игры?

Не, не нужно, просто исправить нужно захват мыши =)

**Comment by KRodinn** [comment]
Это ж при использовании VSR, я правильно понимаю? С ним у меня так же, да. И я хз что с этим делать.
Монитор fullhd. Выбираешь разрешение 2к допустим - оно меняется, но курсор ограничен. И никакой ClipCursor на это не влияет. Уже сто раз проверял.
Притом, что в оригинальном движке этих проблем нету, чертовщина.
Как обходной вариант - изменить разрешение экрана в самой винде на нужное, тогда работает. Я уже ломал голову над этим с прошлого года, ничего не придумал.

**Comment by ArgenteusCorvus** [comment]
Нет, я не использую VSR. У меня монитор с родным т.н. "2К" разрешением (2560х1440). Я дажеп пробовал прописать его в user.ltx вручную. Движок сбрасывает его до 800х600. На улучшенном r2 такой проблемы нет.

**Comment by KRodinn** [comment]
Ну тогда это ещё более странно. Возможно это тоже как то связано с той проблемой что я описал. На данный момент решения нет. Мб кто то другой тут предложит варианты возможного решения, т.к. те баги что я описал можно воспроизвести на любой системе с поддержкой VSR/DSR.

**Comment by abramcumner** [comment]
> Притом, что в оригинальном движке этих проблем нету, чертовщина.

В оригинальном ЧН точно такие же проблемы. На любом рендере. Такая ерунда из-за кода в UICursor.cpp
void CUICursor::UpdateCursorPosition(). В ней получают положение виндового курсора и переводят в UI-координаты. Виндовый курсор перемещается в пределах десктопа, а движок считает, что в пределах установленного разрешения. Исправление по идее какое-то такое:
```diff
-	vPos.x			= (float)p.x * (UI_BASE_WIDTH/(float)Device.dwWidth);
-	vPos.y			= (float)p.y * (UI_BASE_HEIGHT/(float)Device.dwHeight);
+    int width		= GetSystemMetrics(SM_CXVIRTUALSCREEN);
+    int height		= GetSystemMetrics(SM_CYVIRTUALSCREEN);
+	vPos.x			= (float)p.x * (UI_BASE_WIDTH/(float)width);
+	vPos.y			= (float)p.y * (UI_BASE_HEIGHT/(float)height);
```

**Comment by KRodinn** [comment]
> В оригинальном ЧН точно такие же проблемы.

Странно. Ну ЧН у меня нет, но я точно помню что проверял на старом огсе движке (ещё на каком-то, возможно на ЗП, на твоем xray16 ещё вроде) - тех проблем с курсором на высоких разрешениях не было. Да и у меня в наличии двиг ганслингер мода - на нем тоже всё норм. Я думал это только на огср такая хрень.

Твое исправление проверю потом.

**Comment by joye-ramone** [comment]
> Разрешения свыше 1920x1080 не доступно при использовании r3 рендера (DX10 и DX11 режимы).
у меня 2к монитор. Движок нормально запускается под любым рендером при 2560х1440

**Comment by abramcumner** [comment]
> ещё на каком-то, возможно на ЗП, на твоем xray16 ещё вроде

В ЗП не глючит, там GSC пофиксили.

**Comment by KRodinn** [comment]
@abramcumner бро, ну ты просто господь. Перенес `CUICursor` с твоего движка - всё заработало. Меняю разрешение, перезапускаю игру - и всё норм.

> В ТЧ/ЧН должно глючить.

Вот я почему-то был уверен что раньше в ТЧ работало... В результате как всегда потратил кучу времени в никуда.

**Comment by KRodinn** [comment]
@ArgenteusCorvus ну по первому пункту это возможно локальный глюк какой-то ( я-то изначально подумал что с VSR проблема )
по второму пункту - наверно этот фикс поможет.

**Comment by abramcumner** [comment]
>     1. Разрешения свыше 1920x1080 не доступно при использовании r3 рендера (DX10 и DX11 режимы).

ДиректX-апи почему-то у тебя не выдает разрешения больше 1920х1080. Код там простой, вряд ли в нем есть ошибка. Попробуй обновить драйвера.

Еще есть вариант, что у тебя r3 видит больше одного IDXGIAdapter`а или IDXGIOutput`a. Движок сейчас работает только с первыми экземплярами. Но тут нужно исследовать: или под отладчиком или логировать все подробнее.

> Перенес CUICursor с твоего движка - всё заработало.
Ну это все GSС, я не причем :)
С таким кодом при DSR курсор по идее должен медленней двигаться, нет такого?

**Comment by KRodinn** [comment]
> Это все GSС, я не причем :)

Ну если б не ты, я бы так и не узнал как это фиксится вообще.

> С таким кодом при DSR курсор по идее должен медленней двигаться, нет такого?

Мне наоборот кажется что чуть быстрее.

**Comment by ArgenteusCorvus** [comment]
> Еще есть вариант, что у тебя r3 видит больше одного IDXGIAdapter'а или IDXGIOutput'a. Движок сейчас работает только с первыми экземплярами. Но тут нужно исследовать: или под отладчиком или логировать все подробнее.

Так и есть. Я как-то не посчитал необходимым сообщить, что у меня одновременно с монитором в режиме дублирования экрана подключен телевизор. Отключил - все ок. Движок нашей замечательной игры, не дает корректно отрабатывать несколько дисплеев, даже если они в режиме дубля. Проблема не критичная, но было бы приятно от нее избавиться.

И еще небольшой вопрос по поводу курсора: можно его центрировать? Не очень удобно тащить из угла экрана каждый раз.
