### ISSUE TITLE
Не сохраняется снимок карты

### ISSUE THREAD

**Issue by bigmack2304** [OGSR/OGSR-Engine#298]
В "демо рекорде" при нажатии на f11 создается снимок карты, но он не сохраняется в папке со скриншотами.

**Comment by iceboxfun** [comment]
https://github.com/OGSR/OGSR-Engine/issues/298#issue-833473727

**Comment by KRodinn** [comment]
А на втором рендере работает? Если я не ошибаюсь то это баг DX10/11

**Comment by bigmack2304** [comment]
Кстати да, на втором рендере снимок нормально сохраняется, но теперь вскрылся еще один нюанс, насколько я помню на снимке-же вроде должен быть вид карты с верху, но здесь почему-то заскринился участок на который была направлена камера.
![l08_yantar_ -282 869, -677 750 - 311 291, 138 271](https://user-images.githubusercontent.com/37216622/111816947-fdc51b00-890f-11eb-9bf2-51f30e269962.png)

**Comment by KRodinn** [comment]
Я честно не знаю, никогда не пользовался. Разберусь на днях.

**Comment by KRodinn** [comment]
Ну теперь вроде на DX11 норм работает 
![image](https://user-images.githubusercontent.com/16670637/111865172-7b237680-8976-11eb-8850-026628eaa69b.png)
