### ISSUE TITLE
Partly reload sound

### ISSUE THREAD

**Issue by romanpopulik** [OGSR/OGSR-Engine#300]
> Добавлена возможность указания анимации для не полной перезарядки оружия. Это когда жмакается перезарядка, а оружие не пустое, там еще есть патроны. В худовой секции оружия за это отвечают следующие параметры:
anim_reload_partly ;для оружия без подствольного гранатомета
anim_reload_gl_partly ;для оружия с присоединенным подствольным гранатометом
;При их отсутствии используется значение anim_reload и anim_reload_gl.

This is great feature, but what about sound for partly reload ? I tried to add "snd_reload_partly" but it doesnt work.

**Comment by romanpopulik** [comment]
I just realized that "anim_reload_partly_stop_k" feature works quite good, but using different anim for partly reload is more accurate, especially at the end of the animation

**Comment by KRodinn** [comment]
> what about sound for partly reload ? I tried to add "snd_reload_partly" but it doesnt work.

yes, it needs to be completed, I have already been asked this question ( #286 )

**Comment by KRodinn** [comment]
@romanpopulik test on this version please: https://github.com/OGSR/OGSR-Engine/actions/runs/689481688
