### ISSUE TITLE
HUD ammo icons stretching issue

### ISSUE THREAD

**Issue by donizettilorenzo** [OGSR/OGSR-Engine#301]
widescreen and not widescreen :D

-> https://postimg.cc/BXWWLdqn

Maybe it's time to fix the SoC HUD one and for all (for every aspect ratio, 16:9 / 16:10 and 4.:3)

**Comment by joye-ramone** [comment]
maybe, please start )

**Comment by donizettilorenzo** [comment]
Simple solution: option to remove the ammo icons, let stay only the text ammo description.

**Comment by joye-ramone** [comment]
You can do this via maingame_16.xml file. Just set static_ammo to zero size or move out of screen

**Comment by MrSeyker** [comment]
I've noticed this error before. Curiously, the OGSR engine does allow for more consistent display of the elements between resolutions with this bug.

Copying the 4:3 inventory settings and stretching the width to fix the proportions in 16:9 works fine here  whereas in SOC stretching elements would result in the icon covering the text or being displaced outside of the background box.

**Comment by donizettilorenzo** [comment]
Will test! Thanks!

Il giorno ven 2 apr 2021 alle ore 13:06 MrSeyker ***@***.***>
ha scritto:

**Comment by MrSeyker** [comment]
The icon will still be stretched following my method. Nothing I've tried so far can get the ammo icon to be proportional again in either resolution.

**Comment by NikitaNikson** [comment]
I think, [this](https://github.com/NikitaNikson/OGSR-Engine/commit/6210bb2ea961418ffb3b55e7c2c5fbf78ccfc90f) will help
![ss_nikit_04-06-21_23-24-18_(l01_escape)](https://user-images.githubusercontent.com/58656613/113760269-79580200-972f-11eb-92d4-b47374ba62f5.jpg)
