### ISSUE TITLE
anim_holster_empty bug

### ISSUE THREAD

**Issue by romanpopulik** [OGSR/OGSR-Engine#303]
Mentioned animation doesn't work properly:
https://youtu.be/CPdsi18mkq4

**Comment by KRodinn** [comment]
The engine does not read the animation `anim_holster_empty` at all. When hidding an empty pistol, the animation `anim_close / _r` and the sound `snd_close` are played:
```cpp
void CWeaponPistol::PlayAnimHide()
{
	VERIFY(GetState()==eHiding);
	if(m_opened) 
	{
		PlaySound			(sndClose,get_LastFP());
		CWeaponPistol::WWPMotions& m = wwpm_current();
		m_pHUD->animPlay	(random_anim(m.mhud_close), TRUE, this, GetState());
	} 
	else 
		inherited::PlayAnimHide();
}
```

**Comment by romanpopulik** [comment]
Thanks a lot :-) I simply assigned holster sound to `snd_close` and holster_empty animation to `anim_close` and it works as it should.
