### ISSUE TITLE
"r_sslr_enable" not working as intended?

### ISSUE THREAD

**Issue by donizettilorenzo** [OGSR/OGSR-Engine#307]
SSLR is always enabled for water ponds, no matter the value set.

**Comment by KRodinn** [comment]
SSLR is a reflections on wet pavement, it affects many parts of the render, and therefore there is an option to disable this effect.
Reflections on water are a simpler thing, just a shader effect, so there is no option to turn them off.

**Comment by donizettilorenzo** [comment]
Thanks for the clarification!
