### ISSUE TITLE
Another animations issues

### ISSUE THREAD

**Issue by romanpopulik** [OGSR/OGSR-Engine#308]
I'm working now on AK74. Looks like `anim_holster_g` is not working, the game plays `anim_holster_gl`.

Also, `anim_reload_partly_gl` is not working, the game plays `anim_reload_gl`, but suprisingly proper sound is played (`snd_reload_partly`)

**Comment by KRodinn** [comment]
> Also, anim_reload_partly_gl is not working, the game plays anim_reload_gl

Where did you find this animation name? Correct name: `anim_reload_gl_partly`.

> Looks like anim_holster_g is not working, the game plays anim_holster_gl

Hmm, really. It looks like this is a bug. I can fix this.

**Comment by romanpopulik** [comment]
> Where did you find this animation name? Correct name: `anim_reload_gl_partly`.

Ok, it works now.

**Comment by KRodinn** [comment]
Test [**this version**](https://github.com/OGSR/OGSR-Engine/actions/runs/729358575) please.

**Comment by romanpopulik** [comment]
Yes, it's fixed

**Comment by romanpopulik** [comment]
Another one: anim `anim_shoot_g` doesn't work

**Comment by KRodinn** [comment]
Must work:
```cpp
void CWeaponMagazinedWGrenade::PlayAnimShoot()
{
	VERIFY(GetState()==eFire || GetState()==eFire2);
	if(this->m_bGrenadeMode)
	{
		//анимация стрельбы из подствольника
		m_pHUD->animPlay(random_anim(mhud_shots_g),TRUE,this, GetState());
	}
	else
	{
		if(IsGrenadeLauncherAttached())
			m_pHUD->animPlay(random_anim(mhud_shots_w_gl),TRUE,this, GetState());
		else
			inherited::PlayAnimShoot();
	}
}
```

**Comment by romanpopulik** [comment]
https://youtu.be/9GgCqU5xojw

**Comment by KRodinn** [comment]
`¯\_(ツ)_/¯`

**Comment by romanpopulik** [comment]
I tried vanilla files and engine. `anim_shoot_g` is not played too, but immediately after firing the grenade, the engine plays `anim_reload_g`

**Comment by KRodinn** [comment]
Fixed. Thanks for your report.
