### ISSUE TITLE
патрон в стволе

### ISSUE THREAD

**Issue by i-love-kfc** [OGSR/OGSR-Engine#315]
Предлагаю изменить счетчик патронов так, чтобы при перезарядке учитывался патрон в стволе (как в ганслингере)

Моя реализация:
i-love-kfc@531a2fb

Включается/вырубается строкой cartridge_in_the_barrel в секции оружия.

**Comment by DmitriySolontsevoy** [comment]
Предлагаю расширить это решение также опциональной анимацией перезарядки.
Например если мы недостреляли магазин, то при перезарядке проигрываем краткий вариант анимации (без дёргания затвора) и добавляем патрон в патроннике, а если выстреляли всё, то проигрываем анимацию полной перезарядки и не добавляем патрон

**Comment by poosh** [comment]
Тогда уже нужно неполную перезарядку реализовать - без передёргивания затвора. Иначе патрон в стволе вылетает.

**Comment by DmitriySolontsevoy** [comment]
@poosh Давно реализовано тут, надо добавить параметр в конфиг для анимации частичной перезарядки "anim_reload_partly = [имя анимации]", либо указывать параметр "anim_reload_partly_stop_k", который будет проигрывать для частичной перезарядки только часть оригинальной анимации
