### ISSUE TITLE
Невозможность скомпилировать рендеры на mvs 2019.

### ISSUE THREAD

**Issue by OneMorePseudoCoder** [OGSR/OGSR-Engine#323]
Решил скомпилировать движок из ветки "dev" и заметил, что Visual Studio массово заполняет лог ошибками вроде "Не удалось создать виртуальную память для PCH" и "ограничение компилятора: достигнут предел внутренней кучи". 
Это происходит при попытке скомпилировать рендеры(вручную по одному или полностью всё решение); все остальные dll создаются нормально. Как с этим бороться?

**Comment by Xottab-DUTY** [comment]
Не хватило размера файла подкачки

**Comment by KRodinn** [comment]
64 битный тулчейн надо использовать https://stackoverflow.com/questions/19820718/how-to-make-visual-studio-use-the-native-amd64-toolchain

**Comment by KRodinn** [comment]
Можно в самой винде создать переменную окружения `PreferredToolArchitecture=x64`, тогда всегда будет x64 тулчейн юзаться.

**Comment by KRodinn** [comment]
Так-то можно по дефолту его использование прописать в солюшен, но он компилит немного медленнее, насколько я помню. Хотя мб щас уже это не особо важно.

**Comment by OneMorePseudoCoder** [comment]
Спасибо за советы. Может, вы удивитесь, но помогло мне лишь обновление VS до последней версии. (моя версия устарела 3-4 месяца назад) 
Что-то какая-то странная дичь.
