### ISSUE TITLE
Error in new version №2

### ISSUE THREAD

**Issue by KERIXFIX337X** [OGSR/OGSR-Engine#324]
Опять здравствуйте. На новой версии движка (2.1.204) появились **красные надписи** из оригинального ТЧ при demo_record 1. На пред. версии такого не было.
Скриншот приложил. 

![Скриншот 05-05-2021 104106](https://user-images.githubusercontent.com/77852144/117110424-c4951d00-ad8e-11eb-9faa-c1af1fa936af.jpg)

**Comment by KRodinn** [comment]
Это было бы ошибкой, если бы их не было. Вообще они везде должны быть.

**Comment by joye-ramone** [comment]
Я когда то добавлял параметр
[demo_record]
show_info   = false

**Comment by KRodinn** [comment]
Ну он и щас должен работать вроде
