### ISSUE TITLE
Верните/восстановите рабочий EAX в игру

### ISSUE THREAD

**Issue by Prophet2002** [OGSR/OGSR-Engine#328]
Возможно он есть, но почему-то в консоли пишет что EAX не работает.

**Comment by StereoPunk** [comment]
Рабочий EAX? Он когда то нормально работал?

**Comment by Prophet2002** [comment]
> Рабочий EAX? Он когда то нормально работал?

В дополнениях - да. HRTF и EAX Fixes от macron.

**Comment by Xottab-DUTY** [comment]
> Рабочий EAX? Он когда то нормально работал?

> > Рабочий EAX? Он когда то нормально работал?
> 
> В дополнениях - да. HRTF и EAX Fixes от macron.

Возможно и в оригинальной игре тоже работал, но только с звуковыми картами Creative, которых у многих игроков не было.

**Comment by i-love-kfc** [comment]
Возможно, нашел решение:
https://bitbucket.org/i-love-kfc/xray-oxygen/commits/99f6c60e2d40cb69c8b2e838e912889a5cd3daa2
https://bitbucket.org/i-love-kfc/xray-oxygen/commits/c8a11c4c3f8eac117ca64371352ad08386cf3187

**Comment by KRodinn** [comment]
нет

**Comment by Prophet2002** [comment]
> Возможно, нашел решение:
> https://bitbucket.org/i-love-kfc/xray-oxygen/commits/99f6c60e2d40cb69c8b2e838e912889a5cd3daa2
> https://bitbucket.org/i-love-kfc/xray-oxygen/commits/c8a11c4c3f8eac117ca64371352ad08386cf3187

Но ведь это код xrOxygen...

**Comment by ForserX** [comment]
Тут же EFX есть. Разница?

**Comment by KRodinn** [comment]
Efx был, но прожил тут недолго. Я его выпилил давно, а по какой причине - уже не помню. Что то с ним было не так, походу.

**Comment by Prophet2002** [comment]
> Тут же EFX есть. Разница?

Сами команды/функции остались. Факт в том, что при расстановке зон звуковой физики ничего не меняется.

**Comment by KRodinn** [comment]
А ты звуковое устройство переключи. Они только на OpenAL Soft не работают. На других они работают, но странно.

**Comment by Prophet2002** [comment]
> А ты звуковое устройство переключи. Они только на OpenAL Soft не работают. На других они работают, но странно.

Я уже на других проверял, все равно не работает. Даже если в консоли пишет что EAX present.

**Comment by KRodinn** [comment]
Ну кстати да, щас и у меня не работает. Помню что работал в 2019... странно.

**Comment by KRodinn** [comment]
В общем, весь этот EAX надо переосмыслить как-то в будущем. А пока, учитывая, что тут OpenAL Soft юзается, можно hrtf включить например, да и вообще у него много всяких настроек есть.
https://ap-pro.ru/forums/topic/365-%D0%BD%D0%B0%D1%81%D1%82%D1%80%D0%B0%D0%B8%D0%B2%D0%B0%D0%B5%D0%BC-hrtf-%D0%B4%D0%BB%D1%8F-lost-alpha-%D1%80%D0%B5%D0%B0%D0%BB%D0%B8%D1%81%D1%82%D0%B8%D1%87%D0%BD%D1%8B%D0%B9-3d-%D0%B7%D0%B2%D1%83%D0%BA/

https://www.google.com/search?q=hrtf+stalker&newwindow=1&source=lnms&tbm=vid&sa=X&ved=2ahUKEwipm8zlmefwAhWDmIsKHY8YASYQ_AUoAnoECAEQBA&biw=1469&bih=753

**Comment by Prophet2002** [comment]
> В общем, весь этот EAX надо переосмыслить как-то в будущем. А пока, учитывая, что тут OpenAL Soft юзается, можно hrtf включить например, да и вообще у него много всяких настроек есть.
> https://ap-pro.ru/forums/topic/365-%D0%BD%D0%B0%D1%81%D1%82%D1%80%D0%B0%D0%B8%D0%B2%D0%B0%D0%B5%D0%BC-hrtf-%D0%B4%D0%BB%D1%8F-lost-alpha-%D1%80%D0%B5%D0%B0%D0%BB%D0%B8%D1%81%D1%82%D0%B8%D1%87%D0%BD%D1%8B%D0%B9-3d-%D0%B7%D0%B2%D1%83%D0%BA/
> 
> https://www.google.com/search?q=hrtf+stalker&newwindow=1&source=lnms&tbm=vid&sa=X&ved=2ahUKEwipm8zlmefwAhWDmIsKHY8YASYQ_AUoAnoECAEQBA&biw=1469&bih=753

Спасибо, давно искал подобные документации по этому поводу. Если способ действительно рабочий, то "кусаться" по EAX'у не буду :) Кстати, в Anomaly лучше всего реализована звуковая система, надо попробовать код его движка посмотреть.

**Comment by i-love-kfc** [comment]
Решение:
i-love-kfc@e70f2b9
(На надпись "Запустить не удалось" не обращайте внимание. Я просто тогда забыл переключиться на generic software)

**Comment by KRodinn** [comment]
У меня вот еaх щас снова сам по себе появился, мб потому что я openal переустанавливал ранее, или не знаю почему. Я по прежнему не понимаю, почему он вам нравится. На улице постоянное эхо, а в помещениях наоборот эха нет. Как-то это всё прям странно получается.
