### ISSUE TITLE
Параллакс на террейне 

### ISSUE THREAD

**Issue by Egor179** [OGSR/OGSR-Engine#329]
Один разра... начинающий мододел (Михаил Юдин) поделился шейдером параллакса для террейна, изначально он сделан для ЗП и использует оригинальные текстуры террейна, бампа и т.д. По идеи на ТЧ тоже должен работать
Не могли бы вы его добавить в свой движок?
[misha_parallax.zip](https://github.com/OGSR/OGSR-Engine/files/6517495/misha_parallax.zip)
<img src="https://i2.paste.pics/27760a73750b01b811c1e3824ef31a06.png" alt="Screenshot">
<img src="https://i2.paste.pics/71a5aca58d0e1628bc47fcfc2793c14c.png" alt="Screenshot">
<img src="https://i2.paste.pics/56660f6f4e5bdf460c990eb9445152fb.png" alt="Screenshot">
<img src="https://i2.paste.pics/88265b94bf2c5d58826f4a89273f782b.png" alt="Screenshot">
<img src="https://i2.paste.pics/6ae7f94f833809846e05e121bea027e3.png" alt="Screenshot">

**Comment by KRodinn** [comment]
> Один разработчик (Михаил Юдин)

> # **разработчик**

![image](https://user-images.githubusercontent.com/16670637/119015815-f36fdd80-b9a1-11eb-9b0c-a5e2e153b24e.png)

Ну параллакс для террейна у меня в TODO давно есть, мне и @LVutner свой шейдер скидывал ( [LVutner_parllax.zip](https://github.com/OGSR/OGSR-Engine/files/6517511/LVutner_parllax.zip) ), мне просто лень этим заняться. А вообще надо бы, да.

**Comment by mihan-323** [comment]
Я не разработчик OGSR, неееееет

**Comment by KRodinn** [comment]
![EzqpqkZXIAAXId1](https://user-images.githubusercontent.com/16670637/119032809-4606c500-b9b5-11eb-9977-012b61bd3dd3.png)

**Comment by NikitaNikson** [comment]
> не разработчик

![миша](https://user-images.githubusercontent.com/58656613/119078733-37013080-ba10-11eb-8b10-ece47e765eba.png)

**Comment by KRodinn** [comment]
Шейдер годный кст.
Было:
![](https://cdn.discordapp.com/attachments/822015074997633035/845389323414929458/ss_admin_05-21-21_22-52-54_jupiter.png)
Стало:
![](https://cdn.discordapp.com/attachments/822015074997633035/845389373947379742/ss_admin_05-21-21_22-36-50_jupiter.png)
