### ISSUE TITLE
CTD on updating to 2.1.242

### ISSUE THREAD

**Issue by Schizosaccaromyces** [OGSR/OGSR-Engine#331]
Situation:
-Deleted the bin_X64 folder prior to updating on the installer version of OGSR from the Discord channel (hosted in Yandek.disk)
-Replaced with contents of release build and copied the gamedata folder from release build into OGSR directory. 
Error messages observed and Xray log:
![image](https://user-images.githubusercontent.com/18352984/124358237-4da5c480-dc17-11eb-906d-16dd3a23b7cd.png)
![image](https://user-images.githubusercontent.com/18352984/124358243-54ccd280-dc17-11eb-8dff-8b8ee8d53482.png)
[xray_freya.log](https://github.com/OGSR/OGSR-Engine/files/6758585/xray_freya.log)

**Comment by KRodinn** [comment]
No need to try to manually install any updates. The latest version is in the installer. As soon as there is a new one, the installer will be updated. How soon this will be done - I do not know.

**Comment by Schizosaccaromyces** [comment]
Okay, thank you!
I´ll revert to the original files in that case.
