### ISSUE TITLE
Support CoP-style detectors

### ISSUE THREAD

**Issue by seaz5150** [OGSR/OGSR-Engine#335]
Hello. 

I was thinking about how to get the OGSR detectors working on the new CoP HUD system and when trying to use the CoP detector models directly I noticed that setting the cfg parameter attach_place_idx to 1 (item model is attached to the left hand), the game crashes. Only setting it to 0 (right hand, used for all weapons) works. 

Log file with minidump in the attached archive:
[Log.zip](https://github.com/OGSR/OGSR-Engine/files/6800834/Log.zip)

**Comment by KRodinn** [comment]
The CoP-style detectors have not been supported yet.

**Comment by seaz5150** [comment]
Although if the parameter worked, then perhaps it would be possible to port the existing OGSR ShoC detectors to the new HUD system. Might not be worth the hassle though, all depends on if someone is planning to port the CoP ones.

Nonetheless, this engine is by far the best ShoC has ever seen, thanks to everyone involved in it!

**Comment by seaz5150** [comment]
One more thing: walking animations do not work for double barreled shotguns. Atleast for the STCoP WP weapons.

**Comment by bigmack2304** [comment]
seaz5150. На счет двухстволок из STCoP WP, у меня анимация ходьбы тоже не работала пока не добавил в конфиг в секцию худа... 
`anm_idle_moving         		= bm16_idle_moving`  - для bm16
`anm_idle_moving         		= toz34_idle_moving`  - для toz34

**Comment by seaz5150** [comment]
Oh, I tried that, but I also deleted the other idle_moving sections. Like this it works, thank you.

**Comment by KRodinn** [comment]
WIP
![ss_admin_11-13-21_21-54-47_(l01_escape)](https://user-images.githubusercontent.com/16670637/141655965-d5a327e9-9070-41ea-8418-333363285e25.png)

**Comment by seaz5150** [comment]
Very cool)
