### ISSUE TITLE
Hang on entering Bar 

### ISSUE THREAD

**Issue by Schizosaccaromyces** [OGSR/OGSR-Engine#337]
Reproducible= Yes
Situation= After coming back from Darkscape (X18 documents have already been given to Barkeep), entering the Bar area leads to the game freezing. Multiple CMD windows are opened and closed in the background, the screen goes black. Rest of computer is operating normally (not a hardware issue, no fault detected in Event Monitor)
Log and save attached. The freeze is not registered in the log. Loading the save results in the same behaviour. 
Also attached user.ltx file. Currently on DX11 render. 
[user.zip](https://github.com/OGSR/OGSR-Engine/files/6835946/user.zip)

[logs.zip](https://github.com/OGSR/OGSR-Engine/files/6835942/logs.zip)

**Comment by Schizosaccaromyces** [comment]
Added also save before entering Bar. 
[savedgames.zip](https://github.com/OGSR/OGSR-Engine/files/6835948/savedgames.zip)

**Comment by Schizosaccaromyces** [comment]
Potentially an issue with audio: system was set to Generic Software. Changing the option to OpenAl allows to load into Bar.

**Comment by KRodinn** [comment]
Perhaps you have the wrong version of OpenAL installed on your system
