### ISSUE TITLE
Обновить OPCODE до версии 1.3 и вынести его из xrCDB

### ISSUE THREAD

**Issue by KRodinn** [OGSR/OGSR-Engine#34]

**Comment by ForserX** [comment]
Не повторяйте моих ошибок. Оставьте опкод таким, какой он есть... Это вам ничего не даст, кроме ООП API. Только лишняя трата сил.

**Comment by KRodinn** [comment]
@ForserX Я прост читал, что этот ОДЕ https://bitbucket.org/odedevs/ode/src/default/ требует новые опкоды.
Да и планировал обновить его до той версии, ну в след. году уже наверн ( если к тому времени мне будет не лень )
Соотв. если оде обновлять, то и опкоды обновлять придётся ( но это не точно )

**Comment by KRodinn** [comment]
а пока можно и закрыть, действительно, до лучших времён
