### ISSUE TITLE
Затвор пистолета медленно съезжает назад после полного расстреливания магазина

### ISSUE THREAD

**Issue by DmitriySolontsevoy** [OGSR/OGSR-Engine#344]
При выстреле последним патроном из магазина, пистолет не проигрывает анимации выстрела, а просто бездвижно отображается, после чего затвор из закрытого положения медленно съезжает назад.
Баг воспроизводится для всех пистолетов

Тестировалось на немодифицированной версии.

**Comment by i-love-kfc** [comment]
#345 тут фикс
