### ISSUE TITLE
Скроллбар налезает на слоты в режиме обыска (тайника/трупа)

### ISSUE THREAD

**Issue by DmitriySolontsevoy** [OGSR/OGSR-Engine#348]
Вот так это выглядит:
![bandicam 2021-07-29 19-59-51-190](https://user-images.githubusercontent.com/27158522/127534181-a95866ae-965d-41ff-a7cd-ada6e8e451ba.jpg)

При этом в режимах торговли и осмотра собственного рюкзака этой проблемы не обнаружил.
Тестировалось без модов на разрешении 1920x1080 (монитор 16:9)

**Comment by i-love-kfc** [comment]
Это проблема текстуры инвентаря

**Comment by DmitriySolontsevoy** [comment]
Сомневаюсь, что текстуры, если это и корявится в gamedat'е, то разве что в XML-файлах из последнего релиза, потому что текстуры оригинальные.

**Comment by KRodinn** [comment]
Здесь нету хмл настроек инвентаря в релизах

**Comment by DmitriySolontsevoy** [comment]
Значит тем более проблема не в gamedata или оригинале игры, ибо я ничего не менял в них

**Comment by StereoPunk** [comment]
У скроллбаров вообще странное поведение, их расположение можно настроить лишь увеличением элемента.

**Comment by DmitriySolontsevoy** [comment]
В общем, если займётесь этой задачей, предлагаю ещё починить надоедливую трабл из оригинала, если это возможно.
Это когда предметов очень много (например, как на скрине здесь) и в итоге, доскроллив до конца, последняя строка и половина предпоследней некликабельна вообще (по крайней мере на моём разрешении и соотношении сторон).
Если возьмётесь, могу создать отдельный Issue под это

**Comment by KRodinn** [comment]
это тут пофиксено, надо просто инвентарь правильно настроить.

**Comment by DmitriySolontsevoy** [comment]
И подвинутый скролл тоже можно настроить, про который в шапке написано?

**Comment by KRodinn** [comment]
Насчёт проблем с инвентарём, что например низ инвентаря не кликабелен, я не помню деталей, там надо включить отладку ui (show_wnd_rect) и смотреть разметку инвентаря, там могут быть какие-то проблемы которые решаются его настройкой.
А , во, нашел в старых обсуждениях:
![](https://cdn.discordapp.com/attachments/508530705098342401/621962772648951808/unknown.png)
![](https://cdn.discordapp.com/attachments/508530705098342401/621964349376036874/unknown.png)
![](https://cdn.discordapp.com/attachments/508530705098342401/621964392845541385/unknown.png)
`bag_static` вроде кривой, ему нужно высоты накинуть. Почему так происходит - долго объяснять.

А насчёт скролла - я не помню, может и можно, а может и нет.

**Comment by DmitriySolontsevoy** [comment]
Ладно, я тогда пока оставлю открытым на всякий.
За подсказку с bag_static спасибо, нашёл, смог поправить.

**Comment by DmitriySolontsevoy** [comment]
UPD: исправляется увеличением ширины dragdrop_list_our и dragdrop_list_other в carbody_new(_16).xml. Закрываю.
