### ISSUE TITLE
steep parallax багует?

### ISSUE THREAD

**Issue by JIuBeP** [OGSR/OGSR-Engine#359]
Что случилось, не пойму, текстуры земли, асфальта стали псевдообъемными, частично кусочками тянутся вверх-вниз, вызывая размазню в текстуре, издалека вроде терпимо. Пробую отрубить и steep parallax и детальный ландшафт, перезапускаю, никакой реакции. В чем дело? Год назад такого не было.

**Comment by StereoPunk** [comment]
> Что случилось, не пойму, текстуры земли, асфальта стали псевдообъемными, частично кусочками тянутся вверх-вниз, вызывая размазню в текстуре, издалека вроде терпимо. Пробую отрубить и steep parallax и детальный ландшафт, перезапускаю, никакой реакции. В чем дело? Год назад такого не было.

Карты высот на bump текстурах неправильные

**Comment by JIuBeP** [comment]
Скачал те доп. текстуры, ну отчасти получше стало, но все равно байда по сути, размазывает текстуры вблизи заметно, да еще и не отключается... эх

**Comment by KRodinn** [comment]
Я выкладывал лучшие, что нашел в текстурных паках https://disk.yandex.ru/d/mxAaLzitBltpxg
Я бы рад чтоб кто то сделал лучше, но это походу мало кто умеет

**Comment by JIuBeP** [comment]
Понял, но почему он не отключается на dx 11? Изначально насколько помню parallax работал на кирпичной кладке (в ЧН вроде) и смотрелся там хорошо.

**Comment by KRodinn** [comment]
на террейне он не работал никогда.

**Comment by JIuBeP** [comment]
Знаю, может и к лучшему, подходящие бампы для него не так просто найти, помехи все равно есть. А для объема кирпичной стены работал и в предыдущих версиях движка и смотрится на ней более подходяще.

**Comment by KRodinn** [comment]
Ну на стенах и тп он и щас работает

**Comment by JIuBeP** [comment]
Это да.

**Comment by JIuBeP** [comment]
Еще к текстурам можно добавить исправленные воллмарки от ножа, в ТЧ с ними косяк, когда режешь по металлу, дереву или камню, с расстояния 5-10 метров чернели края. https://dropmefiles.com/7sWn6  
https://imgur.com/a/7DJ5eHh

**Comment by KRodinn** [comment]
Только на файлопомойки заливать не надо, плз. Там файл удалится, и где его искать потом? Можно прямо сюда залить же, исправил.

**Comment by JIuBeP** [comment]
Ок. 7 zip github почему то не поддерживает

**Comment by KRodinn** [comment]
ну не обязательно же 7z использовать

**Comment by JIuBeP** [comment]
Угу
