### ISSUE TITLE
When hitting max weight cursor disappears

### ISSUE THREAD

**Issue by FoTacTix** [OGSR/OGSR-Engine#360]
Hello, using the Steam version and replacing files with the x64 and launching -steam 

Basically playing Vanilla with the OGSR-x64 Engine

Whenever I hit max weight, my cursor disappears and I'm unable to select or do anything at all.  I feel like sometimes I can see it in the lower corner, but still unable to select.

I have to ALT + F4 to close game and re-open and not make the same mistake :)

**Comment by KRodinn** [comment]
can you record a video so I can understand what the problem is?

**Comment by FoTacTix** [comment]
Here you go

You can see the cursor in the lower right corner while I try to move my mouse.  My keyboard becomes unresponsive in game.  I then ALT+F4 to quit and reload the save and make sure not to go over max weight.

https://drive.google.com/file/d/11gq7puEUU4OjkdeBDNK3Ie2ci-9w8yt4/view?usp=sharing

**Comment by KRodinn** [comment]
Okay, make a save before the problem and send me the `.sav` so I can test it in game.

**Comment by FoTacTix** [comment]
[savedgames.zip](https://github.com/OGSR/OGSR-Engine/files/7245825/savedgames.zip)
Here's one where I was last night, just loot the bodies behind

**Comment by FoTacTix** [comment]
Thanks for looking into this!

**Comment by KRodinn** [comment]
Indeed, this is something very strange.

**Comment by Xottab-DUTY** [comment]
@KRodinn, maybe a tutorial about overweight appears and it is moving mouse to the bottom left corner... If I remember correctly, tutorials can do that (for example, end game credits), though, overweight tutorial should not..

**Comment by KRodinn** [comment]
The problem is that the tutorial keeps running over and over again. I'll fix it.
