### ISSUE TITLE
4-5 Artifacts do not repair armor

### ISSUE THREAD

**Issue by FoTacTix** [OGSR/OGSR-Engine#361]
Hello, using the Steam version and replacing files with the x64 and launching -steam

Basically playing Vanilla with the OGSR-x64 Engine

Equipping 4 Battery artifacts and standing in anomaly appears to not repair armor anymore

Only seems to add to 100% rather than 120% with +30x4

![20210926154552_1](https://user-images.githubusercontent.com/1234699/134827085-1e050289-802c-43c9-aecc-8b69b6170a31.jpg)
![20210926154556_1](https://user-images.githubusercontent.com/1234699/134827087-6cb40ab2-a1d6-4c31-8d91-d22b836917e0.jpg)

**Comment by KRodinn** [comment]
The fact is that artifacts only protect the actor, and his suit does not.

**Comment by MrSeyker** [comment]
Can't the behavior be reverted back to the way it worked in SOC, sure, it was a coding bug, but it was also the only legit way to perform field repairs.

**Comment by FoTacTix** [comment]
I'm certainly missing it as I have a few suits that need repair :)

**Comment by DmitriySolontsevoy** [comment]
That is definitely unnecessary. A better solution would be to install a mod for repairs or make one yourself, rather than bringing back this bugged behavior.

**Comment by MrSeyker** [comment]
Just make it a toggle option in the config. People have been using this trick for ages.

I do use repair mods (have mechanics installed and carry repair kits). And I still use the trick when needed.

Its a cool engine quirk.

**Comment by AffectedOne** [comment]
> Just make it a toggle option in the config. People have been using this trick for ages. It's a way to fix your suit that is in the game and doesn't require any third party modifications.
> 
> I do personally use repair mods (have mechanics installed and carry repair kits). And I still use the trick when needed (mechanics are either too far away or kits are scarce).
> 
> Its a cool engine quirk.

If you need it so bad, download source code and make it yourself. Its honestly beyond me, why would developer want to reintroduce a bug? :D And whats so "legit" about using bug to repair armor? Its up for contributors, but i can't see a point wasting time, when there is more serious stuff that could be fixed or introduced. Especially when there is repair kit, trader repair dialog and probably more mods for fixing equipment in a much more realistic way.

**Comment by KRodinn** [comment]
I didn't even know before that anomalies could repair armor. But if it was so - it is not correct in any case.
