### ISSUE TITLE
Статик иконок патронов в одну ячейку смещён влево

### ISSUE THREAD

**Issue by DmitriySolontsevoy** [OGSR/OGSR-Engine#362]
Связано с этим багом: https://github.com/OGSR/OGSR-Engine/issues/301
Тестил на последнем релизе. Иконки на две ячейки теперь отображаются правильно, а вот те, что в одну ячейку, теперь улетают куда-то влево.

Вот двойная иконка:
![ss_dima_09-13-21_08-21-49_(garbage_old)](https://user-images.githubusercontent.com/27158522/135728977-9e478d12-fdc9-41a7-9172-73f9588c4b41.jpg)

А вот одинарная:
![ss_dima_10-02-21_20-36-13_(l01_escape)](https://user-images.githubusercontent.com/27158522/135728926-982374d9-873a-4a71-9955-0c54a326155d.jpg)

**Comment by KRodinn** [comment]
Ну это к @NikitaNikson

**Comment by NikitaNikson** [comment]
@DmitriySolontsevoy проверь на [этом](https://drive.google.com/file/d/1OD8CsfwRhuHp-77bX-5XfKs-0g2Eubsu/view?usp=sharing)

**Comment by DmitriySolontsevoy** [comment]
@NikitaNikson проверил, начинал новую игру, такое же поведение у иконок, как описано выше

**Comment by NikitaNikson** [comment]
Понял, сейчас тогда по-другому сделаем

**Comment by NikitaNikson** [comment]
@DmitriySolontsevoy твоя проблема фиксится в maingame (_16).xml 

Либо в `static_ammo`, либо в `static_wpn_icon`

У меня в моде несколько худов доступон. На некоторых иконка патронов сдвинута:
![ss_nikit_10-04-21_17-46-38_(lm02_poorpeople)](https://user-images.githubusercontent.com/58656613/135854228-fff44f27-da8d-4455-98c2-7337e2369444.jpg)
![ss_nikit_10-04-21_17-46-32_(lm02_poorpeople)](https://user-images.githubusercontent.com/58656613/135854236-1c83f60b-1457-405c-8193-afbb08f448c6.jpg)

**Comment by DmitriySolontsevoy** [comment]
@NikitaNikson В моём случае худ один единственный, под стать оригиналу (статик о котором идёт речь - static_wpn_icon). Как я пофиксаю общую иконку? Если я сдвину одиночную вправо, то сдвинутся двойные и будут налезать на статик кол-ва патронов

**Comment by NikitaNikson** [comment]
Восстановил ТЧшный код для иконки. Попробуй сейчас:
[bin_05.10.21.zip](https://github.com/OGSR/OGSR-Engine/files/7286298/bin_05.10.21.zip)

 (если архив не будет работать, измени формат на _.rar_)

**Comment by DmitriySolontsevoy** [comment]
Проверил - иконки так же смещены, но теперь все более растянуты вширь. 
Запустил чистую игру без модов и OGSR, чтобы освежить в памяти, как оно выглядело в ориге. Оказывается, что там одинарные иконки тоже были смещены (хотя почему-то не так сильно, как это выглядит сейчас у меня в моде на OGSR). Но я кое-что проверил и это странно: если выставлять такое разрешение, что соотношение сторон 4:3 - то оба вида иконок появляются в одинаковом месте, а если выбирать любое другое соотношение сторон - то иконка улетает влево. Может движок как-то неправильно строит худ для таких соотношений сторон?

**Comment by NikitaNikson** [comment]
Может ты просто не адаптировал худ под 16:9?

**Comment by DmitriySolontsevoy** [comment]
@NikitaNikson Как раз-таки только его я и адаптировал. В XML-ке под эту иконку один единственный статик, если бы их было два, тогда в этом был бы смысл

**Comment by DmitriySolontsevoy** [comment]
Вот как выглядят rect'ы иконок в обоих случаях. Границы не расширяются в одну сторону, прямоугольник улетает полностью
![ss_dima_10-06-21_23-12-39_(l01_escape)](https://user-images.githubusercontent.com/27158522/136276383-9b742495-01d0-43ea-96cc-7357eeeff25f.jpg)
![ss_dima_10-06-21_23-12-36_(l01_escape)](https://user-images.githubusercontent.com/27158522/136276388-7167d4a4-345a-49f3-896e-b7ed9b218676.jpg)

**Comment by KRodinn** [comment]
Судя по скринам, это надо фиксить как-то в движке, а не где либо ещё

**Comment by xrModder** [comment]
Это исправляется в `UIMainIngameWnd.cpp`.

В оригинале:
```
	float w = ((iGridWidth>2)?1.6f:iGridWidth)*INV_GRID_WIDTH*0.9f;
	float h = INV_GRID_HEIGHT*0.9f;//1 cell

	float x = UIWeaponIcon_rect.x1;
	if	(iGridWidth<2)
		x	+= ( UIWeaponIcon_rect.width() - w) / 2.0f;
```

Для корректного отображения иконки боеприпаса код изменить на:
```
	float w = ((iGridWidth > 1) ? iGridWidth : 1) * INV_GRID_WIDTH;
	float h = INV_GRID_HEIGHT;//1 cell
	w *= UI()->get_current_kx();

	float x = UIWeaponIcon_rect.x1;
	if	(iGridWidth<2)
		x	+= w / 2.0f;
```

**Comment by KRodinn** [comment]
@xrModder неплохо
![ss_admin_11-01-21_10-46-56_(l11_pripyat)](https://user-images.githubusercontent.com/16670637/139642844-510d55b8-0aa1-468c-ad0f-7121d26464be.png)
![ss_admin_11-01-21_10-46-59_(l11_pripyat)](https://user-images.githubusercontent.com/16670637/139642877-f2c4c6e7-f8ad-40da-8d45-fad8d9b67f33.png)

**Comment by xrModder** [comment]
Для исправления вращения стрелки цели по овалу на миникарте в строке 425 файла `xrGame\map_location.cpp` изменить код:
```cpp
m_position_on_map		= map->ConvertRealToLocal(position, false);
```
На:
```cpp
m_position_on_map		= map->ConvertRealToLocal(position, true);
```
