### ISSUE TITLE
Crash after stadium cutscene

### ISSUE THREAD

**Issue by FoTacTix** [OGSR/OGSR-Engine#367]
Hello, using the Steam version and replacing files with the x64 and launching -steam

Basically playing Vanilla with the OGSR-x64 Engine

I was able to play through the entire game to this point without issues. (other than the artifact and weight bug)

I get to the stadium, the cutscene plays, then it loads my character briefly and then crashes.  One single time it loaded what sounded like the NPP, but the screen was black and then crashed.  I could hear helicopters and military radio.

Thank you for your hard work

Attached are crash on load, save file, and video
https://drive.google.com/file/d/1__IPNlkxmIxMYm8bsm5XBQV_ZLg_B3Mb/view?usp=shari
![crash01](https://user-images.githubusercontent.com/1234699/135945030-ddd641c7-7a63-410d-a969-4adb37fcd372.png)
[savedgames.zip](https://github.com/OGSR/OGSR-Engine/files/7282106/savedgames.zip)
ng

**Comment by KRodinn** [comment]
You have something very strange.
I normally switched from your preservation to the Chernobyl nuclear power plant.
Could there be a problem with your graphics drivers?
Send me your log after the error and `user.ltx`.
I can advise you to lower the graphics settings, switch to another render (dx9, 10, 11)

**Comment by FoTacTix** [comment]
[xray_motherfo.log](https://github.com/OGSR/OGSR-Engine/files/7288037/xray_motherfo.log
[user.zip](https://github.com/OGSR/OGSR-Engine/files/7288042/user.zip)
)

Are you having to fight through the stadium, or just loading past it?

running Nvidia 471.96 - I'll try lowering settings and see what happens tonight.  I'll try upgrading drivers if that doesnt work as well.

Thanks again for fast responses.

**Comment by FoTacTix** [comment]
Tried latest Nvidia drivers and other render settings and lowering settings as well.  I also tried going through the hole in the fence and through the stadium.  It gets to 88% loading NPP and crashes.  I only got through to NPP that single time and everything was black and then it crashed.

Let me know what else you need

**Comment by FoTacTix** [comment]
Thank you both - looks like I was 1 build behind.  Updating to 2.1.293 solved things for me.  Made it through to the NPP. Thanks again and sorry I didnt catch that
