### ISSUE TITLE
Проблема с ЗП-худом с ветки "gunsxray"

### ISSUE THREAD

**Issue by OneMorePseudoCoder** [OGSR/OGSR-Engine#384]
Скачал и скомпилил движок с "gunsxray" и заметил такую проблему: при попытке добавить новый ствол на ЗП-худе происходит вылет при попытке взять его в руки. 
ЛОГ:

FATAL ERROR

[error]Expression    : FATAL ERROR
[error]Function      : player_hud_motion_container::load
[error]File          : D:\!orig\OGSR-Engine-gunsxray\ogsr_engine\xrGame\player_hud.cpp
[error]Line          : 118
[error]Description   : [player_hud_motion_container::load] motion [p90_draw](anm_show) not found in section [wpn_p90_hud]

Все остальные стволы уже переведены на ЗП-систему, но почему-то игра не хочет переваривать именно этот ствол (модель из ЧН из OGSM CM). При этом все нужные параметры прописаны в секции и её худе. Да и сама анимация есть и она работает. Вообще, мне кажется это из-за коммита "оптимизированный поиск анимаций" или с "Рефакторинг PlayHUDMotion".
Кто чем может помочь?

**Comment by I-AmDead** [comment]
Ну судя по логу у тебя нету анимаци. Да и вообще зачем тебе движок предназначенный для работы ганслингера?

**Comment by I-AmDead** [comment]
Ты можешь просто взять последнюю релмзнубю версию

**Comment by KRodinn** [comment]
Стабильная версия - только в релизах. Всё остальное может быть нерабочее, нестабильное и тп.

**Comment by OneMorePseudoCoder** [comment]
Просто к сведенью: правка "оптимизированный поиск анимаций" работает. У меня просто .omf файл побился при компиляции. Но вот что заметил: коммит "мелочи" (где shared_string сменили на char в player_hud.cpp) ломает анимки у меня. После анимации доставания делать ничего нельзя сделать, даже обратно спрятать. Может, на стволах из ганса как-то иначе проявляется, но обычные ЗП стволы виснут. Ещё вопрос: вы собираетесь в будущем gunsxray в мастер бранч впихивать или как отдельный бранч будет висеть?

**Comment by I-AmDead** [comment]
> 

Такое возникает если неправильно прописана анимация, я на сборке движка помимо ганслингера еще тестировал STCOP 3.4 - все прекрасно работает.
