### ISSUE TITLE
Опять про детекторы

### ISSUE THREAD

**Issue by bigmack2304** [OGSR/OGSR-Engine#396]
Заметил такой баг. Во время отыгрывания анимации доставания детектора можно достать и оружие из второго слота. 
![ss_ПК_01-10-22_11-32-03_(l13_marsh)](https://user-images.githubusercontent.com/37216622/148719261-9aca5973-e3e5-43b1-9917-81ffb72a93f6.png)
И еще, не знаю можно-ли назвать это багом, но объекты на дисплее детектора могут поворачиваться не только по горизонтальной оси но еще и по вертикальной. Видос(https://disk.yandex.ru/d/VecM_ZPjdci6hw)

**Comment by KRodinn** [comment]
> объекты на дисплее детектора могут поворачиваться не только по горизонтальной оси но еще и по вертикальной.

Это норма

>  Во время отыгрывания анимации доставания детектора можно достать и оружие из второго слота.

Кек, прикольно

**Comment by Xottab-DUTY** [comment]
Калаш в одну руку... Калаш в другую руку 😎

**Comment by KRodinn** [comment]
на самом деле я не собирался его фиксить, потому что баг прикольный

**Comment by bigmack2304** [comment]
Нашел еще один глюк, если стоя не двигаясь с детектором и пистолетом,выкинуть пест то рука держащая его не убирается. Выглядит это как-то так.
![ss_pc_02-15-22_19-35-39_(l13_marsh)](https://user-images.githubusercontent.com/37216622/154212632-1297b187-1b7b-436b-bdbd-84fd41d3962c.png)
У себя смог так решить эту проблему. https://github.com/bigmack2304/OGSR-Engine-01/commit/710682cf2d1c0a9d933c36ccdbac9046655c59d1

**Comment by KRodinn** [comment]
В приватном репо этомуже исправлено

**Comment by stalkerrrrrok** [comment]
не могу добавить детекторы на чистый тч с огср движком @xrKrodin  выдает 358 ошибку Cant open sections  'hud_base'

**Comment by stalkerrrrrok** [comment]
@xrKrodin  если можешь,то расскажи как перенести детекторы на огср движок
