### ISSUE TITLE
2.1.359 - желтый лог на чистой игре

### ISSUE THREAD

**Issue by Darkkys** [OGSR/OGSR-Engine#402]
Чистая игра - вот так в логе (на скрине - с огсм, но без него так же)
![S T A L K E R   Call of Pripyat Screenshot 2022 01 19 - 15 48 19 83](https://user-images.githubusercontent.com/97330663/150104897-bbd2b750-b533-437d-b9e3-3f253c4ec7e8.png)

**Comment by KRodinn** [comment]
Забыл убрать лог, ничего страшного тут нету.
