### ISSUE TITLE
Возможные ошибки с `level.change_level`

### ISSUE THREAD

**Issue by Graff46** [OGSR/OGSR-Engine#406]
Если перед вызовом `level.change_level` выполнить спавн некоторого количества объектов, то получите вылет. Было выявлено, что вылеты вызваны именно спавном объектов непосредственно перед `level.change_level`.
Возможно и другие манипуляции с объектами могут отрицательно повлиять на `level.change_level` (перевод в оффлайн/онлайн, удаление).
Предлагаю в `level.change_level` добавить проверки на отсутствие объектов в очередях на обработку сервером.

**Comment by Heleger** [comment]
Здравствуйте, знаю не по теме, но мне нужна помощь я не могу начать играть из-за этой проблемы, как мне её решить? 
Переустановка игры не помогла
![image](https://user-images.githubusercontent.com/104392030/165165978-c65998c3-d40e-47d9-86a4-4a9aa97828ba.png)

**Comment by I-AmDead** [comment]
OpenAl установи...

**Comment by stalkerrrrrok** [comment]
ребята добавил детекторы и ловлю вылет.Ошибка 371 Can't find variable radius [detector_sipmle]

**Comment by joye-ramone** [comment]
@Graff46 в недавно выложенном движке не повторяется вроде б. Там были какие то правки про очередь спауна
Ну и если вылетает приложи лог хотя б полный.
