### ISSUE TITLE
Простой детектор артефактов

### ISSUE THREAD

**Issue by En-framed** [OGSR/OGSR-Engine#412]
Детекторы на классе DET_SIMP выдают ошибку:
[error]Expression    : assertion failed
[error]Function      : CUIArtefactDetectorSimple::setup_internals
[error]File          : d:\a\ogsr-engine\ogsr-engine\ogsr_engine\xrgame\simpledetector.cpp
[error]Line          : 140
[error]Description   : m_pOnOfLAnim = LALib.FindItem("det_on_off")

Меняю на другой класс, например DET_ADVA. Хотя бы работает, как он

**Comment by KRodinn** [comment]
нету "det_on_off" в `lanims.xr`.
