### ISSUE TITLE
ЗП вооружение

### ISSUE THREAD

**Issue by Drakoha4** [OGSR/OGSR-Engine#414]
Я тут полазил почитал логи, как я понял я могу поставить или перенести вооружение с ЗП, но когда я у себя все сделать то у меня не выходит и в логе ошибки одресуют меня на device, x_ray т.е на xrcore, xrgeme и т.к, либо я кривой все неправильно сделал, либо я кривой что не правильно понял ченж логи разротчика, подскажите можно ли адаптировать, если да то с чем мне нужно взаимодейвовать при переносе?

**Comment by Laucer7** [comment]
Добрый день, оружие из ЗП работает просто копипастом секции худа, переносом модели оружия и вводом анимаций. Чтобы начать работать с ЗП худом - для начала надо перенести перчатки на подобие как в ЗП. То есть прописать в actor.ltx секции перчаток и попрописывать их затем в бронники. Второй этап это копия анимаций рук из ЗП, необходимо перенести все анимации без исключений, начиная от оружия и заканчивая биноклем и детекторами. Они, зачастую, сопровождаются препиской hand_ и имеют формат .omf. Вот собственно все. Потом можно переносить пушки, модели, а omf editor'ом, например, вводить анимации рук.

**Comment by Drakoha4** [comment]
Так в том то и дело что я все выше перечисленное сделал, но когда я перекидываю всё вооружение, то только тогда вылет а если оставляют ± 5 стволов то без вылетов

**Comment by Laucer7** [comment]
То есть если заменено пять стволов, то работает исправно, а если все разом, то - нет? Скорее всего тут надо смотреть логи и разбираться, ибо причин может быть полно. Забыл добавить анимации, не хватает звуков или анимаций в конфиге или неправильные партиклы. Надо смотреть лог.

**Comment by Drakoha4** [comment]
Так в том то и дело что в логе меня отсылают на dll библиотеки xrEngine, а в строке где должна быть ошибка пусто

**Comment by stalkerrrrrok** [comment]
а что насчёт детекторов? ловлю вылет когда пытаюсь перенести, 358 ошибка пишет Cant open section 'base_hud'

**Comment by stalkerrrrrok** [comment]
@Laucer7  помоги пожалуйста с детекторами

**Comment by Drakoha4** [comment]
@stalkerrrrrok Так у тебя не хватает секции base_hud, точно не помню где находится, либо в папке configs/misc и в каком-то из файлов либо в файле configs/defines.ltx
