### ISSUE TITLE
Можно стрелять через стены

### ISSUE THREAD

**Issue by Drakoha4** [OGSR/OGSR-Engine#416]
Вообщем, решил я преукрасить локации взял локу из аномали, удали 2 файла это аи сетка и что то там отвяеющее за партикли на локе, так как на тч совсем другая версия и огср ругается, так вот после переноса я заметил что во время игры нпс видят тебя через стены так и ещё стреляют с другого края карты когда тебя увидят чере стены пол, и вся проблемо в том что всех стен и обекто как будто для пуль не существует они летят через все препятствия спокой, так и гг модет стрелять, подскажите в чем проблема?

**Comment by I-AmDead** [comment]
Ага, очень интересно но ничего не понятно...

**Comment by Drakoha4** [comment]
@I-AmDead крч, для пуль нет преград, стрелять можно через любые объекты

**Comment by I-AmDead** [comment]
@Drakoha4 Ну так настрой материалы, зачем по всяким мелочам сюда всегда писать? Справочное бюро?
