### ISSUE TITLE
Artifacts not spawning in Garbage and other places.

### ISSUE THREAD

**Issue by kremuwakarz** [OGSR/OGSR-Engine#446]
Missing Artifacts in Garbage.

There is other stuff missing like there's is no controller in the Yantar lab
and anomalies in the building behind where Mole stands at Agroprom

Not using any mods, just vanilla so I'm guessing that there is something wrong with the way how OGSR loads levels...

**Comment by xrSimpodin** [comment]
fixed in https://github.com/OGSR/OGSR-Engine/commit/534faa4263a1cbdc2a2f8c46312a9c619ccd594b
