### ISSUE TITLE
Раны исчезают за 10 секунд 

### ISSUE THREAD

**Issue by Erken22** [OGSR/OGSR-Engine#449]
Раны на телах (Блудмарки) исчезают слишком быстро, нельзя ли увеличит продолжительность присутствия ран или полностью отключить исчезновение ран ?

**Comment by xrSimpodin** [comment]
Время регулируется командой `r__wallmark_ttl`

**Comment by Erken22** [comment]
> Время регулируется командой `r__wallmark_ttl`

Спасибо за подсказку, увеличил время до десяти минут, вроде как это максимально доступное значение для декалей. Можно ли еще как то включить   проигрывание интро и заставок во время запуска игры, просто в ogsr они отключены ?

**Comment by xrSimpodin** [comment]
ключ `-intro` к ярлыку
