### ISSUE TITLE
Мышка перестает работать при перегрузе персонажа

### ISSUE THREAD

**Issue by Erken22** [OGSR/OGSR-Engine#450]
Мышка перестает работать при появлений сообщения "вы не грузовик и не можете нести много груза" если в этот момент нажать кнопку esc то перестают работать все кнопки и приходится нажать alt+f4 чтобы закрыть игру полностью

**Comment by joye-ramone** [comment]
это не движок делает. все эти вещи - скриптовые

**Comment by xrSimpodin** [comment]
Щас глянул в OGSR:GA - тут такой проблемы нет
