### ISSUE TITLE
Наловил вылетов на чистом ТЧ.

### ISSUE THREAD

**Issue by 7dot9** [OGSR/OGSR-Engine#454]
Потестировал последний (2.1.407) релиз.
Наловил (немного) вылетов на чистом (только! db-файлы) ТЧ1006.
Помогите сориентироваться где проблемы.
В архиве логи и сейв.

[logs.zip](https://github.com/OGSR/OGSR-Engine/files/11215391/logs.zip)

**Comment by joye-ramone** [comment]
там 40 лог файлов и в каждом своя проблема. 
с этим разбиратся неделю надо

**Comment by 7dot9** [comment]
Да я и не спешу... :)
Внешне проявление одинаковое было: фриз, картинка стоит, рабочий стол.
Места всегда разные и никогда не повторялись - с местом не связано.
На компе RAM=4GB.

**Comment by joye-ramone** [comment]
я к тому что этим никто заниматся не будет. 100% проблемы gamedata так как в двух других больших модад с движком проблем нету

**Comment by 7dot9** [comment]
Gamedata из релиза OGSR-eng, db-файлы из релиза ТЧ10006, больше ничего...
Ладно, понятно...
