### ISSUE TITLE
Chance for integration of ZRP?

### ISSUE THREAD

**Issue by Blackgrowl** [OGSR/OGSR-Engine#457]
Hey there, I was going to play a "vanilla-ish" version of ShoC until I found out about this, this is a great engine itself and knowing it takes some features from Anomaly and a friend I know called Tab (He made Screen Space Shaders) makes it better.

I was wondering though, it seems that the engine, sadly, is not compatible with ZPR by default, it will keep crashing with some logs no matter what.

For context, ZRP means "Zone Reclamation Project", it's just a fancy title for a mod that only does bug fixes, QoL changes and the like.
Most changes are simple, but some are very complex, like allowing AI to throw grenades.

From the list of changes that I've seen and the fact it can be configured itself, I believe it being integrated into OGSR Engine itself would be worth it.

So I was wondering, is there any chance to officially integrate ZRP, be it partly, fully or even redone?

**Comment by I-AmDead** [comment]
officially integrate? therefore, the reason for the author of the mod
