### ISSUE TITLE
AMD FidelityFX Super Resolution 2.0

### ISSUE THREAD

**Issue by xrAbstraction** [OGSR/OGSR-Engine#467]
Добрый день. Недавно заметил, что на просторах моддинга X-Ray один очень популярный проект анонсировал поддержку FSR 2.0 и DLSS 3.5. Также они опубликовали скриншоты с данной технологией. Вопрос заключается в том, будете ли вы добавлять эту технологию или будете использовать технологии сглаживания, придуманные ящерами (такие как SMAA, FXAA и другие)? Было бы интересно узнать ваше мнение.
![WITH_FSR](https://github.com/OGSR/OGSR-Engine/assets/151672711/47c690c3-2f37-48f4-a275-7e631b670b2a)
![WITHOUT_FSR2](https://github.com/OGSR/OGSR-Engine/assets/151672711/565b8a7a-75aa-4f56-aa32-46f654b78c7b)

**Comment by xrSimpodin** [comment]
> один очень популярный проект анонсировал поддержку FSR 2.0 и DLSS 3.5

А я анонсирую PBR в OGSR:GA к новому году. Нужно чтобы кто то пошел к разработчикам популярного проекта и напомнил, что там тоже необходимо внедрить PBR, а то не солидно ведь.

> Также они опубликовали скриншоты с данной технологией

Я вижу два одинаковых скрина в шакальном качестве и с убогой графикой. Никаких высоких технологий на этих скринах не видно, я бы постыдился показывать такое вообще. Ну ладно.

А теперь давайте посмотрим к примеру на эти скрины:
![image](https://github.com/OGSR/OGSR-Engine/assets/16670637/1c5e9c4a-5f28-4df4-80e9-2497ff50dffc)
![image](https://github.com/OGSR/OGSR-Engine/assets/16670637/1f5477f2-1e13-4e34-8661-bdac6938d687)
![image](https://github.com/OGSR/OGSR-Engine/assets/16670637/896b9f1c-8142-4cc6-8731-64cc1b51574c)
Вы здесь проблемы со сглаживанием видите? Что нам ваш FSR/DLSS даст кроме переделки половины рендера/шейдеров, разгребанием тонны багов ставших следствием этих переделок, и полной несовместимости со всеми шейдерными модами после этих переделок?
В этом внедрении FSR/DLSS нет ничего кроме понтов и бессмысленного сизифового труда. У меня всё.

**Comment by VaIeroK** [comment]
АХАХАХАХАХАХАХАХХАХАХАХАХХА графика как в тч модах на дх9 с ретекстуром от "Пупсик1234"

**Comment by xrAbstraction** [comment]
Раз вы говорите, что для вас данные скриншоты слишком мыльноваты и шакальны - вот вам в полном качестве, без сжатия. Так как вы опубликовали скриншоты с огромным кол-во блюма, тонмаппинга и других современных технологий, команде пришлось сильно обновить движко чтобы поддерживать данный пост-процессинг.
![WITHOUT_FSR2](https://github.com/OGSR/OGSR-Engine/assets/151672711/90415a4a-fd2e-4a64-a6ce-a0d0584bec65)
![WITH_FSR2](https://github.com/OGSR/OGSR-Engine/assets/151672711/db929433-e446-43b6-9546-bc60ca882bd2)

**Comment by Kurzdor** [comment]
Pull requests всегда открыты.

Но пересветили картинку - молодцы.

**Comment by xrSimpodin** [comment]
На этих скринах кроме volumetric light который и так всегда был в ЗП, ничего особенного нет.
Ещё раз, я выше задал вопрос, что нам в OGSR дадут эти ваши высочайшие технологии, и перечислил все минусы. Вы на это что нибудь толковое возразите лучше.
А присылать мне скрины с очень популярного проекта не надо, мне на них смотреть не интересно.

**Comment by xxrLil-Batya** [comment]
Уродин, ну чё ты на правду обижаешься, и просто удаляешь сообщения, как девочка?
Тебя валера просто по факту разъебал нахуй, в огср графика хуже чем в тч на статике. И то, что ты спиздил SSS и другие фичи из других движков, это ещё ни хуя не означает.

Флажки власовские выкладывать перестань, иначе будешь на бутылке сидеть.
Когда уже весь компромат на нас из синей папки будет выложен? Я знаю, что ты пытаешься нас "задеанонить", вычислить по айпи, и делаешь другую хуйню, которой мне угрожали ещё хуй знает сколько лет назад, когда я ещё в начальной школе был.
Лучше промывай дальше мозги своим подсосам, это единственное, что у тебя получается хорошо, на большее ты не способен, лох ебаный.

P.S. твою богиню уже выебали до тебя :)

**Comment by Krodin-daun** [comment]
Ну чо ты так легко слился-то? Высри что-нибудь, вместо того чтобы просто сообщения чистить. Или в лс пошли в дискорд, если так не хочешь позориться.
