### ISSUE TITLE
The anm_open_empty animation doesn't seem to play properly.

### ISSUE THREAD

**Issue by starlight1943ld** [OGSR/OGSR-Engine#480]
Even if there are no bullets left in the weapon, the anm_open_empty animation doesn't trigger properly and will only play in the order of anm_open to anm_add_cartridge_empty.

**Comment by xrSimpodin** [comment]
There is no `anm_open_empty` animation in this engine at all.

For gunslinger-style shotguns, we support the following set of animations (they don’t need `anm_open*` animations at all):
```ini
[wpn_wincheaster1300]
is_gunslinger_weapon = true
hud = wpn_wincheaster1300_hud

[wpn_wincheaster1300_hud]
;добавление патрона
anm_add_cartridge			    = winchester1300_pistol_reload_ammo, winchester1300_reload_ammo
anm_add_cartridge_start			    = winchester1300_pistol_reload_start, winchester1300_reload_start
lock_time_end_anm_add_cartridge_start = 0.1
anm_add_cartridge_empty			    = winchester1300_pistol_reload_empty_start, winchester1300_reload_empty_start
lock_time_end_anm_add_cartridge_empty = 0.1
anm_add_cartridge_second		    = winchester1300_pistol_reload_empty_second_ammo, winchester1300_reload_empty_second_ammo

;конец релоада
anm_close			                = winchester1300_pistol_reload_end, winchester1300_reload_end
anm_close_empty			            = winchester1300_pistol_reload_empty_end, winchester1300_reload_end

;расклин
anm_reload_jammed			= winchester1300_pistol_revival, winchester1300_revival
anm_reload_jammed_last		= winchester1300_pistol_revival, winchester1300_revival
```

**Comment by starlight1943ld** [comment]
I made an attempt, but the non-loading animations anm_add_cartridge_start and anm_add_cartridge_empty also cause the number of rounds in the chamber to increase by one, is there a solution for this?

> There is no `anm_open_empty` animation in this engine at all.
> 
> For gunslinger-style shotguns, we support the following set of animations (they don’t need `anm_open*` animations at all):
> 
> ```ini
> [wpn_wincheaster1300]
> is_gunslinger_weapon = true
> hud = wpn_wincheaster1300_hud
> 
> [wpn_wincheaster1300_hud]
> ;добавление патрона
> anm_add_cartridge			    = winchester1300_pistol_reload_ammo, winchester1300_reload_ammo
> anm_add_cartridge_start			    = winchester1300_pistol_reload_start, winchester1300_reload_start
> lock_time_end_anm_add_cartridge_start = 0.1
> anm_add_cartridge_empty			    = winchester1300_pistol_reload_empty_start, winchester1300_reload_empty_start
> lock_time_end_anm_add_cartridge_empty = 0.1
> anm_add_cartridge_second		    = winchester1300_pistol_reload_empty_second_ammo, winchester1300_reload_empty_second_ammo
> 
> ;конец релоада
> anm_close			                = winchester1300_pistol_reload_end, winchester1300_reload_end
> anm_close_empty			            = winchester1300_pistol_reload_empty_end, winchester1300_reload_end
> 
> ;расклин
> anm_reload_jammed			= winchester1300_pistol_revival, winchester1300_revival
> anm_reload_jammed_last		= winchester1300_pistol_revival, winchester1300_revival
> ```



> There is no `anm_open_empty` animation in this engine at all.
> 
> For gunslinger-style shotguns, we support the following set of animations (they don’t need `anm_open*` animations at all):
> 
> ```ini
> [wpn_wincheaster1300]
> is_gunslinger_weapon = true
> hud = wpn_wincheaster1300_hud
> 
> [wpn_wincheaster1300_hud]
> ;добавление патрона
> anm_add_cartridge			    = winchester1300_pistol_reload_ammo, winchester1300_reload_ammo
> anm_add_cartridge_start			    = winchester1300_pistol_reload_start, winchester1300_reload_start
> lock_time_end_anm_add_cartridge_start = 0.1
> anm_add_cartridge_empty			    = winchester1300_pistol_reload_empty_start, winchester1300_reload_empty_start
> lock_time_end_anm_add_cartridge_empty = 0.1
> anm_add_cartridge_second		    = winchester1300_pistol_reload_empty_second_ammo, winchester1300_reload_empty_second_ammo
> 
> ;конец релоада
> anm_close			                = winchester1300_pistol_reload_end, winchester1300_reload_end
> anm_close_empty			            = winchester1300_pistol_reload_empty_end, winchester1300_reload_end
> 
> ;расклин
> anm_reload_jammed			= winchester1300_pistol_revival, winchester1300_revival
> anm_reload_jammed_last		= winchester1300_pistol_revival, winchester1300_revival
> ```

**Comment by xrSimpodin** [comment]
you can see how it works using the example of OGSR:Gunslinger Addon
there are no problems with these animations

**Comment by xrSimpodin** [comment]
well, I can add anm_open_empty if you need it

**Comment by starlight1943ld** [comment]
I just tested it and it works great, thank you very much!
