### ISSUE TITLE
Сглаживание DLSS

### ISSUE THREAD

**Issue by Georgiy-Timoshin** [OGSR/OGSR-Engine#485]
Сегодня скачал и запустил этот [билд](https://github.com/OGSR/OGSR-Engine/releases/tag/1.oct.2024)
На мой взгляд корректней было бы переименовать ["NVIDIA DLSS" в "NVIDIA DLAA"](https://developer.nvidia.com/rtx/streamline), а то некоторые станут задавать вопросы: "почему dlss не увеличивает fps?" или "почему у dlss нет пресетов качества?".

Для включения DLSS(DLAA) производиться проверка совместимости с видеокартой или всегда можно включить???

**Comment by xrSimpodin** [comment]
Я уже сто раз объяснял, что DLAA не хайпово звучит, понимаешь?
Глупые вопросы могут задавать по абсолютно любому поводу, я на это давно не обращаю внимание.
Конечно все проверки проводятся.
