### ISSUE TITLE
Restore Grass Density reaching 0.20 range

### ISSUE THREAD

**Issue by MarcinTomaszTomaszewski** [OGSR/OGSR-Engine#487]
Hi, I've noticed that the newest build is limited with max grass density at 0.50, could you please revert this setting to the earlier range? 0.5 is a bit too low for high end GPU and 0.2 also look so much better. 

But your newest bulid have DLSS implemented and it looks and performs better than smaa, so I would like to stick to the realease from the OCT 1st.

Many thanks in advance!

**Comment by xrSimpodin** [comment]
this is done because there are brainless players who turn all grass sliders to the maximum and then complain that the engine lags. In the future there will be a new render, with many optimizations, including for grass, perhaps then the previous adjustment range can be returned.
