### ISSUE TITLE
вылет при соотношении 4:3

### ISSUE THREAD

**Issue by anatolevuc** [OGSR/OGSR-Engine#497]
Игра вылетает при разрешении 1280х1024/1024х768

это можно как-то исправить? 
[xray_anato_02-12-24_15-37-21.log](https://github.com/user-attachments/files/17978001/xray_anato_02-12-24_15-37-21.log)

**Comment by xrSimpodin** [comment]
Это не проблема движка, а проблема той сборки в которую вы играете.
```
[error]Description   : XML node not found
[error]Arguments     : dragdrop_animation
```
