### ISSUE TITLE
Ошибки при сборке.

### ISSUE THREAD

**Issue by Balavnik** [OGSR/OGSR-Engine#500]
Возникает ряд ошибок(более 150) при сборке. Жалобы на синтаксис. Ничего не менял.

Пример: 

> Severity	Code	Description	Project	File	Line	Suppression State	Details
> Error	C3878	syntax error: unexpected token '*' following 'simple-type-specifier'	xrCore	OGSR-Engine-main\ogsr_engine\xrCore\FS.h	356		
>

**Comment by PRXPHET** [comment]
Версия VS Studio какая?

**Comment by xrSimpodin** [comment]
Для последней студии нужен фикс сборки https://github.com/OGSR/OGSR-Engine/commit/8c83c8bdbf0531fbea0e7efc22fc78e01e4171b9
в приватной версии он давно есть, а тут в паблике не было

**Comment by Balavnik** [comment]
Установил этот фикс, полностью перекачал всё, теперь возникает >8600 ошибок.
`'AStar::_Vertex<_dist_type,_vertex>::__vertex': expected an expression instead of a type`
