### ISSUE TITLE
Quicksave по горячей клавише

### ISSUE THREAD

**Issue by WladTriTopora** [OGSR/OGSR-Engine#97]
Кто-то случайно включил обратно в последних коммитах? 
В коде не смотрел, но после замены движка на свежую версию, заметил при тестах в игре.
Пред. версия у меня была где-то 2-х недельной давности, там ещё был отключен.

**Comment by KRodinn** [comment]
Вроде всегда работал, никто не отключал. Специально, по крайней мере.

**Comment by WladTriTopora** [comment]
Надо бы отключить нафиг.
Сохраняться без остановки процесса - злое зло же.
В OGSE был же выпилен тоже.

**Comment by KRodinn** [comment]
Это распространённый миф

**Comment by KRodinn** [comment]
При всём уважении к разрабам ОГСЕ, но их утверждения о вреде квиксейвов - это бред сивой кобылы.

**Comment by WladTriTopora** [comment]
Я не буду спорить, но по моему опыту, в оригинальном ТЧ бились чаще всего именно квиксейвы и автосейвы.

**Comment by KRodinn** [comment]
>> abort("SAVE FILE IS CORRUPT")
ууу, такое вообще ни разу в жизни не ловил. Хотя прошёл огромное кол-во всяких модов на ТЧ и не только. Это вообще какая-то экзотика. Тут может быть виновато что угодно, но уж точно не квиксейвы.
А в распространённом понимании "битьё сейвов" - это когда виснет логика дверей и тп. По этой теме @dsh2dsh уже ответил.

**Comment by WladTriTopora** [comment]
Ну это ж 
if reader:r_eof() then 
abort("SAVE FILE IS CORRUPT")
end

Насколько я помню, в ванильном ТЧ есть только в bind_stalker, bind_monster и xr_motivator, вроде.

**Comment by KRodinn** [comment]
Ну я как бы и так понял, что это.

**Comment by dsh2dsh** [comment]
Это уже нужно с конкретными скриптами разбираться. Сам по себе, квиксейв ничем не отличается от сейва через меню.
